// packages/core/src/components/server/EventPanel/EventPanel.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Stories for EventPanel showcasing mobile details, desktop layout, and carousel composition with navigation controls.

import type { Meta, StoryObj } from '@storybook/react';
import { Markdown } from '@storybook/addon-docs/blocks';
import * as React from 'react';
import { EventPanel, type EventPanelProps } from './EventPanel';
import { Control } from '../../client/Control';
import { Button } from '../../client/Button';
import { AvatarGroup } from '../../client/AvatarGroup';
import { Carousel } from '../../client/Carousel';
import { Chip } from '../Chip/Chip';
import { EventIcon, MapIcon, PlayIcon, ShareIcon, ArrowOutwardIcon } from '../../../icons';
import Readme from './README.md?raw';

const sampleUsers: React.ComponentProps<typeof AvatarGroup>['users'] = [
  { name: 'Inez Ortiz', imageUrl: 'https://i.pravatar.cc/96?img=1' },
  { name: 'Samir Patel', imageUrl: 'https://i.pravatar.cc/96?img=2' },
  { name: 'Dana Truong', imageUrl: 'https://i.pravatar.cc/96?img=3' },
  { name: 'Lena Brooks', imageUrl: 'https://i.pravatar.cc/96?img=4' }
];

const renderChips = (): React.ReactNode[] => [
  <Chip key="inperson" label="In-person" icon={<EventIcon decorative />} />,
  <Chip key="livestream" label="Live stream" icon={<ShareIcon decorative />} />,
  <Chip key="campus" label="Downtown campus" icon={<MapIcon decorative />} />
];

const renderAvatars = (): React.ReactNode => (
  <AvatarGroup users={sampleUsers} showMessage={false} count={128} avatarsToDisplay={4} />
);

const renderButtons = (): React.ReactNode => (
  <>
    <Button variant="primary" endIcon={<ArrowOutwardIcon />}>
      Find tickets
    </Button>
    <Button variant="secondary" startIcon={<EventIcon />}>
      Add to calendar
    </Button>
  </>
);

const renderLeftAction = (): React.ReactNode => (
  <Control ariaLabel="Previous event" variant="light" icon={<PlayIcon />} />
);

const renderRightAction = (): React.ReactNode => (
  <Control ariaLabel="Next event" variant="light" icon={<ShareIcon />} />
);

const baseArgs: EventPanelProps = {
  imgSrc: 'https://picsum.photos/seed/event-panel/560/490',
  imgAlt: 'People networking at an outdoor tech event',
  subtitle: 'Community',
  title: 'Summer product jam',
  description:
    'Join fellow builders for rapid prototyping, breakout sessions, and pop-up demos across the venue.',
  leftAction: renderLeftAction(),
  rightAction: renderRightAction(),
  chips: renderChips(),
  avatars: renderAvatars(),
  buttons: renderButtons()
};

const meta: Meta<EventPanelProps> = {
  title: 'Server components/EventPanel',
  component: EventPanel,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  },
  args: baseArgs
};

export default meta;

type Story = StoryObj<EventPanelProps>;

export const Default: Story = {
  name: 'Default (mobile)',
  parameters: {
    viewport: { defaultViewport: 'mobile2' }
  },
  render: args => {
    return (
      <div className="group" data-is-in-view="true">
        <EventPanel {...args} />
      </div>
    );
  }
};

export const Desktop: Story = {
  parameters: {
    viewport: { defaultViewport: 'desktop' }
  },
  render: args => {
    return (
      <div className="group" data-is-in-view="true">
        <EventPanel {...args} />
      </div>
    );
  }
};

export const CarouselComposition: Story = {
  name: 'Carousel composition',
  render: () => {
    const events: Array<Pick<EventPanelProps, 'imgSrc' | 'imgAlt'> & Partial<EventPanelProps>> = [
      {
        imgSrc: 'https://picsum.photos/seed/event-carousel-1/560/490',
        imgAlt: 'Stage lighting over an evening panel',
        title: 'Founder fireside',
        subtitle: 'Conversation',
        description: 'Hear how product teams iterate quickly with real user input.',
        chips: renderChips(),
        avatars: renderAvatars(),
        buttons: renderButtons(),
        leftAction: renderLeftAction(),
        rightAction: renderRightAction()
      },
      {
        imgSrc: 'https://picsum.photos/seed/event-carousel-2/560/490',
        imgAlt: 'Attendees collaborating at a workshop table',
        title: 'Design lab',
        subtitle: 'Workshop',
        description: 'Sketch with mentors and develop new flows for your app.',
        chips: renderChips(),
        avatars: renderAvatars(),
        buttons: renderButtons(),
        leftAction: renderLeftAction(),
        rightAction: renderRightAction()
      },
      {
        imgSrc: 'https://picsum.photos/seed/event-carousel-3/560/490',
        imgAlt: 'Open air venue surrounded by city skyline',
        title: 'City socials',
        subtitle: 'Networking',
        description: 'Connect with peers across product, engineering, and design.',
        chips: renderChips(),
        avatars: renderAvatars(),
        buttons: renderButtons(),
        leftAction: renderLeftAction(),
        rightAction: renderRightAction()
      },
      {
        imgSrc: 'https://picsum.photos/seed/event-carousel-4/560/490',
        imgAlt: 'Speakers presenting on a large screen stage',
        title: 'Launch keynote',
        subtitle: 'Keynote',
        description: 'See the latest platform capabilities and roadmap reveals.',
        chips: renderChips(),
        avatars: renderAvatars(),
        buttons: renderButtons(),
        leftAction: renderLeftAction(),
        rightAction: renderRightAction()
      },
      {
        imgSrc: 'https://picsum.photos/seed/event-carousel-5/560/490',
        imgAlt: 'Outdoor lounge with colorful lighting',
        title: 'After hours',
        subtitle: 'Social',
        description: 'Wind down with curated music and lounge sessions.',
        chips: renderChips(),
        avatars: renderAvatars(),
        buttons: renderButtons(),
        leftAction: renderLeftAction(),
        rightAction: renderRightAction()
      },
      {
        imgSrc: 'https://picsum.photos/seed/event-carousel-6/560/490',
        imgAlt: 'Hands-on demo stations with interactive displays',
        title: 'Demo floor',
        subtitle: 'Experience',
        description: 'Interact with partner booths and emerging prototypes.',
        chips: renderChips(),
        avatars: renderAvatars(),
        buttons: renderButtons(),
        leftAction: renderLeftAction(),
        rightAction: renderRightAction()
      }
    ];

    return (
      <Carousel ariaLabel="Upcoming events carousel" align="center" loop peek>
        {events.map((event, index) => (
          <EventPanel key={index} {...event} />
        ))}
      </Carousel>
    );
  }
};
