// packages/core/src/components/server/EventPanel/EventPanel.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: EventPanel renders a hero image with overlay navigation and stacked details with optional labels, avatars, and CTAs.

import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type NativeDivProps = Omit<React.HTMLAttributes<HTMLDivElement>, 'children'>;

export interface EventPanelProps extends NativeDivProps {
  imgSrc: string;
  imgAlt: string;
  loading?: 'lazy' | 'eager';
  leftAction?: React.ReactNode;
  rightAction?: React.ReactNode;
  subtitle?: string;
  title?: string;
  description?: string;
  labels?: React.ReactNode;
  avatars?: React.ReactNode;
  buttons?: React.ReactNode;
}

const baseClasses = `
  isolate
`;

const mediaClasses = `
  relative overflow-clip w-[390px] h-[390px] lg:w-[560px] lg:h-[490px]
  transform-gpu transition-transform duration-700 ease-in-out motion-reduce:transition-none
  scale-110 group-data-[is-in-view=true]:scale-100 mx-24
`;

const imageClasses = `
  block size-full object-cover object-center
`;

const overlayClasses = `
  pointer-events-none absolute inset-0 overlay-image-overlay
`;

const actionsBarClasses = `
  absolute inset-x-0 bottom-0 flex items-center justify-between p-4
`;

const detailsClasses = `
  px-32 py-4 lg:hidden w-[380px]
`;

const subtitleClasses = `
  text-sm tracking-wide uppercase text-color-content-weak
`;

const titleClasses = `
  text-2xl text-color-content-default
`;

const descriptionClasses = `
  text-base text-color-content-weak
`;

const metaClasses = `
  flex flex-col items-start gap-2 text-sm text-color-content-weak
`;

const labelsClasses = `
  flex gap-3
`;

const buttonsClasses = `
  mt-2 hidden group-data-[is-in-view=true]:flex gap-3 items-center justify-end w-[390px] lg:w-[560px]
`;

const leftClasses = `
  flex items-center gap-2
`;

const rightClasses = `
  flex items-center gap-2
`;

const avatarsClasses = `
  flex -space-x-2 items-center
`;

const isNonEmpty = (value?: string): value is string =>
  typeof value === 'string' && value.trim().length > 0;

export const EventPanel = React.forwardRef<HTMLDivElement, EventPanelProps>(
  (
    {
      imgSrc,
      imgAlt,
      loading = 'lazy',
      leftAction,
      rightAction,
      subtitle,
      title,
      description,
      labels,
      avatars,
      buttons,
      className,
      ...rest
    },
    ref
  ) => {
    const baseClassName = collapseWhitespace(composeClasses(baseClasses, className));
    const mediaClassName = collapseWhitespace(composeClasses(mediaClasses));
    const imageClassName = collapseWhitespace(composeClasses(imageClasses));
    const overlayClassName = collapseWhitespace(composeClasses(overlayClasses));
    const actionsBarClassName = collapseWhitespace(composeClasses(actionsBarClasses));
    const detailsClassName = collapseWhitespace(composeClasses(detailsClasses));
    const subtitleClassName = collapseWhitespace(composeClasses(subtitleClasses));
    const titleClassName = collapseWhitespace(composeClasses(titleClasses));
    const descriptionClassName = collapseWhitespace(composeClasses(descriptionClasses));
    const metaClassName = collapseWhitespace(composeClasses(metaClasses));
    const labelsClassName = collapseWhitespace(composeClasses(labelsClasses));
    const buttonsClassName = collapseWhitespace(composeClasses(buttonsClasses));
    const leftClassName = collapseWhitespace(composeClasses(leftClasses));
    const rightClassName = collapseWhitespace(composeClasses(rightClasses));
    const avatarsClassName = collapseWhitespace(composeClasses(avatarsClasses));

    return (
      <div {...rest} ref={ref} className={baseClassName} data-slot="base">
        <div className={mediaClassName} data-slot="_media">
          <img
            src={imgSrc}
            alt={imgAlt}
            className={imageClassName}
            data-slot="_image"
            loading={loading}
          />
          <div className={overlayClassName} data-slot="_overlay" />
          <div className={actionsBarClassName} data-slot="_actionsBar">
            <div className={leftClassName} data-slot="_left">
              {leftAction}
            </div>
            <div className={rightClassName} data-slot="_right">
              {rightAction}
            </div>
          </div>
        </div>
        <div className={detailsClassName} data-slot="_details">
          {isNonEmpty(subtitle) ? (
            <div className={subtitleClassName} data-slot="_subtitle">
              {subtitle}
            </div>
          ) : null}
          {isNonEmpty(title) ? (
            <div className={titleClassName} data-slot="_title">
              {title}
            </div>
          ) : null}
          {isNonEmpty(description) ? (
            <div className={descriptionClassName} data-slot="_description">
              {description}
            </div>
          ) : null}
          {labels || avatars ? (
            <div className={metaClassName} data-slot="_meta">
              <div className={labelsClassName} data-slot="_labels">
                {labels}
              </div>
              <div className={avatarsClassName} data-slot="_avatars">
                {avatars}
              </div>
            </div>
          ) : null}
        </div>
        {buttons ? (
          <div className={buttonsClassName} data-slot="_buttons">
            {buttons}
          </div>
        ) : null}
      </div>
    );
  }
);

EventPanel.displayName = 'EventPanel';
