// packages/core/src/icons/ForwardIcon/ForwardIcon.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: ForwardIcon renders a forward glyph SVG supporting decorative or labeled usage with optional title and color props

import * as React from 'react';

export interface ForwardIconProps extends React.SVGAttributes<SVGSVGElement> {
  decorative?: boolean;
  title?: string;
  titleId?: string;
  color?: string;
}

type ForwardIconElement = SVGSVGElement;

export const ForwardIcon = React.forwardRef<ForwardIconElement, ForwardIconProps>(
  (
    {
      decorative = true,
      width = '20px',
      height = '20px',
      title,
      titleId: providedTitleId,
      color = 'currentColor',
      className,
      'aria-labelledby': ariaLabelledby,
      ...rest
    },
    ref
  ) => {
    const generatedTitleId = React.useId();
    const resolvedTitleId = title ? (providedTitleId ?? generatedTitleId) : undefined;

    const computedAriaHidden = decorative ? 'true' : undefined;
    const computedRole = decorative ? undefined : 'img';
    const computedAriaLabelledby =
      !decorative && title && resolvedTitleId ? resolvedTitleId : ariaLabelledby;

    return (
      <svg
        ref={ref}
        {...rest}
        className={className}
        viewBox="0 0 20 20"
        width={width}
        height={height}
        fill={color}
        aria-hidden={computedAriaHidden}
        role={computedRole}
        aria-labelledby={computedAriaLabelledby}
      >
        {!decorative && title ? <title id={resolvedTitleId}>{title}</title> : null}
        <g transform="scale(0.0208333333,0.0208333333) translate(0,960)">
          <path d="M654.48-292.35 595.83-351l159-159-159-159 58.65-58.65L872.13-510 654.48-292.35Zm-518.61 90.48V-354q0-82.15 57.67-139.83 57.68-57.67 139.83-57.67h172.65L388.52-669l58.41-58.65L664.59-510 446.93-292.35 388.52-351l117.5-117.5H333.37q-47.85 0-81.17 33.33-33.33 33.32-33.33 81.17v152.13h-83Z" />
        </g>
      </svg>
    );
  }
);

ForwardIcon.displayName = 'ForwardIcon';
