// packages/core/src/icons/ForwardIcon/ForwardIcon.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook stories for ForwardIcon showcasing decorative default and non-decorative role=img usage with color/className controls.

import type { Meta, StoryObj } from '@storybook/react';
import { ForwardIcon, ForwardIconProps } from './ForwardIcon';

const meta: Meta<ForwardIconProps> = {
  title: 'Icons/ForwardIcon',
  component: ForwardIcon,
  args: {
    decorative: true,
    color: 'currentColor'
  },
  argTypes: {
    decorative: { control: 'boolean' },
    title: { control: 'text' },
    titleId: { control: 'text' },
    color: { control: 'color' },
    className: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<ForwardIconProps>;

export const Default: Story = {};

export const NonDecorative: Story = {
  args: {
    decorative: false,
    title: 'Dismiss notification',
    titleId: 'close-icon-title'
  }
};
