// packages/core/src/icons/ArrowDropDownIcon/ArrowDropDownIcon.test.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Checks ArrowDropDownIcon decorative defaults, labeled role=img handling, color prop passthrough, className merge, and automatic title id creation.

import { render, screen } from '@testing-library/react';
import { ArrowDropDownIcon } from './ArrowDropDownIcon';

describe('ArrowDropDownIcon', () => {
  it('defaults to decorative and sets aria-hidden="true"', () => {
    render(<ArrowDropDownIcon data-testid="icon" />);
    expect(screen.getByTestId('icon')).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders non-decorative icons with title as role="img" and aria-labelledby', () => {
    render(<ArrowDropDownIcon decorative={false} title="Dismiss" titleId="close-icon" />);
    const svg = screen.getByRole('img', { name: 'Dismiss' });
    expect(svg).toHaveAttribute('aria-labelledby', 'close-icon');
  });

  it('applies the color prop to the fill attribute', () => {
    render(<ArrowDropDownIcon data-testid="icon" color="#123456" />);
    expect(screen.getByTestId('icon')).toHaveAttribute('fill', '#123456');
  });

  it('merges className onto the svg element', () => {
    render(<ArrowDropDownIcon data-testid="icon" className="custom-class" />);
    expect(screen.getByTestId('icon')).toHaveClass('custom-class');
  });

  it('generates a title id when non-decorative with title and no titleId', () => {
    render(<ArrowDropDownIcon decorative={false} title="Dismiss" />);
    const img = screen.getByRole('img', { name: 'Dismiss' });
    expect(img).toHaveAttribute('aria-labelledby');
  });
});
