// packages/core/src/components/client/AvatarGroup/AvatarGroup.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Storybook stories for AvatarGroup showing default copy, hiding message, large counts, and trimmed user lists, with indicator/message/count controls and users control disabled.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react-vite';
import * as React from 'react';
import Readme from './README.md?raw';
import { AvatarGroup, type AvatarGroupProps } from './AvatarGroup';

const sampleUsers: AvatarGroupProps['users'] = [
  { name: 'Aliyah Ward', imageUrl: 'https://i.pravatar.cc/64?img=1' },
  { name: 'Bruno Castro', imageUrl: 'https://i.pravatar.cc/64?img=2' },
  { name: 'Carmen Reyes', imageUrl: 'https://i.pravatar.cc/64?img=3' },
  { name: 'Diego Luna', imageUrl: 'https://i.pravatar.cc/64?img=4' },
  { name: 'Elisa Novak', imageUrl: 'https://i.pravatar.cc/64?img=5' },
  { name: 'Fiona Zhang', imageUrl: 'https://i.pravatar.cc/64?img=6' }
];

const meta: Meta<AvatarGroupProps> = {
  title: 'Client components/AvatarGroup',
  component: AvatarGroup,
  args: {
    indicator: '+',
    message: 'others interested',
    showMessage: true,
    avatarsToDisplay: 4,
    count: 12,
    users: sampleUsers
  },
  argTypes: {
    indicator: { control: 'text' },
    count: { control: 'number' },
    message: { control: 'text' },
    showMessage: { control: 'boolean' },
    avatarsToDisplay: { control: 'number' },
    users: { control: false }
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<AvatarGroupProps>;

export const Default: Story = {
  args: {}
};

export const NoMessage: Story = {
  args: {
    showMessage: false
  }
};

export const LongCount: Story = {
  args: {
    count: 6892
  }
};

export const FewUsers: Story = {
  args: {
    users: sampleUsers.slice(0, 2),
    count: undefined
  }
};
