// packages/core/src/components/client/DatePicker/DatePicker.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook story for DatePicker loading RSuite styles and rendering the default range picker configuration.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react';
import 'rsuite/DateRangePicker/styles/index.css';

import Readme from './README.md?raw';
import { DatePicker } from './DatePicker';

const meta: Meta<typeof DatePicker> = {
  title: 'Client components/DatePicker',
  component: DatePicker,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<typeof DatePicker>;

export const Default: Story = {
  args: {}
};
