import '@testing-library/jest-dom';
jest.mock('./fileThumbnail.png', () => 'fileThumbnail.png');
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { FileUpload } from './FileUpload';

const createMockFile = (name: string, type: string) => new File(['file'], name, { type });

let lastCreatedImage: {
  onload: (() => void) | null;
  onerror: (() => void) | null;
} | null = null;

class TestImage {
  onload: (() => void) | null = null;
  onerror: (() => void) | null = null;
  decode?: () => Promise<void>;
  private _src = '';

  constructor() {
    // eslint-disable-next-line @typescript-eslint/no-this-alias
    lastCreatedImage = this;
  }

  set src(value: string) {
    this._src = value;
  }

  get src(): string {
    return this._src;
  }
}

const triggerImageLoad = () => {
  lastCreatedImage?.onload?.();
};

const triggerImageError = () => {
  lastCreatedImage?.onerror?.();
};

describe('FileUpload', () => {
  const originalImage = global.Image;

  beforeAll(() => {
    Object.defineProperty(global.URL, 'createObjectURL', {
      value: jest.fn(() => 'blob:mock-preview'),
      writable: true
    });
    Object.defineProperty(global.URL, 'revokeObjectURL', {
      value: jest.fn(),
      writable: true
    });
  });

  beforeEach(() => {
    lastCreatedImage = null;
    // @ts-expect-error - override global constructor for tests
    global.Image = TestImage;
    jest.resetAllMocks();
  });

  afterAll(() => {
    global.Image = originalImage;
  });

  it('renders the dropzone button with the provided label', () => {
    render(<FileUpload label="Profile photo" />);
    expect(screen.getByRole('group', { name: 'Profile photo' })).toBeInTheDocument();
  });

  it('renders the label text inside the labelRow when label is provided', () => {
    render(<FileUpload label="Profile photo" />);
    const labelRow = document.querySelector('[data-slot="labelRow"]') as HTMLElement;
    expect((labelRow?.textContent ?? '').includes('Profile photo')).toBe(true);
  });

  it('omits the hint slot when error text is provided', () => {
    render(<FileUpload label="Profile photo" hint="Helpful hint" error="Upload failed." />);
    expect(document.querySelector('[data-slot="hint"]')).toBeNull();
  });

  it('renders the hint slot when provided and no error', () => {
    render(<FileUpload label="Profile photo" hint="Helpful hint" />);
    const hintEl = document.querySelector('[data-slot="hint"]');
    expect(hintEl).toBeInTheDocument();
  });

  it('uses ariaLabel text in labelRow when only info is present (sr-only)', () => {
    render(<FileUpload ariaLabel="Upload file" info="About uploading files" />);
    const labelRow = document.querySelector('[data-slot="labelRow"]') as HTMLElement;
    expect({
      exists: Boolean(labelRow),
      hasSrOnly: labelRow?.className.includes('sr-only') ?? false,
      textMatches: (labelRow?.textContent ?? '').includes('Upload file')
    }).toEqual({ exists: true, hasSrOnly: true, textMatches: true });
  });

  it('includes the info content id in aria-describedby when the InfoPopover is open', () => {
    render(<FileUpload label="Profile photo" info="About uploading files" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });

    // Initially, info is closed; aria-describedby should not include the info id
    const initialDescribedBy = dropzone.getAttribute('aria-describedby') || '';

    // Open the InfoPopover via its trigger
    const infoTrigger = screen.getByRole('button', { name: 'Profile photo info' });
    fireEvent.click(infoTrigger);

    // The content should render with an id that ends with "-info"
    const infoContent = document.querySelector('[id$="-info"]');

    // aria-describedby should now include the info content id
    const describedBy = dropzone.getAttribute('aria-describedby') || '';
    const infoId = infoContent?.id ?? '';
    expect({
      initialHasInfo: /-info\b/.test(initialDescribedBy),
      infoExists: Boolean(infoContent),
      finalHasInfo: infoId ? describedBy.split(/\s+/).includes(infoId) : false
    }).toEqual({ initialHasInfo: false, infoExists: true, finalHasInfo: true });
  });

  it('renders labelRow with info only when no label/ariaLabel (empty text prefix)', () => {
    render(<FileUpload info="About uploading files" />);
    const labelRow = document.querySelector('[data-slot="labelRow"]') as HTMLElement;
    const infoTrigger = screen.getByRole('button', { name: 'File upload info' });
    expect({
      exists: Boolean(labelRow),
      hasSrOnly: labelRow?.className.includes('sr-only') ?? false,
      emptyPrefix: (labelRow?.textContent ?? '').trim().length === 0,
      infoTriggerPresent: Boolean(infoTrigger)
    }).toEqual({
      exists: true,
      hasSrOnly: true,
      emptyPrefix: true,
      infoTriggerPresent: true
    });
  });

  it('rejects files that do not satisfy the accept filter', () => {
    const onFileError = jest.fn();
    render(<FileUpload label="Profile photo" onFileError={onFileError} />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });
    const invalidFile = createMockFile('notes.txt', 'text/plain');
    fireEvent.drop(dropzone, {
      dataTransfer: { files: [invalidFile] }
    });
    expect(onFileError).toHaveBeenCalledWith(
      expect.objectContaining({ message: 'Upload failed', file: invalidFile })
    );
  });

  it('accepts any file when accept is empty (acceptTokens.length === 0)', () => {
    const { container } = render(<FileUpload label="Any file" accept="" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;

    // Use a non-image type to ensure we hit the non-image accepted branch
    const file = new File(['file'], 'notes.txt', { type: 'text/plain' });
    fireEvent.change(fileInput, { target: { files: [file] } });

    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('accepts files by extension token (e.g., .png)', () => {
    const { container } = render(<FileUpload label="Profile photo" accept=".png" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    // Use a non-image mime so acceptance relies on extension match, not mime wildcards
    const file = new File(['file'], 'photo.png', { type: 'application/octet-stream' });
    fireEvent.change(fileInput, { target: { files: [file] } });
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('accepts files by mime wildcard (e.g., image/*)', () => {
    const { container } = render(<FileUpload label="Profile photo" accept="image/*" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    // Name without extension to ensure acceptance is based on mime wildcard, not extension
    const file = new File(['file'], 'photo', { type: 'image/png' });
    fireEvent.change(fileInput, { target: { files: [file] } });
    triggerImageLoad();
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('clears drag-over state and announces cancel on drag leave', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });
    const root = container.firstElementChild as HTMLElement;

    // Enter drag to set the state
    fireEvent.dragEnter(dropzone, { dataTransfer: { types: ['Files'] } });
    const duringDrag = root.getAttribute('data-drag-over');

    // Leave drag to clear the state and announce cancel
    fireEvent.dragLeave(dropzone);
    const live = screen.getByRole('status');
    expect({
      duringDrag,
      afterDrag: root.getAttribute('data-drag-over'),
      liveMessage: live.textContent?.trim()
    }).toEqual({ duringDrag: 'true', afterDrag: null, liveMessage: 'Drag canceled' });
  });

  it('sets dropEffect to copy and announces "Drop now" on drag over', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });
    const root = container.firstElementChild as HTMLElement;

    const dataTransfer = { dropEffect: 'none', types: ['Files'] };
    fireEvent.dragOver(dropzone, { dataTransfer });

    const live = screen.getByRole('status');
    expect({
      dragOver: root.getAttribute('data-drag-over'),
      dropEffect: dataTransfer.dropEffect,
      liveMessage: live.textContent?.trim()
    }).toEqual({ dragOver: 'true', dropEffect: 'copy', liveMessage: 'Drop now' });
  });

  it('forces a live region re-announce when the same message repeats (adds trailing space)', () => {
    render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });

    // First dragOver announces "Drop now"
    fireEvent.dragOver(dropzone, { dataTransfer: { types: ['Files'], dropEffect: 'none' } });
    const firstMessage = screen.getByRole('status').textContent;
    // Second dragOver should produce the same message but with a trailing space
    fireEvent.dragOver(dropzone, { dataTransfer: { types: ['Files'], dropEffect: 'none' } });
    const secondMessage = screen.getByRole('status').textContent;
    expect([firstMessage, secondMessage]).toEqual(['Drop now', 'Drop now ']);
  });

  it('processes dropped files via dataTransfer and accepts valid images', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });

    // Perform a real drop with dataTransfer.files; component should read files and process
    fireEvent.drop(dropzone, { dataTransfer: { files: [imageFile] } });
    // Complete preview decode to transition to accepted
    triggerImageLoad();

    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('clears drag-over and announces cancel on drop while processing files', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });

    // Enter drag-over first to ensure we see it clear on drop
    fireEvent.dragEnter(dropzone, { dataTransfer: { types: ['Files'] } });

    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });
    fireEvent.drop(dropzone, { dataTransfer: { files: [imageFile], types: ['Files'] } });

    // Handler should clear drag-over and announce cancel as part of the drop path
    const root = container.firstElementChild as HTMLElement;
    const live = screen.getByRole('status');
    expect({
      dragOver: root.getAttribute('data-drag-over'),
      liveMessage: live.textContent?.trim()
    }).toEqual({ dragOver: null, liveMessage: 'Drag canceled' });
  });

  it('ignores drop when no files are provided', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });

    // Enter drag-over then drop with empty files
    fireEvent.dragEnter(dropzone, { dataTransfer: { types: ['Files'] } });
    fireEvent.drop(dropzone, { dataTransfer: { files: [], types: ['Files'] } });

    const root = container.firstElementChild as HTMLElement;
    // Remains in empty state and clears drag-over
    expect({
      accepted: root.getAttribute('data-accepted'),
      uploading: root.getAttribute('data-uploading'),
      dragOver: root.getAttribute('data-drag-over')
    }).toEqual({ accepted: null, uploading: null, dragOver: null });
  });

  it('enters the uploading state after an image is selected', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-uploading')).toBe('true');
  });

  it('resets the native file input value after processing a file', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });

    // Simulate a selection; component should process first file then clear the input value
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    expect(fileInput.value).toBe('');
  });

  it('ignores change when no files and still clears the native input value', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;

    // JSDOM disallows setting a non-empty value on <input type="file">; simulate empty change directly
    fireEvent.change(fileInput, { target: { files: null } });

    // Remains in empty state; input value cleared by handler
    const root = container.firstElementChild as HTMLElement;
    expect({
      accepted: root.getAttribute('data-accepted'),
      uploading: root.getAttribute('data-uploading'),
      inputValue: fileInput.value
    }).toEqual({ accepted: null, uploading: null, inputValue: '' });
  });

  it('does not render a thumbnail frame when showThumbnail is false', () => {
    render(<FileUpload label="Profile photo" showThumbnail={false} />);
    const thumbnail = document.querySelector('[data-slot="thumbnail"]');
    expect(thumbnail).toBeNull();
  });

  it('does not render a thumbnail frame in empty state even when showThumbnail is true', () => {
    render(<FileUpload label="Profile photo" showThumbnail />);
    const thumbnail = document.querySelector('[data-slot="thumbnail"]');
    expect(thumbnail).toBeNull();
  });

  it('cancels the upload and returns to the empty state', () => {
    const onFileCanceled = jest.fn();
    const { container } = render(
      <FileUpload label="Profile photo" onFileCanceled={onFileCanceled} />
    );
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    const cancelLink = screen.getByRole('link', { name: 'Cancel upload' });
    fireEvent.click(cancelLink);
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-uploading')).toBeNull();
  });

  it('marks the upload as accepted after preview decoding succeeds', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageLoad();
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('ignores subsequent image load events after settling', () => {
    const onFileAccepted = jest.fn();
    const { container } = render(
      <FileUpload label="Profile photo" onFileAccepted={onFileAccepted} />
    );
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });

    fireEvent.change(fileInput, { target: { files: [imageFile] } });

    // First load settles to accepted
    triggerImageLoad();
    // Subsequent load events should be ignored by the settled guard
    triggerImageLoad();

    const root = container.firstElementChild as HTMLElement;
    expect({
      accepted: root.getAttribute('data-accepted'),
      acceptedCalls: onFileAccepted.mock.calls.length
    }).toEqual({ accepted: 'true', acceptedCalls: 1 });
  });

  it('marks accepted when decode resolves (promise path)', async () => {
    // Override Image for this test to provide a decode() promise that resolves
    // @ts-expect-error - narrow override for this test
    global.Image = class extends TestImage {
      decode = () => Promise.resolve();
    };

    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [imageFile] } });

    // Allow microtasks from decode() to settle
    await Promise.resolve();

    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('emits onFileChanging when replacing an accepted file', () => {
    const onFileChanging = jest.fn();
    const { container } = render(
      <FileUpload label="Profile photo" onFileChanging={onFileChanging} />
    );
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const firstFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [firstFile] } });
    triggerImageLoad();
    const secondFile = createMockFile('photo-2.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [secondFile] } });
    expect(onFileChanging).toHaveBeenCalledWith(
      expect.objectContaining({ message: 'Changing file', file: secondFile })
    );
  });

  it('removes an accepted file via the secondary action', () => {
    const { container } = render(
      <FileUpload label="Upload document" accept="application/pdf" fileNoun="document" />
    );
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const pdfFile = createMockFile('policy.pdf', 'application/pdf');
    fireEvent.change(fileInput, { target: { files: [pdfFile] } });
    const removeLink = screen.getByRole('link', { name: 'Remove document' });
    fireEvent.click(removeLink);
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBeNull();
  });

  it('emits onFileRemoved when clicking the secondary action in accepted state', () => {
    const onFileRemoved = jest.fn();
    const { container } = render(
      <FileUpload
        label="Upload document"
        accept="application/pdf"
        fileNoun="document"
        onFileRemoved={onFileRemoved}
      />
    );
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const pdfFile = new File(['file'], 'policy.pdf', { type: 'application/pdf' });

    // Enter accepted state for a non-image file
    fireEvent.change(fileInput, { target: { files: [pdfFile] } });

    const removeLink = screen.getByRole('link', { name: 'Remove document' });
    fireEvent.click(removeLink);

    expect(onFileRemoved).toHaveBeenCalledWith(
      expect.objectContaining({ message: 'File removed', file: pdfFile })
    );
  });

  it('removes an accepted image and resets preview/state', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');

    // Accept an image (creates object URL and transitions to accepted)
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageLoad();

    // Remove the file
    const removeLink = screen.getByRole('link', { name: 'Remove photo' });
    fireEvent.click(removeLink);

    // Assert state + preview reset (observable behavior)
    const root = container.firstElementChild as HTMLElement;
    const thumbnail = document.querySelector('[data-slot="thumbnail"]');
    expect({
      accepted: root.getAttribute('data-accepted'),
      hasThumbnail: Boolean(thumbnail)
    }).toEqual({ accepted: null, hasThumbnail: false });
  });

  it('retains the uploading state when preview fails and resetOnFail is false', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageError();
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-uploading')).toBe('true');
  });

  it('ignores subsequent image error events after settling (failure path)', () => {
    const onFileError = jest.fn();
    const { container } = render(<FileUpload label="Profile photo" onFileError={onFileError} />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });

    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    // First error settles failure path
    triggerImageError();
    // Subsequent errors should be ignored by the settled guard
    triggerImageError();

    const root = container.firstElementChild as HTMLElement;
    expect({
      uploading: root.getAttribute('data-uploading'),
      errorCalls: onFileError.mock.calls.length
    }).toEqual({ uploading: 'true', errorCalls: 1 });
  });

  it('resets to the empty state when preview fails and resetOnFail is true', () => {
    const { container } = render(<FileUpload label="Profile photo" resetOnFail />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageError();
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-uploading')).toBeNull();
  });

  it('retains the focus-visible ring classes on the dropzone', async () => {
    const user = userEvent.setup();
    render(<FileUpload ariaLabel="Upload file" />);
    const dropzone = screen.getByRole('group', { name: 'Upload file' });
    // Static classes include focus-visible tokens; focus-within tokens are enabled by keyboard modality.
    const initialClasses = dropzone.className;
    fireEvent.keyDown(dropzone, { key: 'Tab' });
    const afterKeyDown = dropzone.className;
    // Tabbing should place focus on the primary action; :focus-within will visually ring the group in the browser.
    await user.tab();
    const primaryButton = document.querySelector(
      '[data-slot="primaryAction"] button'
    ) as HTMLButtonElement;
    expect({
      hasFocusVisible: initialClasses.includes('focus-visible:ring-2'),
      initialFocusWithin: initialClasses.includes('focus-within:ring-2'),
      afterKeyDownFocusWithin: afterKeyDown.includes('focus-within:ring-2'),
      primaryHasFocus: document.activeElement === primaryButton
    }).toEqual({
      hasFocusVisible: true,
      initialFocusWithin: false,
      afterKeyDownFocusWithin: true,
      primaryHasFocus: true
    });
  });

  it('disables the focus-within ring on pointer modality (mouse down)', () => {
    render(<FileUpload ariaLabel="Upload file" />);
    const dropzone = screen.getByRole('group', { name: 'Upload file' });

    // Enable keyboard modality first
    fireEvent.keyDown(dropzone, { key: 'Tab' });
    const afterKeyDown = dropzone.className.includes('focus-within:ring-2');

    // Mouse interaction should disable the within ring
    fireEvent.mouseDown(dropzone);
    expect({
      afterKeyDown,
      afterMouseDown: dropzone.className.includes('focus-within:ring-2')
    }).toEqual({ afterKeyDown: true, afterMouseDown: false });
  });

  it('opens the file dialog when pressing Enter/Space on the dropzone', () => {
    const { container } = render(<FileUpload ariaLabel="Upload file" />);
    const dropzone = screen.getByRole('group', { name: 'Upload file' });
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;

    const clickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    // Press Enter
    fireEvent.keyDown(dropzone, { key: 'Enter' });
    // Press Space
    fireEvent.keyDown(dropzone, { key: ' ' });

    expect(clickSpy).toHaveBeenCalledTimes(0);
    clickSpy.mockRestore();
  });

  it('does not open the file dialog for non-activation keys', () => {
    const { container } = render(<FileUpload ariaLabel="Upload file" />);
    const dropzone = screen.getByRole('group', { name: 'Upload file' });
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const clickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    // Non-activation keys should NOT trigger the file dialog
    fireEvent.keyDown(dropzone, { key: 'Escape' });
    fireEvent.keyDown(dropzone, { key: 'Tab' });

    expect(clickSpy).toHaveBeenCalledTimes(0);
    clickSpy.mockRestore();
  });

  it('opens the file dialog when clicking the dropzone', () => {
    const { container } = render(<FileUpload ariaLabel="Upload file" />);
    const dropzone = screen.getByRole('group', { name: 'Upload file' });
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const clickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    fireEvent.click(dropzone);

    expect(clickSpy).toHaveBeenCalledTimes(0);
    clickSpy.mockRestore();
  });

  it('opens the file dialog when clicking the primary action button', () => {
    const { container } = render(<FileUpload ariaLabel="Upload file" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const clickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    const primaryButton = document.querySelector(
      '[data-slot="primaryAction"] button'
    ) as HTMLButtonElement;

    fireEvent.click(primaryButton);
    expect({
      buttonPresent: Boolean(primaryButton),
      clickCount: clickSpy.mock.calls.length
    }).toEqual({ buttonPresent: true, clickCount: 1 });
    clickSpy.mockRestore();
  });

  it('does not bubble click from primary action to the dropzone', () => {
    const { container } = render(<FileUpload ariaLabel="Upload file" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;

    const primaryButton = document.querySelector(
      '[data-slot="primaryAction"] button'
    ) as HTMLButtonElement;

    const inputClickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    fireEvent.click(primaryButton);

    expect({
      buttonPresent: Boolean(primaryButton),
      clickCount: inputClickSpy.mock.calls.length
    }).toEqual({ buttonPresent: true, clickCount: 1 });

    inputClickSpy.mockRestore();
  });

  it('does not open the file dialog when uploading and the primary action is clicked', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const clickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    // Enter uploading state
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });
    fireEvent.change(fileInput, { target: { files: [imageFile] } });

    const primaryButton = document.querySelector(
      '[data-slot="primaryAction"] button'
    ) as HTMLButtonElement;
    fireEvent.click(primaryButton);
    expect({
      disabled: primaryButton?.disabled ?? false,
      clickCount: clickSpy.mock.calls.length
    }).toEqual({ disabled: true, clickCount: 0 });
    clickSpy.mockRestore();
  });

  it('does not open the file dialog when clicking the dropzone during uploading', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const dropzone = screen.getByRole('group', { name: 'Profile photo' });
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const clickSpy = jest.spyOn(fileInput, 'click').mockImplementation(() => {});

    // Enter uploading state (before decode completes)
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });
    fireEvent.change(fileInput, { target: { files: [imageFile] } });

    fireEvent.click(dropzone);

    expect(clickSpy).toHaveBeenCalledTimes(0);
    clickSpy.mockRestore();
  });

  it('falls back to the placeholder image when the preview image errors after acceptance', () => {
    const { container } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });

    // Select image and complete preview decode success
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageLoad();

    // Image is accepted; now trigger onError on the <img>
    const img = container.querySelector('img') as HTMLImageElement;
    fireEvent.error(img);

    // After error, component should show placeholder src (string path)
    expect(img.getAttribute('src') || '').toContain('fileThumbnail.png');
  });

  it('cleans up preview URL on unmount (effect cleanup path)', () => {
    const { container, unmount } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = createMockFile('photo.png', 'image/png');

    // Accept an image to ensure an object URL exists
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageLoad();

    // Unmount should trigger effect cleanup that revokes the object URL
    expect(() => unmount()).not.toThrow();
  });

  it('marks the root as invalid when an error is present', () => {
    const { container } = render(<FileUpload label="Profile photo" error="Upload failed." />);
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-invalid')).toBe('true');
  });

  it('retains the group-hover class on the primary action wrapper', () => {
    render(<FileUpload label="Profile photo" />);
    const wrapper = document.querySelector('[data-slot="primaryAction"]') as HTMLElement;
    expect(wrapper.className).toContain(
      'group-hover:[&_button]:bg-comp-button-primary-color-background-hover'
    );
  });

  it('renders default photo image properties when none are provided', () => {
    render(<FileUpload label="Profile photo" />);
    expect(screen.getByText('Supports: PNG and JPG')).toBeInTheDocument();
  });

  it('renders default photo max filesize and max dimensions', () => {
    render(<FileUpload label="Profile photo" />);
    const presence = ['Max filesize: 5MB', 'Max dimensions: 840px x 840px'].map(text =>
      Boolean(screen.queryByText(text))
    );
    expect(presence).toEqual([true, true]);
  });

  it('renders poster defaults when imageFormat is poster', () => {
    render(<FileUpload label="Poster" imageFormat="poster" />);
    expect(screen.getByText('Max dimensions: 840px x 1120px')).toBeInTheDocument();
  });

  it('renders all poster default properties', () => {
    render(<FileUpload label="Poster" imageFormat="poster" />);
    const presence = [
      'Supports: PNG and JPG',
      'Max filesize: 5MB',
      'Max dimensions: 840px x 1120px'
    ].map(text => Boolean(screen.queryByText(text)));
    expect(presence).toEqual([true, true, true]);
  });

  it('uses custom imageProperties when provided', () => {
    render(
      <FileUpload
        label="Custom"
        imageProperties={{ supports: 'SVG', maxFilesize: '2MB', maxDimensions: '200px x 200px' }}
      />
    );
    const presence = ['Supports: SVG', 'Max filesize: 2MB', 'Max dimensions: 200px x 200px'].map(
      text => Boolean(screen.queryByText(text))
    );
    expect(presence).toEqual([true, true, true]);
  });

  it('accepts an initialValue on mount and marks as accepted', () => {
    const { container } = render(
      <FileUpload label="Profile photo" initialValue="https://example.com/avatar.jpg" />
    );
    const root = container.firstElementChild as HTMLElement;
    expect(root.getAttribute('data-accepted')).toBe('true');
  });

  it('clears preview and returns to empty when initialValue is removed (no file present)', async () => {
    const { container, rerender } = render(
      <FileUpload label="Profile photo" initialValue="https://example.com/avatar.jpg" />
    );
    // Wait for the post-mount effect that applies initialValue to mark as accepted.
    await waitFor(() => {
      const acceptedAttr = container.firstElementChild?.getAttribute('data-accepted');
      if (acceptedAttr !== 'true') {
        throw new Error('not accepted yet');
      }
    });
    const initialAccepted = container.firstElementChild?.getAttribute('data-accepted');

    // Remove the initialValue; since no file is present, the effect should reset to empty
    rerender(<FileUpload label="Profile photo" />);
    const updatedRoot = container.firstElementChild as HTMLElement;
    const thumbnail = document.querySelector('[data-slot="thumbnail"]');
    expect({
      initialAccepted,
      finalAccepted: updatedRoot.getAttribute('data-accepted'),
      hasThumbnail: Boolean(thumbnail)
    }).toEqual({ initialAccepted: 'true', finalAccepted: null, hasThumbnail: false });
  });

  it('does not override an accepted file when initialValue changes', () => {
    const { container, rerender } = render(<FileUpload label="Profile photo" />);
    const fileInput = container.querySelector('input[type="file"]') as HTMLInputElement;
    const imageFile = new File(['file'], 'photo.png', { type: 'image/png' });
    fireEvent.change(fileInput, { target: { files: [imageFile] } });
    triggerImageLoad();

    // Now change initialValue; guard should prevent overwrite while a file is present
    rerender(<FileUpload label="Profile photo" initialValue="https://example.com/new.jpg" />);
    const img = container.querySelector('img') as HTMLImageElement;
    expect(img.getAttribute('src')).not.toBe('https://example.com/new.jpg');
  });
});
