// packages/core/src/icons/NearMeIcon/NearMeIcon.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: NearMeIcon renders a near-me glyph SVG supporting decorative or labeled usage with optional title and color props

import * as React from 'react';

export interface NearMeIconProps extends React.SVGAttributes<SVGSVGElement> {
  decorative?: boolean;
  title?: string;
  titleId?: string;
  color?: string;
}

type NearMeIconElement = SVGSVGElement;

export const NearMeIcon = React.forwardRef<NearMeIconElement, NearMeIconProps>(
  (
    {
      decorative = true,
      width = '20px',
      height = '20px',
      title,
      titleId: providedTitleId,
      color = 'currentColor',
      className,
      'aria-labelledby': ariaLabelledby,
      ...rest
    },
    ref
  ) => {
    const generatedTitleId = React.useId();
    const resolvedTitleId = title ? (providedTitleId ?? generatedTitleId) : undefined;

    const computedAriaHidden = decorative ? 'true' : undefined;
    const computedRole = decorative ? undefined : 'img';
    const computedAriaLabelledby =
      !decorative && title && resolvedTitleId ? resolvedTitleId : ariaLabelledby;

    return (
      <svg
        ref={ref}
        {...rest}
        className={className}
        viewBox="0 0 20 20"
        width={width}
        height={height}
        fill={color}
        aria-hidden={computedAriaHidden}
        role={computedRole}
        aria-labelledby={computedAriaLabelledby}
      >
        {!decorative && title ? <title id={resolvedTitleId}>{title}</title> : null}
        <g transform="scale(0.0208333333,0.0208333333) translate(0,960)">
          <path d="M507.2-135.87 405.48-409.78 131.56-511.5v-46l696.88-275.48L553.2-135.87h-46Z" />
        </g>
      </svg>
    );
  }
);

NearMeIcon.displayName = 'NearMeIcon';
