// packages/core/src/components/server/SubscriptionCard/SubscriptionCard.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: SubscriptionCard shows plan terms with active or inactive styling, optional cancel link or slot, and billing details.

import * as React from 'react';
import { TextLink } from '../TextLink';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type NativeDivProps = Omit<React.HTMLAttributes<HTMLDivElement>, 'children'>;

export interface SubscriptionCardProps extends NativeDivProps {
  terms: string;
  cancelText?: string;
  cancelHref?: string;
  isActive?: boolean;
  nextBillingDate?: string;
  memberSince?: string;
  inactiveSubtitle?: string;
  cancel?: React.ReactNode;
}

const baseClasses = `
  flex flex-col gap-2 p-4 rounded-md border bg-color-background-none transition-colors
  text-left w-[439px]
`;

const activeStateClasses = `
  border-color-background-utility-danger
`;

const inactiveStateClasses = `
  border-color-background-utility-success
`;

const headerClasses = `
  flex items-start justify-between gap-4
`;

const termsClasses = `
  text-3xl font-bold text-color-content-default
`;

const cancelSlotClasses = `
  text-sm font-medium text-color-content-weak
`;

const subtitleClasses = `
  text-sm text-color-content-weak
`;

const detailsClasses = `
  flex flex-col gap-1
`;

const detailRowClasses = `
  flex items-center gap-2
`;

const detailLabelClasses = `
  uppercase text-sm w-[135px] font-medium text-color-content-default
`;

const detailValueClasses = `
  text-sm text-color-content-weak
`;

export const SubscriptionCard = React.forwardRef<HTMLDivElement, SubscriptionCardProps>(
  (
    {
      terms,
      cancelText = 'Cancel',
      cancelHref,
      isActive = false,
      nextBillingDate,
      memberSince,
      inactiveSubtitle = 'Cancel anytime.',
      cancel,
      className,
      ...rest
    },
    ref
  ) => {
    const baseClassName = collapseWhitespace(
      composeClasses(baseClasses, isActive ? activeStateClasses : inactiveStateClasses, className)
    );
    const headerClassName = collapseWhitespace(composeClasses(headerClasses));
    const termsClassName = collapseWhitespace(composeClasses(termsClasses));
    const cancelSlotClassName = collapseWhitespace(composeClasses(cancelSlotClasses));
    const subtitleClassName = collapseWhitespace(composeClasses(subtitleClasses));
    const detailsClassName = collapseWhitespace(composeClasses(detailsClasses));
    const detailRowClassName = collapseWhitespace(composeClasses(detailRowClasses));
    const detailLabelClassName = collapseWhitespace(composeClasses(detailLabelClasses));
    const detailValueClassName = collapseWhitespace(composeClasses(detailValueClasses));

    const hasCancelSlot = Boolean(cancel);
    const hasCancelHref = typeof cancelHref === 'string' && cancelHref.length > 0;
    const shouldRenderCancelSlot = isActive && hasCancelSlot;
    const shouldRenderDefaultCancel = isActive && !hasCancelSlot && hasCancelHref;

    return (
      <div ref={ref} className={baseClassName} {...rest}>
        <div className={headerClassName}>
          <div className={termsClassName} data-slot="terms">
            {terms}
          </div>
          {shouldRenderCancelSlot ? (
            <div className={cancelSlotClassName} data-slot="cancel">
              {cancel}
            </div>
          ) : null}
          {shouldRenderDefaultCancel ? (
            <TextLink variant="subtle" href={cancelHref} label={cancelText} />
          ) : null}
        </div>

        {isActive ? (
          <div className={detailsClassName} data-slot="details">
            <div className={detailRowClassName} data-slot="detailRow">
              <span className={detailLabelClassName} data-slot="detailLabel">
                Next billing date:
              </span>
              <span className={detailValueClassName} data-slot="detailValue">
                {nextBillingDate}
              </span>
            </div>
            <div className={detailRowClassName} data-slot="detailRow">
              <span className={detailLabelClassName} data-slot="detailLabel">
                Member since:
              </span>
              <span className={detailValueClassName} data-slot="detailValue">
                {memberSince}
              </span>
            </div>
          </div>
        ) : (
          <p className={subtitleClassName} data-slot="subtitle">
            {inactiveSubtitle}
          </p>
        )}
      </div>
    );
  }
);

SubscriptionCard.displayName = 'SubscriptionCard';
