// packages/core/src/components/client/Slider/Slider.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Ensures Slider renders with aria labeling, reflects controlled value/domain props, fires handlers, and applies styleMap classes.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Slider, type SliderProps } from './Slider';

type ResizeObserverCallback = (entries: unknown[], observer: unknown) => void;

class ResizeObserverMock {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  constructor(_callback: ResizeObserverCallback) {}
  observe(): void {}
  unobserve(): void {}
  disconnect(): void {}
}

beforeAll(() => {
  if (typeof window !== 'undefined' && !('ResizeObserver' in window)) {
    (window as unknown as { ResizeObserver: typeof ResizeObserverMock }).ResizeObserver =
      ResizeObserverMock;
  }
});

const renderSlider = (overrides?: Partial<SliderProps>) => {
  const props: SliderProps = {
    value: 50,
    onChange: () => {},
    min: 0,
    max: 100,
    step: 1,
    ariaLabel: 'Slider',
    ...overrides
  };

  return render(<Slider {...props} />);
};

describe('Slider', () => {
  it('renders a slider role with the provided aria label', () => {
    renderSlider({ ariaLabel: 'Volume' });
    expect(screen.getByRole('slider', { name: 'Volume' })).toBeInTheDocument();
  });

  it('updates aria-valuenow when the value prop changes', () => {
    const { rerender } = renderSlider({ value: 40 });
    const before = screen.getByRole('slider', { name: 'Slider' }).getAttribute('aria-valuenow');
    rerender(
      <Slider value={60} onChange={() => {}} ariaLabel="Slider" min={0} max={100} step={1} />
    );
    const after = screen.getByRole('slider', { name: 'Slider' }).getAttribute('aria-valuenow');
    expect({ before, after }).toEqual({ before: '40', after: '60' });
  });

  it('exposes domain attributes reflecting min, max, and step', () => {
    renderSlider({ min: 10, max: 90, step: 5 });
    const slider = screen.getByRole('slider', { name: 'Slider' });
    const container = document.querySelector('[data-slot="container"]') as HTMLElement | null;
    expect({
      min: slider.getAttribute('aria-valuemin'),
      max: slider.getAttribute('aria-valuemax'),
      step: container?.getAttribute('data-step')
    }).toEqual({ min: '10', max: '90', step: '5' });
  });

  it('invokes onChange with the normalized value on keyboard interaction', async () => {
    const onChange = jest.fn();
    renderSlider({ value: 30, onChange, ariaLabel: 'Seek' });
    const slider = screen.getByRole('slider', { name: 'Seek' });
    slider.focus();
    const user = userEvent.setup();

    await user.keyboard('[ArrowRight]');

    expect(onChange).toHaveBeenCalledWith(31);
  });

  it('emits onCommit exactly once after a keyboard interaction completes', () => {
    const onCommit = jest.fn();
    renderSlider({ onCommit, ariaLabel: 'Commit' });
    const slider = screen.getByRole('slider', { name: 'Commit' });

    fireEvent.keyDown(slider, { key: 'ArrowRight' });
    fireEvent.keyUp(slider, { key: 'ArrowRight' });

    expect(onCommit).toHaveBeenCalledTimes(1);
  });

  it('applies styleMap classes to track, range, and thumb slots', () => {
    renderSlider();
    const track = document.querySelector('[data-slot="_track"]') as HTMLElement | null;
    const range = document.querySelector('[data-slot="_range"]') as HTMLElement | null;
    const thumb = document.querySelector('[data-slot="_thumb"]') as HTMLElement | null;
    expect({
      track: track?.className.includes('bg-color-background-subtle'),
      range: range?.className.includes('bg-color-background-brand'),
      thumb: thumb?.className.includes('size-[8px]')
    }).toEqual({ track: true, range: true, thumb: true });
  });
});
