'use client';

// packages/core/src/components/client/Slider/Slider.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Controlled single-thumb Radix slider with min/max/step domain props, normalized change/commit handlers, and aria labeling routed to the thumb.

import * as React from 'react';
import { Slider as RadixSlider } from 'radix-ui';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type SliderRootElement = React.ElementRef<typeof RadixSlider.Root>;

export interface SliderProps {
  value: number;
  onChange: (value: number) => void;
  onCommit?: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
  ariaLabel?: string;
  ariaLabelledBy?: string;
}

const baseClasses = `
  w-full select-none touch-none
`;

const containerClasses = `
  relative w-full h-[12px] flex items-center
`;

const trackClasses = `
  relative w-full h-[4px] rounded-full bg-color-background-subtle overflow-hidden
`;

const rangeClasses = `
  absolute left-0 top-0 h-full rounded-full bg-color-background-brand
`;

const thumbClasses = `
  block size-[8px] rounded-full bg-color-background-brand
  focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-4
  focus-visible:ring-comp-border-focus-ring focus-visible:ring-offset-color-background-default
`;

export const Slider = React.forwardRef<SliderRootElement, SliderProps>(
  ({ value, onChange, onCommit, min = 0, max = 100, step = 1, ariaLabel, ariaLabelledBy }, ref) => {
    const handleValueChange = React.useCallback(
      (nextValues: number[]) => {
        const nextValue = nextValues[0];
        if (typeof nextValue === 'number') {
          onChange(nextValue);
        }
      },
      [onChange]
    );

    const handleValueCommit = React.useCallback(
      (nextValues: number[]) => {
        if (!onCommit) return;
        const nextValue = nextValues[0];
        if (typeof nextValue === 'number') {
          onCommit(nextValue);
        }
      },
      [onCommit]
    );

    const rootClassName = collapseWhitespace(composeClasses(baseClasses, containerClasses));
    const trackClassName = collapseWhitespace(composeClasses(trackClasses));
    const rangeClassName = collapseWhitespace(composeClasses(rangeClasses));
    const thumbClassName = collapseWhitespace(composeClasses(thumbClasses));

    const thumbAriaProps =
      ariaLabel !== undefined
        ? { 'aria-label': ariaLabel }
        : ariaLabelledBy !== undefined
          ? { 'aria-labelledby': ariaLabelledBy }
          : {};

    return (
      <RadixSlider.Root
        ref={ref}
        value={[value]}
        min={min}
        max={max}
        step={step}
        onValueChange={handleValueChange}
        onValueCommit={onCommit ? handleValueCommit : undefined}
        className={rootClassName}
        data-slot="container"
        data-step={step}
      >
        <RadixSlider.Track className={trackClassName} data-slot="_track">
          <RadixSlider.Range className={rangeClassName} data-slot="_range" />
        </RadixSlider.Track>
        <RadixSlider.Thumb
          className={thumbClassName}
          data-slot="_thumb"
          aria-valuemin={min}
          aria-valuemax={max}
          {...thumbAriaProps}
        />
      </RadixSlider.Root>
    );
  }
);

Slider.displayName = 'Slider';
