// packages/core/src/components/client/Slider/Slider.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Storybook demo showing the controlled Slider with adjustable domain props and inline value preview.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react-vite';
import * as React from 'react';
import { fn } from 'storybook/test';
import Readme from './README.md?raw';
import { Slider, type SliderProps } from './Slider';

const meta: Meta<SliderProps> = {
  title: 'Client components/Slider',
  component: Slider,
  args: {
    value: 50,
    min: 0,
    max: 100,
    step: 1,
    ariaLabel: 'Slider',
    onChange: fn(),
    onCommit: fn()
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Single-thumb slider driven by provided `value`, demonstrating controlled usage with adjustable `min`, `max`, and `step` props plus inline value readout.'
      },
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<SliderProps>;

const SliderDemo: React.FC<SliderProps> = args => {
  const [currentValue, setCurrentValue] = React.useState(args.value);

  React.useEffect(() => {
    setCurrentValue(args.value);
  }, [args.value]);

  const handleChange = React.useCallback(
    (next: number) => {
      setCurrentValue(next);
      args.onChange(next);
    },
    [args]
  );

  const handleCommit = React.useCallback(
    (next: number) => {
      args.onCommit?.(next);
    },
    [args]
  );

  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: '12px', width: '320px' }}>
      <Slider {...args} value={currentValue} onChange={handleChange} onCommit={handleCommit} />
    </div>
  );
};

export const Default: Story = {
  render: args => <SliderDemo {...args} />
};
