// packages/core/src/icons/AddIcon/AddIcon.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: AddIcon renders an add glyph SVG supporting decorative or labeled usage with optional title and color props

import * as React from 'react';

export interface AddIconProps extends React.SVGAttributes<SVGSVGElement> {
  decorative?: boolean;
  title?: string;
  titleId?: string;
  color?: string;
}

type AddIconElement = SVGSVGElement;

export const AddIcon = React.forwardRef<AddIconElement, AddIconProps>(
  (
    {
      decorative = true,
      width = '20px',
      height = '20px',
      title,
      titleId: providedTitleId,
      color = 'currentColor',
      className,
      'aria-labelledby': ariaLabelledby,
      ...rest
    },
    ref
  ) => {
    const generatedTitleId = React.useId();
    const resolvedTitleId = title ? (providedTitleId ?? generatedTitleId) : undefined;

    const computedAriaHidden = decorative ? 'true' : undefined;
    const computedRole = decorative ? undefined : 'img';
    const computedAriaLabelledby =
      !decorative && title && resolvedTitleId ? resolvedTitleId : ariaLabelledby;

    return (
      <svg
        ref={ref}
        {...rest}
        className={className}
        viewBox="0 0 20 20"
        width={width}
        height={height}
        fill={color}
        aria-hidden={computedAriaHidden}
        role={computedRole}
        aria-labelledby={computedAriaLabelledby}
      >
        {!decorative && title ? <title id={resolvedTitleId}>{title}</title> : null}
        <g transform="scale(0.0208333333,0.0208333333) translate(0,960)">
          <path d="M438.5-438.5H231.87v-83H438.5v-206.63h83v206.63h206.63v83H521.5v206.63h-83V-438.5Z" />
        </g>
      </svg>
    );
  }
);

AddIcon.displayName = 'AddIcon';
