// packages/core/src/components/server/ImagePanel/ImagePanel.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: ImagePanel renders a hero-sized image with overlay and a fading content stack for carousel slides.

import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type ImagePanelLabel = {
  icon?: React.ReactNode;
  label: string;
  ariaLabel?: string;
};

type NativeDivProps = Omit<React.HTMLAttributes<HTMLDivElement>, 'title'>;

export interface ImagePanelProps extends NativeDivProps {
  imgSrc: string;
  imgAlt: string;
  loading?: 'lazy' | 'eager';
  fetchPriority?: 'high' | 'low';
  title?: string;
  description?: string;
  labels?: ReadonlyArray<ImagePanelLabel>;
  actions?: ReadonlyArray<React.ReactNode>;
}

const baseClasses = `
  relative isolate overflow-clip w-[390px] h-[390px] lg:w-[1040px] lg:h-[620px]
  transform-gpu transition-transform duration-token-md ease-token-standard scale-95
  group-data-[is-in-view=true]:scale-100
`;

const imageSlotClasses = `
  block size-full object-cover object-center
`;

const overlaySlotClasses = `
  pointer-events-none absolute inset-0 overlay-image-overlay-dark
`;

const contentSlotClasses = `
  absolute inset-0 flex flex-col gap-1 items-start p-token-md opacity-0 transition-opacity
  duration-token-md ease-token-standard group-data-[is-in-view=true]:opacity-1 motion-reduce:transition-none
`;

const titleSlotClasses = `
  text-2xl text-color-content-default
`;

const descriptionSlotClasses = `
  text-base text-color-content-weak
`;

const labelsSlotClasses = `
  text-sm text-color-content-weak flex
`;

const actionsSlotClasses = `
  flex gap-2 items-center
`;

export const ImagePanel = React.forwardRef<HTMLDivElement, ImagePanelProps>(
  (
    {
      imgSrc,
      imgAlt,
      loading = 'lazy',
      fetchPriority,
      title,
      description,
      labels = [],
      actions = [],
      className,
      ...rest
    },
    ref
  ) => {
    const labelsList: ReadonlyArray<ImagePanelLabel> = Array.isArray(labels) ? labels : [];
    const actionsList: ReadonlyArray<React.ReactNode> = Array.isArray(actions) ? actions : [];

    const baseClassName = collapseWhitespace(composeClasses(baseClasses, className));
    const imageSlotClassName = collapseWhitespace(composeClasses(imageSlotClasses));
    const overlaySlotClassName = collapseWhitespace(composeClasses(overlaySlotClasses));
    const contentSlotClassName = collapseWhitespace(composeClasses(contentSlotClasses));
    const titleSlotClassName = collapseWhitespace(composeClasses(titleSlotClasses));
    const descriptionSlotClassName = collapseWhitespace(composeClasses(descriptionSlotClasses));
    const labelsSlotClassName = collapseWhitespace(composeClasses(labelsSlotClasses));
    const actionsSlotClassName = collapseWhitespace(composeClasses(actionsSlotClasses));

    return (
      <div {...rest} ref={ref} className={baseClassName} data-slot="base">
        <img
          className={imageSlotClassName}
          data-slot="_image"
          src={imgSrc}
          alt={imgAlt}
          loading={loading}
          {...(typeof fetchPriority === 'string' ? { fetchpriority: fetchPriority } : {})}
        />
        <div className={overlaySlotClassName} data-slot="_overlay" />
        <div className={contentSlotClassName} data-slot="_content">
          <div className={actionsSlotClassName} data-slot="_actions">
            {actionsList.map((action, index) => (
              <React.Fragment key={index}>{action}</React.Fragment>
            ))}
          </div>
          {title ? (
            <h3 className={titleSlotClassName} data-slot="_title">
              {title}
            </h3>
          ) : null}
          {description ? (
            <p className={descriptionSlotClassName} data-slot="_description">
              {description}
            </p>
          ) : null}
          <div className={labelsSlotClassName} data-slot="_labels">
            {labelsList.map(({ icon, label, ariaLabel }, index) => {
              const labelKey = `${label}-${index}`;
              const accessibleLabel =
                typeof ariaLabel === 'string' && ariaLabel.trim().length > 0 ? ariaLabel : undefined;
              return (
                <span key={labelKey} data-slot="_labelItem" aria-label={accessibleLabel}>
                  {icon ? (
                    <span aria-hidden="true" data-slot="_labelIcon">
                      {icon}
                    </span>
                  ) : null}
                  <span>{label}</span>
                </span>
              );
            })}
          </div>
        </div>
      </div>
    );
  }
);

ImagePanel.displayName = 'ImagePanel';
