import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import type { RenderResult } from '@testing-library/react';
import { IconButton } from './IconButton';
import type { IconButtonProps } from './IconButton';

type Variant = NonNullable<IconButtonProps['variant']>;

describe('IconButton', () => {
  const sampleIcon = <span data-testid="icon-slot">★</span>;

  it('throws when ariaLabel is empty or whitespace', () => {
    expect(() =>
      render(<IconButton icon={sampleIcon} ariaLabel="   " />)
    ).toThrowError('IconButton requires a non-empty ariaLabel.');
  });

  it('throws when children are provided', () => {
    expect(() =>
      render(
        <IconButton icon={sampleIcon} ariaLabel="Invalid child usage">
          <span />
        </IconButton>
      )
    ).toThrowError('IconButton does not accept children; pass the icon via the `icon` prop.');
  });

  it('renders the icon slot inside a button by default', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Open menu" />
    );
    const button = screen.getByRole('button', { name: 'Open menu' });
    expect(button).toBeInTheDocument();
    expect(screen.getByTestId('icon-slot')).toBeInTheDocument();
    view.unmount();
  });

  describe('variant classes', () => {
    const cases: ReadonlyArray<[Variant, string]> = [
      ['primary', 'bg-comp-icon-button-primary-color-background-default'],
      ['secondary', 'bg-comp-icon-button-secondary-color-background-default'],
      ['bare', 'text-comp-icon-button-bare-color-foreground-default'],
      ['knockout', 'border-comp-icon-button-knockout-color-border-default'],
      ['bareKnockout', 'border-comp-icon-button-bare-knockout-color-border-default']
    ] as const;

    it.each(cases)('applies %s variant class', (variant, token) => {
      const view: RenderResult = render(
        <IconButton icon={sampleIcon} ariaLabel="Toggle setting" variant={variant} />
      );
      const button = screen.getByRole('button', { name: 'Toggle setting' });
      expect(button).toHaveClass(token);
      view.unmount();
    });
  });

  it('applies focus ring token class on the root', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Focus test" />
    );
    const button = screen.getByRole('button', { name: 'Focus test' });
    expect(button.className).toMatch(/focus-visible:ring-comp-icon-button-focus-color-ring/);
    view.unmount();
  });

  it('applies square sizing classes from the style map', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Square check" />
    );
    const button = screen.getByRole('button', { name: 'Square check' });
    expect(button).toHaveClass('h-10');
    expect(button).toHaveClass('w-10');
    expect(button).toHaveClass('rounded-md');
    view.unmount();
  });

  it('normalizes the aria-label by trimming whitespace', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="  Settings  " />
    );
    expect(screen.getByRole('button', { name: 'Settings' })).toBeInTheDocument();
    view.unmount();
  });

  it('sets type="button" by default', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Default type" />
    );
    const button = screen.getByRole('button', { name: 'Default type' });
    expect(button).toHaveAttribute('type', 'button');
    view.unmount();
  });

  it('respects an explicit type', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Submit action" type="submit" />
    );
    const button = screen.getByRole('button', { name: 'Submit action' });
    expect(button).toHaveAttribute('type', 'submit');
    view.unmount();
  });

  it('marks the control disabled when disabled prop is true', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Disabled" disabled />
    );
    const button = screen.getByRole('button', { name: 'Disabled' });
    expect(button).toHaveAttribute('aria-disabled', 'true');
    expect(button).toBeDisabled();
    view.unmount();
  });

  it('marks the control busy and disabled when loading', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Loading" loading />
    );
    const button = screen.getByRole('button', { name: 'Loading' });
    expect(button).toHaveAttribute('aria-busy', 'true');
    expect(button).toHaveAttribute('aria-disabled', 'true');
    expect(button).toHaveAttribute('data-loading', 'true');
    expect(button).toHaveClass('cursor-wait');
    expect(button).toBeDisabled();
    view.unmount();
  });

  it('wraps the icon with an aria-hidden container', () => {
    const view: RenderResult = render(
      <IconButton icon={sampleIcon} ariaLabel="Icon slot" />
    );
    const button = screen.getByRole('button', { name: 'Icon slot' });
    const iconWrapper = button.querySelector('span[aria-hidden="true"]');
    expect(iconWrapper).not.toBeNull();
    expect(iconWrapper).toHaveClass('shrink-0');
    view.unmount();
  });

});
