import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import { IconButton } from './IconButton';
import type { IconButtonProps } from './IconButton';

type Variant = NonNullable<IconButtonProps['variant']>;

describe('IconButton', () => {
  const sampleIcon = <span data-testid="icon-slot">★</span>;

  describe('a11y', () => {
    it('throws when ariaLabel is empty or whitespace', () => {
      expect(() => {
        render(<IconButton icon={sampleIcon} ariaLabel="   " />);
      }).toThrow('IconButton requires a non-empty ariaLabel.');
    });

    it('normalizes the aria-label by trimming whitespace', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="  Settings  " />);
      expect(screen.getByRole('button', { name: 'Settings' })).toBeInTheDocument();
    });
  });

  describe('structure', () => {
    it('renders a button element', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Open menu" />);
      expect(screen.getByRole('button', { name: 'Open menu' })).toBeInTheDocument();
    });

    it('renders the icon slot', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Open menu" />);
      expect(screen.getByTestId('icon-slot')).toBeInTheDocument();
    });

    it('wraps the icon with an aria-hidden container', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Icon slot" />);
      const iconWrapper = screen
        .getByRole('button', { name: 'Icon slot' })
        .querySelector('span[aria-hidden="true"]');
      expect(iconWrapper).not.toBeNull();
    });

    it('applies focus ring token class on the root', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Focus test" />);
      const button = screen.getByRole('button', { name: 'Focus test' });
      expect(button.className).toMatch(/focus-visible:ring-comp-icon-button-focus-color-ring/);
    });
  });

  describe('square sizing', () => {
    const sizeCases = ['h-32', 'w-32', 'rounded-md'] as const;
    it.each(sizeCases)('applies %s', cls => {
      render(<IconButton icon={sampleIcon} ariaLabel="Square check" />);
      const button = screen.getByRole('button', { name: 'Square check' });
      expect(button).toHaveClass(cls);
    });
  });

  describe('variants', () => {
    const cases: ReadonlyArray<[Variant, string]> = [
      ['primary', 'bg-comp-button-primary-color-background-default'],
      ['secondary', 'border-comp-button-color-border-default'],
      ['bare', 'bg-background-none'],
      ['knockout', 'bg-comp-button-color-background-knockout'],
      ['bareKnockout', 'text-comp-button-primary-color-content-default']
    ] as const;

    it.each(cases)('applies %s variant class', (variant, token) => {
      render(<IconButton icon={sampleIcon} ariaLabel="Toggle setting" variant={variant} />);
      const button = screen.getByRole('button', { name: 'Toggle setting' });
      expect(button).toHaveClass(token);
    });
  });

  describe('type attribute', () => {
    it('sets type="button" by default', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Default type" />);
      const button = screen.getByRole('button', { name: 'Default type' });
      expect(button).toHaveAttribute('type', 'button');
    });

    it('respects an explicit type', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Submit action" type="submit" />);
      const button = screen.getByRole('button', { name: 'Submit action' });
      expect(button).toHaveAttribute('type', 'submit');
    });
  });

  describe('disabled state', () => {
    it('sets aria-disabled when disabled', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Disabled" disabled />);
      const button = screen.getByRole('button', { name: 'Disabled' });
      expect(button).toHaveAttribute('aria-disabled', 'true');
    });

    it('sets the native disabled attribute when disabled', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Disabled" disabled />);
      const button = screen.getByRole('button', { name: 'Disabled' });
      expect(button).toBeDisabled();
    });
  });

  describe('loading state', () => {
    it('sets aria-busy when loading', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Loading" loading />);
      const button = screen.getByRole('button', { name: 'Loading' });
      expect(button).toHaveAttribute('aria-busy', 'true');
    });

    it('sets aria-disabled when loading', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Loading" loading />);
      const button = screen.getByRole('button', { name: 'Loading' });
      expect(button).toHaveAttribute('aria-disabled', 'true');
    });

    it('sets data-loading when loading', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Loading" loading />);
      const button = screen.getByRole('button', { name: 'Loading' });
      expect(button).toHaveAttribute('data-loading', 'true');
    });

    it('applies cursor-wait when loading', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Loading" loading />);
      const button = screen.getByRole('button', { name: 'Loading' });
      expect(button).toHaveClass('cursor-wait');
    });

    it('disables the button when loading', () => {
      render(<IconButton icon={sampleIcon} ariaLabel="Loading" loading />);
      const button = screen.getByRole('button', { name: 'Loading' });
      expect(button).toBeDisabled();
    });
  });
});
