// packages/core/src/components/client/MediaPlayer/MediaPlayer.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook stories for MediaPlayer covering default, compact, and mini layouts with sample audio sources.

import type { Meta, StoryObj } from '@storybook/react';
import { MediaPlayer, type MediaPlayerProps } from './MediaPlayer';

const meta: Meta<MediaPlayerProps> = {
  title: 'Client components/MediaPlayer',
  component: MediaPlayer,
  args: {
    audioSrc: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
    title: 'Inspiration Loop',
    subtitle: 'Episode 3 — Momentum',
    preload: 'metadata'
  }
};

export default meta;

type Story = StoryObj<MediaPlayerProps>;

export const Default: Story = {
  args: {
    variant: 'default',
    autoPlay: false,
    loop: false
  }
};

export const Compact: Story = {
  args: {
    variant: 'compact',
    autoPlay: false,
    loop: false,
    startTime: 30
  }
};

export const Mini: Story = {
  args: {
    variant: 'mini',
    autoPlay: false
  }
};
