// packages/core/src/components/client/MediaPlayer/MediaPlayer.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Verifies MediaPlayer layout, audio time syncing, seek commits, MediaControl integration, and volume slider behavior.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MediaPlayer, type MediaPlayerProps } from './MediaPlayer';

type MockSliderProps = {
  value: number;
  onChange: (v: number) => void;
  onCommit?: (v: number) => void;
  ariaLabel?: string;
};

/**
 * NOTE: MediaPlayer tests only verify integration with Slider:
 * - Seek: onChange/onCommit update audio.currentTime and visible time label
 * - Volume: onChange maps to audio.volume
 * We do NOT test Slider behavior/semantics/aria here; those belong to Slider tests.
 */
jest.mock('../Slider', () => ({
  Slider: ({ value, onChange, onCommit, ariaLabel }: MockSliderProps) => (
    <input
      type="range"
      role="slider"
      aria-label={ariaLabel}
      data-testid={`${ariaLabel}-slider`}
      value={value}
      onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
        onChange(Number(event.target.value))
      }
      onMouseUp={(event: React.MouseEvent<HTMLInputElement>) =>
        onCommit?.(Number((event.target as HTMLInputElement).value))
      }
    />
  )
}));

const playMock = jest.fn().mockResolvedValue(undefined);
const pauseMock = jest.fn();

beforeAll(() => {
  Object.defineProperty(window.HTMLMediaElement.prototype, 'play', {
    configurable: true,
    value: playMock
  });
  Object.defineProperty(window.HTMLMediaElement.prototype, 'pause', {
    configurable: true,
    value: pauseMock
  });
});

afterEach(() => {
  jest.clearAllMocks();
});

const primeMediaElement = (
  audio: HTMLAudioElement,
  overrides?: { duration?: number; currentTime?: number; volume?: number }
) => {
  let currentTimeValue = overrides?.currentTime ?? 0;
  let durationValue = overrides?.duration ?? 0;
  let volumeValue = overrides?.volume ?? 1;

  Object.defineProperty(audio, 'currentTime', {
    configurable: true,
    get: () => currentTimeValue,
    set: value => {
      currentTimeValue = value;
    }
  });

  Object.defineProperty(audio, 'duration', {
    configurable: true,
    get: () => durationValue,
    set: value => {
      durationValue = value;
    }
  });

  Object.defineProperty(audio, 'volume', {
    configurable: true,
    get: () => volumeValue,
    set: value => {
      volumeValue = value;
    }
  });
};

const dispatchAudioEvent = (audio: HTMLAudioElement, type: string) => {
  act(() => {
    audio.dispatchEvent(new Event(type));
  });
};

const renderMediaPlayer = (props?: Partial<MediaPlayerProps>) => {
  const defaultProps: MediaPlayerProps = {
    audioSrc: '/audio/sample.mp3',
    title: 'Sample Track',
    subtitle: 'Sample Artist',
    ...props
  };

  return render(<MediaPlayer {...defaultProps} />);
};

describe('MediaPlayer', () => {
  it('renders the title', () => {
    renderMediaPlayer();
    expect(screen.getByText('Sample Track')).toBeInTheDocument();
  });

  it('renders the subtitle', () => {
    renderMediaPlayer();
    expect(screen.getByText('Sample Artist')).toBeInTheDocument();
  });

  it('default: renders two sliders (seek and volume)', () => {
    renderMediaPlayer({ variant: 'default' });
    const sliders = screen.getAllByRole('slider');
    expect(sliders.length).toBe(2);
  });

  it('updates the time display after audio metadata and timeupdate events', async () => {
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 120, currentTime: 0 });
    dispatchAudioEvent(audio, 'loadedmetadata');
    audio.currentTime = 42;
    dispatchAudioEvent(audio, 'timeupdate');

    await waitFor(() => {
      expect(screen.getByText('00:42 / 02:00')).toBeInTheDocument();
    });
  });

  it('commits seek changes back to the audio element', async () => {
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 180, currentTime: 0 });
    dispatchAudioEvent(audio, 'loadedmetadata');
    const seekSlider = screen.getByTestId('Seek-slider') as HTMLInputElement;

    fireEvent.change(seekSlider, { target: { value: '60' } });
    fireEvent.mouseUp(seekSlider);

    await waitFor(() => {
      expect(audio.currentTime).toBe(60);
    });
  });

  it('updates the time label after a committed seek', async () => {
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 180, currentTime: 0 });
    dispatchAudioEvent(audio, 'loadedmetadata');
    const seekSlider = screen.getByTestId('Seek-slider') as HTMLInputElement;
    fireEvent.change(seekSlider, { target: { value: '60' } });
    fireEvent.mouseUp(seekSlider);
    await waitFor(() => {
      expect(screen.getByText('01:00 / 03:00')).toBeInTheDocument();
    });
  });

  it('plays on first click of the control button', async () => {
    const user = userEvent.setup();
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 90 });
    dispatchAudioEvent(audio, 'loadedmetadata');

    const controlBtn = screen.getByRole('button');
    await user.click(controlBtn);
    expect(playMock).toHaveBeenCalledTimes(1);
  });

  it('pauses on second click of the control button', async () => {
    const user = userEvent.setup();
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 90 });
    dispatchAudioEvent(audio, 'loadedmetadata');

    const controlBtn = screen.getByRole('button');
    await user.click(controlBtn);
    dispatchAudioEvent(audio, 'play');
    await user.click(controlBtn);
    expect(pauseMock).toHaveBeenCalledTimes(1);
  });

  it('maps volume slider changes to the audio element volume', () => {
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 60, volume: 1 });
    dispatchAudioEvent(audio, 'loadedmetadata');

    const volumeSlider = screen.getByTestId('Volume-slider') as HTMLInputElement;
    fireEvent.change(volumeSlider, { target: { value: '35' } });

    expect(audio.volume).toBeCloseTo(0.35);
  });

  it('seeks to the provided startTime once metadata loads', () => {
    renderMediaPlayer({ startTime: 15 });
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 120, currentTime: 0 });

    dispatchAudioEvent(audio, 'loadedmetadata');

    expect(audio.currentTime).toBe(15);
  });

  it('updates the duration label after durationchange events', async () => {
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 60, currentTime: 0 });
    dispatchAudioEvent(audio, 'loadedmetadata');

    (audio as unknown as { duration: number }).duration = 245;
    dispatchAudioEvent(audio, 'durationchange');

    await waitFor(() => {
      expect(screen.getByText('00:00 / 04:05')).toBeInTheDocument();
    });
  });

  it('syncs the slider value when the audio element fires volumechange', () => {
    renderMediaPlayer();
    const audio = document.querySelector('audio') as HTMLAudioElement;
    primeMediaElement(audio, { duration: 60, volume: 1 });
    dispatchAudioEvent(audio, 'loadedmetadata');

    audio.volume = 0.45;
    dispatchAudioEvent(audio, 'volumechange');

    const volumeSlider = screen.getByTestId('Volume-slider') as HTMLInputElement;
    expect(volumeSlider.value).toBe('45');
  });


  it('compact: hides the volume slider', () => {
    renderMediaPlayer({ variant: 'compact' });
    expect(screen.queryByTestId('Volume-slider')).toBeNull();
  });

  it('compact: does not render the time display', () => {
    renderMediaPlayer({ variant: 'compact' });
    expect(screen.queryByText(/\/\s*\d{2}:\d{2}$/)).toBeNull();
  });

  it('mini: hides the seek slider', () => {
    renderMediaPlayer({ variant: 'mini' });
    expect(screen.queryByTestId('Seek-slider')).toBeNull();
  });

  it('mini: hides the volume slider', () => {
    renderMediaPlayer({ variant: 'mini' });
    expect(screen.queryByTestId('Volume-slider')).toBeNull();
  });

});
