// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { fn } from 'storybook/test';
import { MediaControl, type MediaControlProps } from './MediaControl';

const meta: Meta<MediaControlProps> = {
  title: 'Components/MediaControl',
  component: MediaControl,
  args: {
    variant: 'light',
    size: 'lg',
    onStateChange: fn(),
    onPlay: fn(),
    onPause: fn()
  }
};

export default meta;

type Story = StoryObj<MediaControlProps>;

const MediaControlDemo: React.FC<MediaControlProps> = args => {
  const [state, setState] = React.useState<MediaControlProps['state']>('paused');
  const controlRef = React.useRef<HTMLButtonElement>(null);

  const handleStateChange = React.useCallback((next: NonNullable<MediaControlProps['state']>) => {
    setState(next);
  }, []);

  return (
    <MediaControl {...args} ref={controlRef} state={state} onStateChange={handleStateChange} />
  );
};

export const Default: Story = {
  render: args => <MediaControlDemo {...args} />
};
