import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MediaControl, type MediaControlProps } from './MediaControl';

const playPathD = 'M327.87-201.41v-557.18L759.07-480l-431.2 278.59Z';
const pausePathD = 'M560.17-213.41v-533.18h190v533.18h-190Zm-350.34 0v-533.18h190v533.18h-190Z';
const playingTintClass = '[&_[data-slot="_icon"]]:text-color-content-brand';

const renderMediaControl = (props?: Partial<MediaControlProps>) => render(<MediaControl {...props} />);

describe('MediaControl', () => {
  it('renders a button with the icon slot', () => {
    renderMediaControl();
    const icon = document.querySelector('[data-slot="_icon"]');
    expect(icon).not.toBeNull();
  });

  it('applies the paused aria label by default', () => {
    renderMediaControl();
    const button = screen.getByRole('button');
    expect(button).toHaveAttribute('aria-label', 'Play media');
  });

  it('renders the PlayIcon path when paused', () => {
    renderMediaControl();
    const path = document.querySelector('[data-slot="_icon"] path');
    expect(path?.getAttribute('d')).toBe(playPathD);
  });

  it('switches to the PauseIcon after clicking once', async () => {
    const user = userEvent.setup();
    renderMediaControl();
    const button = screen.getByRole('button');

    await user.click(button);

    const path = document.querySelector('[data-slot="_icon"] path');
    expect(path?.getAttribute('d')).toBe(pausePathD);
  });

  it('updates the aria label when the control enters playing state', async () => {
    const user = userEvent.setup();
    renderMediaControl();
    const button = screen.getByRole('button');

    await user.click(button);

    expect(button).toHaveAttribute('aria-label', 'Pause media');
  });

  it('emits callbacks in order for playing then paused transitions', async () => {
    const calls: string[] = [];
    const user = userEvent.setup();
    renderMediaControl({
      onStateChange: next => {
        calls.push(`state:${next}`);
      },
      onPlay: () => {
        calls.push('play');
      },
      onPause: () => {
        calls.push('pause');
      }
    });
    const button = screen.getByRole('button');

    await user.click(button);
    await user.click(button);

    expect(calls).toEqual(['state:playing', 'play', 'state:paused', 'pause']);
  });

  it('does not toggle visuals when controlled without external state change', async () => {
    const user = userEvent.setup();
    renderMediaControl({ state: 'paused', onStateChange: () => {} });
    const button = screen.getByRole('button');

    await user.click(button);

    const path = document.querySelector('[data-slot="_icon"] path');
    expect(path?.getAttribute('d')).toBe(playPathD);
  });

  it('reflects controlled prop updates', () => {
    const { rerender } = renderMediaControl({ state: 'paused', onStateChange: () => {} });
    rerender(<MediaControl state="playing" onStateChange={() => {}} />);
    const path = document.querySelector('[data-slot="_icon"] path');
    expect(path?.getAttribute('d')).toBe(pausePathD);
  });

  it('uses caller-provided labels when supplied', () => {
    renderMediaControl({ ariaLabelPlay: 'Resume audio' });
    const button = screen.getByRole('button');
    expect(button).toHaveAttribute('aria-label', 'Resume audio');
  });

  it('forwards variant and size to Control', () => {
    renderMediaControl({ variant: 'brand', size: 'sm' });
    const button = screen.getByRole('button');
    const satisfiesForwarding =
      button.classList.contains('bg-comp-button-primary-color-background-default') &&
      button.classList.contains('h-32');
    expect(satisfiesForwarding).toBe(true);
  });

  it('adds the playing tint class when state is playing', () => {
    renderMediaControl({ state: 'playing' });
    const button = screen.getByRole('button');
    expect(button.className.includes(playingTintClass)).toBe(true);
  });

  it('omits the playing tint class when paused', () => {
    renderMediaControl();
    const button = screen.getByRole('button');
    expect(button.className.includes(playingTintClass)).toBe(false);
  });

  it('shows the focus-visible ring after keyboard focus', async () => {
    const user = userEvent.setup();
    renderMediaControl();

    await user.tab();

    const button = screen.getByRole('button');
    const focusState = {
      isFocused: document.activeElement === button,
      hasFocusClass: button.className.includes('focus-visible:ring-comp-border-focus-ring')
    };
    expect(focusState).toEqual({ isFocused: true, hasFocusClass: true });
  });
});

