// packages/core/src/components/server/Breadcrumbs/Breadcrumbs.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Verifies Breadcrumbs navigation landmark labeling, link and separator counts, collapsed ellipsis behavior, and decorative aria-hidden separators.

import '@testing-library/jest-dom';
import { render, screen } from '@testing-library/react';
import { Breadcrumbs, BreadcrumbsProps } from './Breadcrumbs';

describe('Breadcrumbs', () => {
  const makeItems = (count: number): BreadcrumbsProps['items'] =>
    Array.from({ length: count }, (_, index) => ({
      label: `Crumb ${index + 1}`,
      href: `/crumb-${index + 1}`
    }));

  const renderComponent = (override?: Partial<BreadcrumbsProps>) =>
    render(
      <Breadcrumbs
        items={makeItems(3)}
        current="Current Page"
        {...override}
      />
    );

  it('renders navigation landmark', () => {
    renderComponent({ items: makeItems(1), current: 'Home' });
    const navigation = screen.getByRole('navigation', { name: 'Breadcrumbs' });
    expect(navigation).toBeInTheDocument();
  });

  it('respects a custom aria-label on the nav landmark', () => {
    render(<Breadcrumbs items={[{ label: 'Home', href: '/' }]} current="Current" ariaLabel="Trail" />);
    expect(screen.getByRole('navigation', { name: 'Trail' })).toBeInTheDocument();
  });

  it('composes user-provided className on the root nav', () => {
    render(<Breadcrumbs items={[{ label: 'Home', href: '/' }]} current="Current" className="p-4" />);
    const nav = screen.getByRole('navigation', { name: 'Breadcrumbs' });
    expect(nav).toHaveClass('p-4');
  });

  it('renders non-final crumbs as links with their labels and hrefs', () => {
    renderComponent({ items: makeItems(3) });
    const linkCount = screen.getAllByRole('link').length;
    expect(linkCount).toBe(3);
  });

  describe('collapse behavior', () => {
    it('renders zero item slots when items.length=0', () => {
      renderComponent({ items: makeItems(0) });
      const itemCount = document.querySelectorAll('[data-slot="item"]').length;
      expect(itemCount).toBe(0);
    });

    it('renders one separator when items.length=2', () => {
      renderComponent({ items: makeItems(2) });
      const separatorCount = document.querySelectorAll('[data-slot="separator"]').length;
      expect(separatorCount).toBe(2);
    });

    it('renders three separators when items.length=4', () => {
      renderComponent({ items: makeItems(4) });
      const separatorCount = document.querySelectorAll('[data-slot="separator"]').length;
      expect(separatorCount).toBe(4);
    });

    it('renders ellipsis when items.length=5', () => {
      renderComponent({ items: makeItems(5) });
      const hasEllipsis = Boolean(document.querySelector('[data-slot="ellipsis"]'));
      expect(hasEllipsis).toBe(true);
    });

    it('renders a single item slot when items.length=6', () => {
      renderComponent({ items: makeItems(6) });
      const itemCount = document.querySelectorAll('[data-slot="item"]').length;
      expect(itemCount).toBe(1);
    });
  });

  it('marks the current crumb and keeps separators/ellipsis decorative', () => {
    renderComponent({ items: makeItems(5), current: 'Overview' });
    const navigation = screen.getByRole('navigation', { name: 'Breadcrumbs' });
    const currentCrumb = screen.getByText('Overview');
    const decorativeOnly = Array.from(
      navigation.querySelectorAll('[data-slot="separator"], [data-slot="ellipsis"]')
    ).every(element => element.getAttribute('aria-hidden') === 'true');
    expect({ ariaCurrent: currentCrumb.getAttribute('aria-current'), decorativeOnly }).toEqual({
      ariaCurrent: 'page',
      decorativeOnly: true
    });
  });

  it('sets aria-current on the current crumb', () => {
    renderComponent({ items: makeItems(2), current: 'Reports' });
    const currentCrumb = screen.getByText('Reports');
    expect(currentCrumb).toHaveAttribute('aria-current', 'page');
  });

  it('marks separators as decorative', () => {
    renderComponent({ items: makeItems(5), current: 'Overview' });
    const separator = document.querySelector('[data-slot="separator"]');
    expect(separator).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders collapsed sequence in order: item → separator → ellipsis → separator → current', () => {
    render(
      <Breadcrumbs
        items={[
          { label: 'A', href: '/a' },
          { label: 'B', href: '/b' },
          { label: 'C', href: '/c' },
          { label: 'D', href: '/d' },
          { label: 'E', href: '/e' }
        ]}
        current="Now"
      />
    );
    const list = document.querySelector('[data-slot="list"]');
    const slots = Array.from(list!.children).map(element => element.getAttribute('data-slot'));
    expect(slots).toEqual(['item', 'separator', 'ellipsis', 'separator', 'current']);
  });

  it('renders the first crumb as a link with correct href in collapsed mode', () => {
    render(
      <Breadcrumbs
        items={[
          { label: 'A', href: '/a' },
          { label: 'B', href: '/b' },
          { label: 'C', href: '/c' },
          { label: 'D', href: '/d' },
          { label: 'E', href: '/e' }
        ]}
        current="Now"
      />
    );
    const link = screen.getByRole('link', { name: 'A' });
    expect(link).toHaveAttribute('href', '/a');
  });

  it('renders exactly two separators in collapsed mode', () => {
    render(
      <Breadcrumbs
        items={[
          { label: 'A', href: '/a' },
          { label: 'B', href: '/b' },
          { label: 'C', href: '/c' },
          { label: 'D', href: '/d' },
          { label: 'E', href: '/e' }
        ]}
        current="Now"
      />
    );
    const count = document.querySelectorAll('[data-slot="separator"]').length;
    expect(count).toBe(2);
  });

  it('marks the ellipsis as decorative in collapsed mode', () => {
    render(
      <Breadcrumbs
        items={[
          { label: 'A', href: '/a' },
          { label: 'B', href: '/b' },
          { label: 'C', href: '/c' },
          { label: 'D', href: '/d' },
          { label: 'E', href: '/e' }
        ]}
        current="Now"
      />
    );
    const ellipsis = document.querySelector('[data-slot="ellipsis"]');
    expect(ellipsis).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders expanded sequence in order: item → separator (×3) → current', () => {
    render(
      <Breadcrumbs
        items={[
          { label: 'A', href: '/a' },
          { label: 'B', href: '/b' },
          { label: 'C', href: '/c' }
        ]}
        current="Now"
      />
    );
    const list = document.querySelector('[data-slot="list"]');
    const slots = Array.from(list!.children).map(element => element.getAttribute('data-slot'));
    expect(slots).toEqual(['item', 'separator', 'item', 'separator', 'item', 'separator', 'current']);
  });

  it('renders the first crumb as a link with correct href in expanded mode', () => {
    render(
      <Breadcrumbs
        items={[
          { label: 'Alpha', href: '/alpha' },
          { label: 'Beta', href: '/beta' },
          { label: 'Gamma', href: '/gamma' }
        ]}
        current="Now"
      />
    );
    const link = screen.getByRole('link', { name: 'Alpha' });
    expect(link).toHaveAttribute('href', '/alpha');
  });

  it('renders one link and one separator before current in expanded mode (items.length=1)', () => {
    render(<Breadcrumbs items={[{ label: 'Only', href: '/only' }]} current="Now" />);
    const count = document.querySelectorAll('[data-slot="separator"]').length;
    expect(count).toBe(1);
  });
});
