// packages/core/src/components/client/IconButton/IconButton.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories for IconButton highlighting variant styles, loading and disabled states, and sample Radix icons with aria-label controls.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react-vite';
import * as React from 'react';
import { InfoCircledIcon } from '@radix-ui/react-icons';
import Readme from './README.md?raw';
import { IconButton, IconButtonProps } from './IconButton';

const meta: Meta<IconButtonProps> = {
  title: 'Client components/IconButton',
  component: IconButton,
  args: {
    icon: <InfoCircledIcon />,
    ariaLabel: 'Open settings',
    variant: 'primary',
    loading: false,
    disabled: false,
    type: 'button'
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<IconButtonProps>;

export const Primary: Story = {};

export const Secondary: Story = {
  args: {
    variant: 'secondary'
  }
};

export const Bare: Story = {
  args: {
    variant: 'bare'
  }
};

export const Knockout: Story = {
  args: {
    variant: 'knockout'
  }
};

export const BareKnockout: Story = {
  args: {
    variant: 'bareKnockout'
  }
};
