'use client';

// packages/core/src/components/client/Scroller/Scroller.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Horizontal scroller with hidden-scroll viewport, optional controls, stackable rail, and scroll metrics callbacks.

import * as React from 'react';
import { Control } from '../Control';
import { ArrowForwardIcon, ArrowBackIcon } from '../../../icons';
import { composeClasses } from '../../../utilities/composeClasses/composeClasses';
import { collapseWhitespace } from '../../../utilities/collapseWhitespace/collapseWhitespace';

type PageBy = 'viewport' | 'fixed';

type ScrollMetrics = {
  left: number;
  width: number;
  viewport: number;
  atStart: boolean;
  atEnd: boolean;
};

const EDGE_EPSILON = 2;
const SCROLL_END_DELAY = 120;

const baseClasses = `
  relative block w-full
`;

const viewportClasses = `
  overflow-x-auto overscroll-x-contain touch-pan-x [scrollbar-gutter:stable]
  [-ms-overflow-style:none] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden
`;

const railClasses = `
  flex items-stretch min-w-0 w-max data-[stack-rows=true]:flex-col
`;

const controlsClasses = `
  mt-3 flex gap-2 justify-end
`;

const prevWrapperClasses = `
  shrink-0
`;

const nextWrapperClasses = `
  shrink-0
`;

const stateClasses = {
  isScrolling: '[--scroller-scrolling:1]',
  isAtStart: '[--scroller-edge-start:1]',
  isAtEnd: '[--scroller-edge-end:1]',
  hasControls: '[--has-controls:1]'
} as const;

export interface ScrollerProps
  extends Omit<
    React.HTMLAttributes<HTMLDivElement>,
    'role' | 'aria-label' | 'aria-labelledby' | 'children'
  > {
  showControls?: boolean;
  stackRows?: boolean;
  pageBy?: PageBy;
  pageSize?: number;
  onScrollChange?: (metrics: ScrollMetrics) => void;
  children: React.ReactNode;
}

export const Scroller = React.forwardRef<HTMLDivElement, ScrollerProps>(
  (
    {
      showControls = true,
      stackRows = false,
      pageBy = 'viewport',
      pageSize = 320,
      onScrollChange,
      children,
      className,
      onScroll,
      onWheel,
      ...rest
    },
    forwardedRef
  ) => {
    const baseRef = React.useRef<HTMLDivElement | null>(null);
    const viewportRef = React.useRef<HTMLDivElement | null>(null);
    const railRef = React.useRef<HTMLDivElement | null>(null);
    const scrollEndTimerRef = React.useRef<ReturnType<typeof setTimeout> | null>(null);
    const metricsRef = React.useRef<ScrollMetrics | null>(null);

    const [isScrolling, setIsScrolling] = React.useState(false);
    const [isAtStart, setIsAtStart] = React.useState(true);
    const [isAtEnd, setIsAtEnd] = React.useState(false);

    // Expose the scrollable element via ref
    React.useImperativeHandle(forwardedRef, () => viewportRef.current!, []);

    const scheduleScrollIdleReset = React.useCallback(() => {
      if (scrollEndTimerRef.current !== null) {
        clearTimeout(scrollEndTimerRef.current);
      }
      scrollEndTimerRef.current = setTimeout(() => {
        setIsScrolling(false);
        scrollEndTimerRef.current = null;
      }, SCROLL_END_DELAY);
    }, []);

    const updateMetrics = React.useCallback(
      (el: HTMLDivElement, emit: boolean) => {
        const { scrollLeft, scrollWidth, clientWidth } = el;

        const atStart = scrollLeft <= EDGE_EPSILON;
        const atEnd = scrollWidth - (scrollLeft + clientWidth) <= EDGE_EPSILON;

        setIsAtStart(prev => (prev !== atStart ? atStart : prev));
        setIsAtEnd(prev => (prev !== atEnd ? atEnd : prev));

        const next: ScrollMetrics = {
          left: scrollLeft,
          width: scrollWidth,
          viewport: clientWidth,
          atStart,
          atEnd
        };

        const prevMetrics = metricsRef.current;
        const changed =
          !prevMetrics ||
          Math.abs(prevMetrics.left - next.left) > EDGE_EPSILON ||
          prevMetrics.width !== next.width ||
          prevMetrics.viewport !== next.viewport ||
          prevMetrics.atStart !== next.atStart ||
          prevMetrics.atEnd !== next.atEnd;

        if (emit && changed && onScrollChange) onScrollChange(next);
        if (changed) metricsRef.current = next;
      },
      [onScrollChange]
    );

    const handleScroll = React.useCallback(
      (event: React.UIEvent<HTMLDivElement>) => {
        onScroll?.(event);
        setIsScrolling(true);
        scheduleScrollIdleReset();
        updateMetrics(event.currentTarget, true);
      },
      [onScroll, scheduleScrollIdleReset, updateMetrics]
    );

    const handleWheel = React.useCallback(
      (event: React.WheelEvent<HTMLDivElement>) => {
        onWheel?.(event);
        setIsScrolling(true);
        scheduleScrollIdleReset();
      },
      [onWheel, scheduleScrollIdleReset]
    );

    const applyScroll = React.useCallback(
      (direction: -1 | 1) => {
        const el = viewportRef.current!;
        const step = pageBy === 'viewport' ? el.clientWidth : pageSize;
        el.scrollBy({ left: step * direction, behavior: 'auto' });
      },
      [pageBy, pageSize]
    );

    React.useEffect(() => {
      const el = viewportRef.current!;

      const handler = () => updateMetrics(el, true);
      updateMetrics(el, true);

      if (typeof ResizeObserver === 'function') {
        const ro = new ResizeObserver(handler);
        ([el, railRef.current] as (Element | null)[])
          .filter(Boolean)
          .forEach(node => ro.observe(node as Element));
        return () => ro.disconnect();
      }
      return undefined;
    }, [updateMetrics]);

    React.useEffect(() => {
      return () => {
        if (scrollEndTimerRef.current !== null) clearTimeout(scrollEndTimerRef.current);
      };
    }, []);

    const baseClassName = collapseWhitespace(
      composeClasses(baseClasses, className, {
        [stateClasses.isScrolling]: isScrolling,
        [stateClasses.isAtStart]: isAtStart,
        [stateClasses.isAtEnd]: isAtEnd,
        [stateClasses.hasControls]: showControls
      })
    );

    const viewportClassName = collapseWhitespace(composeClasses(viewportClasses));
    const railClassName = collapseWhitespace(composeClasses(railClasses));
    const controlsClassName = collapseWhitespace(composeClasses(controlsClasses));
    const prevWrapperClassName = collapseWhitespace(composeClasses(prevWrapperClasses));
    const nextWrapperClassName = collapseWhitespace(composeClasses(nextWrapperClasses));

    const canPrev = !isAtStart;
    const canNext = !isAtEnd;

    return (
      <div ref={baseRef} className={baseClassName} data-slot="base" {...rest}>
        <div
          ref={viewportRef}
          className={viewportClassName}
          data-slot="_viewport"
          onScroll={handleScroll}
          onWheel={handleWheel}
        >
          <div
            ref={railRef}
            className={railClassName}
            data-slot="_rail"
            data-stack-rows={stackRows ? 'true' : undefined}
          >
            {children}
          </div>
        </div>

        {showControls ? (
          <div className={controlsClassName} data-slot="_controls">
            <div className={prevWrapperClassName} data-slot="_prev">
              <Control
                icon={<ArrowBackIcon aria-hidden="true" />}
                ariaLabel="Scroll left"
                size="sm"
                variant={canPrev ? 'brand' : 'light'}
                onClick={() => applyScroll(-1)}
              />
            </div>
            <div className={nextWrapperClassName} data-slot="_next">
              <Control
                icon={<ArrowForwardIcon aria-hidden="true" />}
                ariaLabel="Scroll right"
                size="sm"
                variant={canNext ? 'brand' : 'light'}
                onClick={() => applyScroll(1)}
              />
            </div>
          </div>
        ) : null}
      </div>
    );
  }
);

Scroller.displayName = 'Scroller';
