// packages/core/src/components/client/Scroller/Scroller.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories for Scroller using MediaCard (no image) and ContentCard (horizontal, no image).
// - Default: single row with MediaCards
// - FixedPage: ContentCards horizontal, no image
// - StackRows: three ScrollerRow rows with MediaCards
// - NoControls: ContentCards horizontal, no image, controls hidden

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { fn } from 'storybook/test';
import Readme from './README.md?raw';
import { Scroller, type ScrollerProps } from './Scroller';

// Server-side presentation components used in stories
// Note: Storybook allows mixing server/client imports. In Next.js app code,
// pass Server children into the client Scroller from a Server parent.
import { ScrollerRow } from '../../server/ScrollerRow';
import { MediaCard } from '../../server/MediaCard';
import { ContentCard } from '../../server/ContentCard';
import { MediaControl } from '../MediaControl';
import { EventIcon } from '../../../icons';

const EYEBROWS = ['Design', 'Product', 'News', 'Release', 'Guide'] as const;

const makeMediaCard = (index: number) => (
  <MediaCard
    key={`media-${index}`}
    title={`Media item ${index + 1}`}
    subtitle="Example content without an image"
    labels={[
      { label: EYEBROWS[index % EYEBROWS.length], icon: <EventIcon /> },
      { label: EYEBROWS[(index + 1) % EYEBROWS.length], icon: <EventIcon /> }
    ]}
    control={
      <MediaControl
        ariaLabelPlay={`Play media item ${index + 1}`}
        ariaLabelPause={`Pause media item ${index + 1}`}
      />
    }
  />
);

const makeContentCard = (index: number) => (
  <ContentCard
    key={`content-${index}`}
    title={`Content item ${index + 1}`}
    description="Horizontal layout without an image."
    layout="horizontal"
    href="#"
    labels={[
      { label: EYEBROWS[index % EYEBROWS.length], icon: <EventIcon /> },
      { label: EYEBROWS[(index + 1) % EYEBROWS.length], icon: <EventIcon /> }
    ]}
  />
);

// Default: single row of MediaCards (NoImage)
const defaultChildren = Array.from({ length: 10 }, (_, i) => makeMediaCard(i));

const meta: Meta<ScrollerProps> = {
  title: 'Client components/Scroller',
  component: Scroller,
  args: {
    showControls: true,
    pageBy: 'viewport',
    children: defaultChildren,
    onScrollChange: fn()
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Manual horizontal scroller with prev/next Controls. Next.js note: pass server-rendered children (e.g., `<ScrollerRow>` or `<MediaCard>`) from a parent server component; do not import server components into this client Scroller. Controls are rendered outside the scroll viewport and do not scroll with content. The viewport hides native scrollbars while remaining scrollable.'
      },
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<ScrollerProps>;

// 1) Default — single row MediaCards (NoImage)
export const Default: Story = {};

// 2) FixedPage — ContentCards, horizontal, no image
export const FixedPage: Story = {
  args: {
    pageBy: 'fixed',
    pageSize: 320,
    children: Array.from({ length: 10 }, (_, i) => makeContentCard(i))
  }
};

// 3) StackRows — three ScrollerRow rows, each with MediaCards (NoImage)
const threeRows = (
  <>
    {Array.from({ length: 3 }, (_, row) => (
      <ScrollerRow key={`row-${row}`}>
        {Array.from({ length: 4 }, (_, i) => makeMediaCard(row * 4 + i))}
      </ScrollerRow>
    ))}
  </>
);

export const StackRows: Story = {
  args: {
    stackRows: true,
    children: threeRows
  }
};

// 4) NoControls — ContentCards, horizontal, no image, controls hidden
export const NoControls: Story = {
  args: {
    showControls: false,
    children: Array.from({ length: 8 }, (_, i) => makeContentCard(i))
  }
};
