import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import { AvatarGroup, type AvatarGroupProps } from './AvatarGroup';

describe('AvatarGroup', () => {
  const baseUsers: AvatarGroupProps['users'] = [
    { name: 'Aliyah Ward', imageUrl: 'https://example.com/aliyah.jpg' },
    { name: 'Bruno Castro', imageUrl: 'https://example.com/bruno.jpg' },
    { name: 'Carmen Reyes', imageUrl: 'https://example.com/carmen.jpg' },
    { name: 'Diego Luna', imageUrl: 'https://example.com/diego.jpg' },
    { name: 'Elisa Novak', imageUrl: 'https://example.com/elisa.jpg' }
  ];

  const renderAvatarGroup = (props?: Partial<AvatarGroupProps>) =>
    render(
      <AvatarGroup
        indicator="+"
        message="others interested"
        showMessage
        avatarsToDisplay={4}
        users={baseUsers}
        {...props}
      />
    );

  it('renders the message text when showMessage is true', () => {
    renderAvatarGroup();
    expect(screen.getByText('others interested')).toBeInTheDocument();
  });

  it('renders an avatar per user', () => {
    const { container } = renderAvatarGroup();
    expect(container.querySelectorAll('[data-slot="avatar"]').length).toBe(baseUsers.length);
  });

  describe('count abbreviation', () => {
    const cases: ReadonlyArray<[number, string]> = [
      [0, '0'],
      [7, '7'],
      [987, '987'],
      [1_300, '1k'],
      [6_892, '7k'],
      [1_200_000, '1m']
    ];

    it.each(cases)('abbreviates %d to %s', (incomingCount, expected) => {
      render(
        <AvatarGroup
          indicator="+"
          message="others interested"
          showMessage
          avatarsToDisplay={0}
          users={[]}
          count={incomingCount}
        />
      );
      expect(screen.getByText(expected, { selector: '[data-slot="count"]' })).toBeInTheDocument();
    });
  });

  it('calculates displayCount from users length when count is omitted', () => {
    renderAvatarGroup();
    expect(screen.getByText('0', { selector: '[data-slot="count"]' })).toBeInTheDocument();
  });

  it('uses the provided count when supplied', () => {
    renderAvatarGroup({ count: 20 });
    expect(screen.getByText('15', { selector: '[data-slot="count"]' })).toBeInTheDocument();
  });

  it('hides the message when showMessage is false', () => {
    const { container } = renderAvatarGroup({ showMessage: false });
    expect(container.querySelector('[data-slot="message"]')).toBeNull();
  });

  it('renders fallback initial when name is provided', () => {
    render(
      <AvatarGroup
        indicator="+"
        message="others interested"
        showMessage
        avatarsToDisplay={1}
        users={[{ name: 'zoe fitz', imageUrl: '' }]}
      />
    );
    expect(screen.getByText('Z')).toBeInTheDocument();
  });

  it('renders empty fallback text when name is missing', () => {
    const { container } = render(
      <AvatarGroup
        indicator="+"
        message="others interested"
        showMessage
        avatarsToDisplay={1}
        users={[{ name: '', imageUrl: '' }]}
      />
    );
    expect(container.querySelector('[data-slot="avatarFallback"]')?.textContent).toBe('');
  });

  it('sets img alt attribute from the user name', () => {
    renderAvatarGroup();
    expect(screen.getByRole('img', { name: 'Aliyah Ward' })).toHaveAttribute('alt', 'Aliyah Ward');
  });
});
