import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import type { TextLinkProps } from './TextLink';
import { TextLink } from './TextLink';

describe('TextLink', () => {
  const renderLink = (props?: Partial<TextLinkProps>) =>
    render(
      <TextLink
        href="#example"
        label="Visit example"
        variant="brand"
        {...props}
      />
    );

  it('renders link with visible label', () => {
    renderLink();
    expect(screen.getByRole('link', { name: 'Visit example' })).toBeInTheDocument();
  });

  describe('variants', () => {
    const variantCases: ReadonlyArray<[TextLinkProps['variant'], string]> = [
      ['brand', 'text-comp-text-link-brand-color-foreground-default'],
      ['strong', 'text-comp-text-link-strong-color-foreground-default'],
      ['subtle', 'text-comp-text-link-subtle-color-foreground-default'],
      ['inverted', 'text-comp-text-link-inverted-color-foreground-default']
    ];

    it.each(variantCases)('applies %s variant classes', (variant, classToken) => {
      renderLink({ variant });
      const link = screen.getByRole('link', { name: 'Visit example' });
      expect(link).toHaveClass(classToken);
    });
  });

  it('renders start icon with aria-hidden', () => {
    renderLink({ startIcon: <span data-testid="start-icon">*</span> });
    expect(screen.getByTestId('start-icon').closest('span')).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders end icon with aria-hidden', () => {
    renderLink({ endIcon: <span data-testid="end-icon">*</span> });
    expect(screen.getByTestId('end-icon').closest('span')).toHaveAttribute('aria-hidden', 'true');
  });

  it('marks link as disabled via aria-disabled', () => {
    renderLink({ disabled: true });
    expect(screen.getByRole('link', { name: 'Visit example' })).toHaveAttribute('aria-disabled', 'true');
  });

  it('removes disabled link from tab order', () => {
    renderLink({ disabled: true });
    expect(screen.getByRole('link', { name: 'Visit example' })).toHaveAttribute('tabindex', '-1');
  });

  it('suppresses click handlers when disabled', () => {
    const handleClick = jest.fn();
    renderLink({ disabled: true, onClick: handleClick });
    fireEvent.click(screen.getByRole('link', { name: 'Visit example' }));
    expect(handleClick).not.toHaveBeenCalled();
  });

  it('includes focus ring token class', () => {
    renderLink();
    expect(screen.getByRole('link', { name: 'Visit example' })).toHaveClass(
      'focus-visible:ring-comp-text-link-focus-color-ring'
    );
  });

  it('throws when label is empty', () => {
    expect(() =>
      render(
        <TextLink
          href="#example"
          label="   "
          variant="brand"
        />
      )
    ).toThrow('TextLink requires a non-empty label.');
  });

  it('throws when href is empty', () => {
    expect(() =>
      render(
        <TextLink
          href="   "
          label="Visit example"
          variant="brand"
        />
      )
    ).toThrow('TextLink requires a non-empty href.');
  });
});
