// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { ArrowRightIcon, ArrowLeftIcon } from '@radix-ui/react-icons';
import { TextLink, TextLinkProps } from './TextLink';

const meta: Meta<TextLinkProps> = {
  title: 'Components/TextLink',
  component: TextLink,
  args: {
    label: 'Learn more',
    href: '#',
    variant: 'brand',
    disabled: false
  },
  argTypes: {
    variant: { control: { type: 'radio' }, options: ['brand', 'strong', 'subtle', 'inverted'] },
    disabled: { control: 'boolean' },
    href: { control: 'text' },
    label: { control: 'text' },
    startIcon: { control: false },
    endIcon: { control: false }
  }
};

export default meta;

type Story = StoryObj<TextLinkProps>;

export const Default: Story = {
  args: {
    startIcon: <ArrowLeftIcon />,
    endIcon: <ArrowRightIcon />
  }
};

export const Strong: Story = {
  args: {
    variant: 'strong'
  }
};

export const Subtle: Story = {
  args: {
    variant: 'subtle'
  }
};

export const Inverted: Story = {
  args: {
    variant: 'inverted'
  }
};

export const Disabled: Story = {
  args: {
    disabled: true
  }
};

export const WithStartIcon: Story = {
  args: {
    startIcon: <ArrowLeftIcon />,
    endIcon: undefined
  }
};

export const WithEndIcon: Story = {
  args: {
    startIcon: undefined,
    endIcon: <ArrowRightIcon />
  }
};

export const WithIcons: Story = {
  args: {
    startIcon: <ArrowLeftIcon />,
    endIcon: <ArrowRightIcon />
  }
};
