// packages/core/src/components/server/Text/Text.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Text renders semantic inline content with typographic variants, transform/alignment classes, and italic/truncate states via native HTML tags.

import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type TextElement =
  | 'span'
  | 'p'
  | 'div'
  | 'label'
  | 'strong'
  | 'em'
  | 'small'
  | 'code'
  | 'kbd'
  | 'mark';

type TextSize =
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
  | '7xl'
  | '8xl'
  | 'inherit';
type TextWeight =
  | 'thin'
  | 'extra-light'
  | 'light'
  | 'normal'
  | 'medium'
  | 'semi-bold'
  | 'bold'
  | 'extra-bold'
  | 'black'
  | 'inherit';
type TextAlign = 'left' | 'center' | 'right' | 'justify' | 'inherit';
type TextColor =
  | 'default'
  | 'brand'
  | 'weak'
  | 'inverse'
  | 'subtle'
  | 'danger-strong'
  | 'danger-subtle'
  | 'warning-strong'
  | 'warning-subtle'
  | 'success-strong'
  | 'success-subtle'
  | 'info-strong'
  | 'info-subtle'
  | 'inherit';
type TextTransform = 'normal' | 'uppercase' | 'lowercase' | 'capitalize' | 'inherit';

type NonInherited<T extends string> = Exclude<T, 'inherit'>;

export interface TextProps<T extends TextElement = 'span'> {
  as?: T;
  size?: TextSize;
  weight?: TextWeight;
  align?: TextAlign;
  color?: TextColor;
  transform?: TextTransform;
  italic?: boolean;
  truncate?: boolean;
  className?: string;
  children?: React.ReactNode;
}

type PolymorphicTextProps<T extends TextElement> = TextProps<T> &
  (T extends TextElement ? Omit<React.ComponentPropsWithoutRef<T>, keyof TextProps<T>> : never);

const sizeClassMap: Record<NonInherited<TextSize>, string> = {
  xs: `text-xs`,
  sm: `text-sm`,
  base: `text-base`,
  lg: `text-lg`,
  xl: `text-xl`,
  '2xl': `text-2xl`,
  '3xl': `text-3xl`,
  '4xl': `text-4xl`,
  '5xl': `text-5xl`,
  '6xl': `text-6xl`,
  '7xl': `text-7xl`,
  '8xl': `text-8xl`
} as const;

const weightClassMap: Record<NonInherited<TextWeight>, string> = {
  thin: `font-thin`,
  'extra-light': `font-extralight`,
  light: `font-light`,
  normal: `font-normal`,
  medium: `font-medium`,
  'semi-bold': `font-semibold`,
  bold: `font-bold`,
  'extra-bold': `font-extrabold`,
  black: `font-black`
} as const;

const alignClassMap: Record<NonInherited<TextAlign>, string> = {
  left: `text-left`,
  center: `text-center`,
  right: `text-right`,
  justify: `text-justify`
} as const;

const colorClassMap: Record<NonInherited<TextColor>, string> = {
  default: `text-color-content-default`,
  brand: `text-color-content-brand`,
  weak: `text-color-content-weak`,
  inverse: `text-color-content-inverse`,
  subtle: `text-color-content-subtle`,
  'danger-strong': `text-color-content-utility-danger-strong`,
  'danger-subtle': `text-color-content-utility-danger-subtle`,
  'warning-strong': `text-color-content-utility-warning-strong`,
  'warning-subtle': `text-color-content-utility-warning-subtle`,
  'success-strong': `text-color-content-utility-success-strong`,
  'success-subtle': `text-color-content-utility-success-subtle`,
  'info-strong': `text-color-content-utility-info-strong`,
  'info-subtle': `text-color-content-utility-info-subtle`
} as const;

const transformClassMap: Record<NonInherited<TextTransform>, string> = {
  normal: `normal-case`,
  uppercase: `uppercase`,
  lowercase: `lowercase`,
  capitalize: `capitalize`
} as const;

const italicClass = `italic`;
const truncateClass = `truncate`;

type TextComponent = <T extends TextElement = 'span'>(
  props: PolymorphicTextProps<T> & { ref?: React.Ref<React.ElementRef<T>> }
) => React.ReactElement | null;

const TextWithRef = React.forwardRef(
  (
    {
      as,
      size = 'base',
      weight = 'normal',
      align = 'inherit',
      color = 'default',
      transform = 'inherit',
      italic = false,
      truncate = false,
      className,
      children,
      ...rest
    }: PolymorphicTextProps<TextElement>,
    forwardedRef: React.ForwardedRef<HTMLElement>
  ) => {
    const Comp = as ?? 'span';

    const textClassName = collapseWhitespace(
      composeClasses(
        size !== 'inherit' ? sizeClassMap[size] : null,
        weight !== 'inherit' ? weightClassMap[weight] : null,
        align !== 'inherit' ? alignClassMap[align] : null,
        color !== 'inherit' ? colorClassMap[color] : null,
        transform !== 'inherit' ? transformClassMap[transform] : null,
        italic ? italicClass : null,
        truncate ? truncateClass : null,
        className
      )
    );

    return (
      <Comp
        ref={forwardedRef as React.Ref<never>}
        className={textClassName}
        {...(rest as Record<string, never>)}
      >
        {children}
      </Comp>
    );
  }
);

TextWithRef.displayName = 'Text';

export const Text = TextWithRef as TextComponent;
