// packages/core/src/components/client/Control/Control.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Confirms Control enforces non-empty ariaLabel, renders button with icon slot, and applies variant and size class tokens.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import type { ControlProps } from './Control';
import { Control } from './Control';

const sampleIcon = <span data-testid="control-icon">★</span>;

const renderControl = (props?: Partial<ControlProps>) =>
  render(<Control icon={sampleIcon} ariaLabel="Control icon" {...props} />);

describe('Control', () => {
  it('renders with accessible name', () => {
    renderControl();
    expect(screen.getByLabelText('Control icon')).toBeInTheDocument();
  });

  it('renders as a button element', () => {
    renderControl();
    expect(screen.getByRole('button', { name: 'Control icon' })).toBeInTheDocument();
  });

  it('throws when ariaLabel is empty', () => {
    expect(() => render(<Control icon={sampleIcon} ariaLabel="   " />)).toThrow(
      'Control requires a non-empty ariaLabel.'
    );
  });

  it('renders icon slot once', () => {
    renderControl();
    expect(screen.getAllByTestId('control-icon')).toHaveLength(1);
  });

  describe('variants', () => {
    const cases: ReadonlyArray<[ControlProps['variant'], string]> = [
      ['brand', 'bg-comp-button-primary-color-background-default'],
      ['dark', 'bg-comp-button-color-background-knockout-blur'],
      ['light', 'bg-comp-button-color-background-default-blur']
    ];

    it.each(cases)('applies %s variant classes', (variant, classToken) => {
      renderControl({ variant });
      const root = screen.getByLabelText('Control icon');
      expect(root).toHaveClass(classToken);
    });
  });

  describe('sizes', () => {
    const sizeCases: ReadonlyArray<[ControlProps['size'], [string, string]]> = [
      ['lg', ['h-40', 'w-40']],
      ['sm', ['h-32', 'w-32']]
    ];

    it.each(sizeCases)('applies %s size classes', (size, expectedClasses) => {
      renderControl({ size });
      const root = screen.getByLabelText('Control icon');
      expect(root).toHaveClass(...expectedClasses);
    });
  });
});
