// packages/core/src/components/client/Control/Control.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories for Control button showcasing brand/dark/light variants and size options with customizable icon aria labeling.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react-vite';
import * as React from 'react';
import { CheckIcon } from '@radix-ui/react-icons';
import Readme from './README.md?raw';
import { Control, ControlProps } from './Control';

const meta: Meta<ControlProps> = {
  title: 'Client components/Control',
  component: Control,
  args: {
    icon: <CheckIcon />,
    ariaLabel: 'Control icon',
    variant: 'brand',
    size: 'lg'
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<ControlProps>;

export const Default: Story = {};

export const Dark: Story = {
  args: {
    variant: 'dark'
  }
};

export const Light: Story = {
  args: {
    variant: 'light'
  }
};
