// packages/core/src/components/client/Carousel/Carousel.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories for Carousel covering default usage, autoplay behavior, snapping alignments, RTL, and non-looping edge cases.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react';
import { fn } from 'storybook/test';
import * as React from 'react';
import Readme from './README.md?raw';
import { Carousel, CarouselProps } from './Carousel';

const slideItems = Array.from({ length: 5 }, (_, index) => {
  const label = `Slide ${index + 1}`;

  return (
    <div
      key={label}
      className={`flex h-12 min-w-full items-center justify-center rounded-lg bg-color-background-subtle text-color-content-strong text-lg font-semibold`}
    >
      {label}
    </div>
  );
});

const Template: React.FC<CarouselProps> = props => (
  <div className={`mx-auto w-full max-w-xl text-color-content-default`}>
    <Carousel {...props}>{slideItems}</Carousel>
  </div>
);

const meta: Meta<CarouselProps> = {
  title: 'Client components/Carousel',
  component: Carousel,
  args: {
    ariaLabel: 'Featured stories',
    loop: false,
    align: 'center',
    showIndicators: true,
    autoPlay: false,
    autoPlayDelay: 4000,
    onChange: fn(),
    onInViewChange: fn(),
    onAutoPlayChange: fn()
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component: '`defaultIndex` and `currentIndex` are 0-based.'
      },
      page: () => <Markdown>{Readme}</Markdown>
    }
  },
  render: args => <Template {...args} />
};

export default meta;

type Story = StoryObj<CarouselProps>;

export const Default: Story = {};

export const AlignCenter: Story = {
  args: {
    align: 'center'
  }
};

export const Autoplay: Story = {
  args: {
    autoPlay: true,
    loop: true,
    autoPlayPauseOnInteraction: true,
    autoPlayPauseOnHover: true,
    autoPlayPauseOnFocus: true,
    respectReducedMotion: true
  }
};

export const AlignStart: Story = {
  args: {
    align: 'start'
  }
};

export const AlignEnd: Story = {
  args: {
    align: 'end'
  }
};

const RtlWrapper: React.FC<CarouselProps> = props => {
  React.useEffect(() => {
    const element = document.documentElement;
    const previousDir = element.getAttribute('dir') ?? 'ltr';
    element.setAttribute('dir', 'rtl');

    return () => {
      element.setAttribute('dir', previousDir);
    };
  }, []);

  return (
    <div dir="rtl" className={`mx-auto w-full max-w-xl`}>
      <Carousel {...props}>{slideItems}</Carousel>
    </div>
  );
};

export const Rtl: Story = {
  render: args => <RtlWrapper {...args} />
};

export const NonLoopingThreeSlides: Story = {
  args: {
    loop: false,
    showIndicators: true
  },
  render: args => {
    const shortSlides = slideItems.slice(0, 3);

    return (
      <div className={`mx-auto w-full max-w-xl`}>
        <Carousel {...args}>{shortSlides}</Carousel>
      </div>
    );
  }
};
