'use client';

// packages/core/src/components/client/Dropdown/Dropdown.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Dropdown composes Popover with a secondary Button trigger, optional icon props, placement controls, and consumer-owned panel content.

import * as React from 'react';
import { Popover } from 'radix-ui';
import { ArrowDropDownIcon } from '../../../icons';
import { collapseWhitespace, composeClasses } from '../../../utilities';
import { Button } from '../Button';

const containerClasses = `min-w-160`;

const containerChildClasses = `grow text-left`;

const contentClasses = `
  rounded-md
  border
  shadow-md
  p-2
  bg-color-background-default
  text-color-content-default
  border-color-border-subtle
`;

type Align = 'start' | 'center' | 'end';
type Side = 'top' | 'right' | 'bottom' | 'left';
type AriaHaspopup = 'menu' | 'listbox' | 'dialog';

export interface DropdownProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'children'> {
  label: string;
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  align?: Align;
  side?: Side;
  sideOffset?: number;
  collisionPadding?: number;
  trapFocus?: boolean;
  ariaHaspopup?: AriaHaspopup;
  children: React.ReactNode;
}

export const Dropdown = React.forwardRef<HTMLDivElement, DropdownProps>((props, ref) => {
  const {
    label,
    startIcon,
    endIcon,
    open,
    defaultOpen = false,
    onOpenChange,
    disabled = false,
    align = 'start',
    side = 'bottom',
    sideOffset = 8,
    collisionPadding = 8,
    trapFocus = false,
    ariaHaspopup = 'menu',
    children,
    className,
    ...rest
  } = props;

  const [internalOpen, setInternalOpen] = React.useState(defaultOpen);

  React.useEffect(() => {
    if (open === undefined) {
      setInternalOpen(defaultOpen);
    }
  }, [defaultOpen, open]);

  const handleOpenChange = React.useCallback(
    (nextOpen: boolean) => {
      if (open === undefined) {
        setInternalOpen(nextOpen);
      }

      onOpenChange?.(nextOpen);
    },
    [open, onOpenChange]
  );

  const resolvedOpen = open ?? internalOpen;

  const baseClassName = collapseWhitespace(composeClasses(className));
  const containerClassName = collapseWhitespace(composeClasses(containerClasses));
  const containerChildClassName = collapseWhitespace(composeClasses(containerChildClasses));
  const contentClassName = collapseWhitespace(composeClasses(contentClasses));
  const resolvedEndIcon = endIcon ?? <ArrowDropDownIcon aria-hidden="true" />;

  return (
    <div ref={ref} className={baseClassName} data-slot="base" {...rest}>
      <Popover.Root
        open={open}
        defaultOpen={open === undefined ? defaultOpen : undefined}
        onOpenChange={handleOpenChange}
        modal={trapFocus}
      >
        <Popover.Trigger asChild data-slot="trigger">
          <Button
            variant="secondary"
            startIcon={startIcon}
            endIcon={resolvedEndIcon}
            disabled={disabled}
            aria-haspopup={ariaHaspopup}
            aria-expanded={resolvedOpen}
            className={containerClassName}
            data-slot="container"
          >
            <div className={containerChildClassName}>{label}</div>
          </Button>
        </Popover.Trigger>
        <Popover.Portal>
          <Popover.Content
            className={contentClassName}
            align={align}
            side={side}
            sideOffset={sideOffset}
            collisionPadding={collisionPadding}
            data-slot="content"
          >
            {children}
          </Popover.Content>
        </Popover.Portal>
      </Popover.Root>
    </div>
  );
});

Dropdown.displayName = 'Dropdown';
