// packages/core/src/icons/Replay10Icon/Replay10Icon.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook stories for Replay10Icon showcasing decorative default and non-decorative role=img usage with color/className controls.

import type { Meta, StoryObj } from '@storybook/react';
import { Replay10Icon, Replay10IconProps } from './Replay10Icon';

const meta: Meta<Replay10IconProps> = {
  title: 'Icons/Replay10Icon',
  component: Replay10Icon,
  args: {
    decorative: true,
    color: 'currentColor'
  },
  argTypes: {
    decorative: { control: 'boolean' },
    title: { control: 'text' },
    titleId: { control: 'text' },
    color: { control: 'color' },
    className: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<Replay10IconProps>;

export const Default: Story = {};

export const NonDecorative: Story = {
  args: {
    decorative: false,
    title: 'Dismiss notification',
    titleId: 'close-icon-title'
  }
};
