// packages/core/src/components/server/Heading/Heading.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories showcase Heading defaults, auto presets per level, and prop-driven variant tables (size, weight, align, color, transform, italic, truncate).

import type { Meta, StoryObj } from '@storybook/react-vite';
import { Markdown } from '@storybook/addon-docs/blocks';
import * as React from 'react';
import { Heading, HeadingProps } from './Heading';
import Readme from './README.md?raw';

const meta: Meta<HeadingProps> = {
  title: 'Server components/Heading',
  component: Heading,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  },
  args: {
    as: 'h2',
    size: 'auto',
    weight: 'auto',
    align: 'inherit',
    color: 'default',
    transform: 'inherit',
    italic: false,
    truncate: false,
    noMargin: true,
    children: 'Heading text'
  }
};

export default meta;

type Story = StoryObj<HeadingProps>;

const stackStyle: React.CSSProperties = {
  display: 'flex',
  flexDirection: 'column',
  gap: '0.75rem'
};

/**
 * Baseline stories (preserved)
 */
export const Default: Story = {};

export const HeadingH1: Story = {
  args: {
    as: 'h1',
    size: 'auto',
    weight: 'auto',
    children: 'Heading 1'
  }
};

export const HeadingH2: Story = {
  args: {
    as: 'h2',
    size: 'auto',
    weight: 'auto',
    children: 'Heading 2'
  }
};

export const HeadingH3: Story = {
  args: {
    as: 'h3',
    size: 'auto',
    weight: 'auto',
    children: 'Heading 3'
  }
};

export const HeadingH4: Story = {
  args: {
    as: 'h4',
    size: 'auto',
    weight: 'auto',
    children: 'Heading 4'
  }
};

export const HeadingH5: Story = {
  args: {
    as: 'h5',
    size: 'auto',
    weight: 'auto',
    children: 'Heading 5'
  }
};

export const HeadingH6: Story = {
  args: {
    as: 'h6',
    size: 'auto',
    weight: 'auto',
    children: 'Heading 6'
  }
};

/**
 * Prop-based stories (mirroring Text.stories)
 */
const sizeOptions: Array<Exclude<HeadingProps['size'], 'inherit' | 'auto'>> = [
  'xs',
  'sm',
  'base',
  'lg',
  'xl',
  '2xl',
  '3xl',
  '4xl',
  '5xl',
  '6xl',
  '7xl',
  '8xl'
];

export const Sizes: Story = {
  render: () => (
    <div style={stackStyle}>
      {sizeOptions.map(size => (
        <Heading key={size} size={size}>
          {`Size ${size}`}
        </Heading>
      ))}
    </div>
  )
};

const weightOptions: Array<Exclude<HeadingProps['weight'], 'inherit' | 'auto'>> = [
  'thin',
  'extra-light',
  'light',
  'normal',
  'medium',
  'semi-bold',
  'bold',
  'extra-bold',
  'black'
];

export const Weights: Story = {
  render: () => (
    <div style={stackStyle}>
      {weightOptions.map(weight => (
        <Heading key={weight} weight={weight}>
          {`Weight ${weight}`}
        </Heading>
      ))}
    </div>
  )
};

const alignOptions: Array<Exclude<HeadingProps['align'], 'inherit'>> = [
  'left',
  'center',
  'right',
  'justify'
];

export const Alignments: Story = {
  render: () => (
    <div style={{ ...stackStyle, width: '32rem' }}>
      {alignOptions.map(alignment => (
        <Heading key={alignment} align={alignment}>
          {`Alignment ${alignment}: Lorem ipsum dolor sit amet, consectetur adipiscing elit.`}
        </Heading>
      ))}
    </div>
  )
};

const colorOptions: Array<Exclude<HeadingProps['color'], 'inherit'>> = [
  'default',
  'brand',
  'weak',
  'inverse',
  'subtle',
  'danger-strong',
  'danger-subtle',
  'warning-strong',
  'warning-subtle',
  'success-strong',
  'success-subtle',
  'info-strong',
  'info-subtle'
];

export const Colors: Story = {
  render: () => (
    <div style={stackStyle}>
      {colorOptions.map(color => (
        <Heading key={color} color={color}>
          {`Color ${color}`}
        </Heading>
      ))}
    </div>
  )
};

const transformOptions: Array<Exclude<HeadingProps['transform'], 'inherit'>> = [
  'normal',
  'uppercase',
  'lowercase',
  'capitalize'
];

export const Transforms: Story = {
  render: () => (
    <div style={stackStyle}>
      <Heading transform="inherit">Transform inherit (no class)</Heading>
      {transformOptions.map(transform => (
        <Heading key={transform} transform={transform}>
          {`Transform ${transform} text`}
        </Heading>
      ))}
    </div>
  )
};

export const Italic: Story = {
  args: {
    italic: true,
    children: 'Italic emphasis heading.'
  }
};

export const Truncate: Story = {
  args: {
    truncate: true,
    children:
      'This is a very long heading intended to demonstrate single-line truncation with an ellipsis when space is constrained.'
  },
  render: args => (
    <div style={{ width: '16rem' }}>
      <Heading {...args} />
    </div>
  )
};
