// packages/core/src/components/server/Heading/Heading.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Heading renders semantic h1–h6 elements with typography presets, color/align variants, and utility states.

import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type HeadingTag = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
type HeadingSize =
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
  | '7xl'
  | '8xl'
  | 'auto'
  | 'inherit';
type HeadingWeight =
  | 'thin'
  | 'extra-light'
  | 'light'
  | 'normal'
  | 'medium'
  | 'semi-bold'
  | 'bold'
  | 'extra-bold'
  | 'black'
  | 'auto'
  | 'inherit';
type HeadingAlign = 'left' | 'center' | 'right' | 'justify' | 'inherit';
type HeadingColor =
  | 'default'
  | 'brand'
  | 'weak'
  | 'inverse'
  | 'subtle'
  | 'danger-strong'
  | 'danger-subtle'
  | 'warning-strong'
  | 'warning-subtle'
  | 'success-strong'
  | 'success-subtle'
  | 'info-strong'
  | 'info-subtle'
  | 'inherit';
type HeadingTransform = 'normal' | 'uppercase' | 'lowercase' | 'capitalize' | 'inherit';

export interface HeadingProps extends React.HTMLAttributes<HTMLHeadingElement> {
  as?: HeadingTag;
  size?: HeadingSize;
  weight?: HeadingWeight;
  align?: HeadingAlign;
  color?: HeadingColor;
  transform?: HeadingTransform;
  italic?: boolean;
  truncate?: boolean;
  noMargin?: boolean;
}

const sizeClassMap: Record<Exclude<HeadingSize, 'auto' | 'inherit'>, string> = {
  xs: `text-xs`,
  sm: `text-sm`,
  base: `text-base`,
  lg: `text-lg`,
  xl: `text-xl`,
  '2xl': `text-2xl`,
  '3xl': `text-3xl`,
  '4xl': `text-4xl`,
  '5xl': `text-5xl`,
  '6xl': `text-6xl`,
  '7xl': `text-7xl`,
  '8xl': `text-8xl`
};

const weightClassMap: Record<Exclude<HeadingWeight, 'auto' | 'inherit'>, string> = {
  thin: `font-thin`,
  'extra-light': `font-extralight`,
  light: `font-light`,
  normal: `font-normal`,
  medium: `font-medium`,
  'semi-bold': `font-semibold`,
  bold: `font-bold`,
  'extra-bold': `font-extrabold`,
  black: `font-black`
};

const alignClassMap: Record<Exclude<HeadingAlign, 'inherit'>, string> = {
  left: `text-left`,
  center: `text-center`,
  right: `text-right`,
  justify: `text-justify`
};

const colorClassMap: Record<Exclude<HeadingColor, 'inherit'>, string> = {
  default: `text-color-content-default`,
  brand: `text-color-content-brand`,
  weak: `text-color-content-weak`,
  inverse: `text-color-content-inverse`,
  subtle: `text-color-content-subtle`,
  'danger-strong': `text-color-content-utility-danger-strong`,
  'danger-subtle': `text-color-content-utility-danger-subtle`,
  'warning-strong': `text-color-content-utility-warning-strong`,
  'warning-subtle': `text-color-content-utility-warning-subtle`,
  'success-strong': `text-color-content-utility-success-strong`,
  'success-subtle': `text-color-content-utility-success-subtle`,
  'info-strong': `text-color-content-utility-info-strong`,
  'info-subtle': `text-color-content-utility-info-subtle`
};

const transformClassMap: Record<Exclude<HeadingTransform, 'inherit'>, string> = {
  normal: `normal-case`,
  uppercase: `uppercase`,
  lowercase: `lowercase`,
  capitalize: `capitalize`
};

const presetSizeClassMap: Record<HeadingTag, string> = {
  h1: `text-3xl`,
  h2: `text-2xl`,
  h3: `text-xl`,
  h4: `text-xl`,
  h5: `text-lg`,
  h6: `text-base`
};

const presetWeightClassMap: Record<HeadingTag, string> = {
  h1: `font-bold`,
  h2: `font-bold`,
  h3: `font-extrabold`,
  h4: `font-bold`,
  h5: `font-bold`,
  h6: `font-bold`
};

const italicClasses = `italic`;
const truncateClasses = `truncate`;
const noMarginClasses = `m-0`;

export const Heading = React.forwardRef<HTMLHeadingElement, HeadingProps>(
  (
    {
      as = 'h2',
      size = 'auto',
      weight = 'auto',
      align = 'inherit',
      color = 'default',
      transform = 'inherit',
      italic = false,
      truncate = false,
      noMargin = true,
      className,
      children,
      ...rest
    },
    ref
  ) => {
    const sizeClassName = size === 'inherit' || size === 'auto' ? undefined : sizeClassMap[size];
    const weightClassName =
      weight === 'inherit' || weight === 'auto' ? undefined : weightClassMap[weight];
    const presetSizeClassName = size === 'auto' ? presetSizeClassMap[as] : undefined;
    const presetWeightClassName = weight === 'auto' ? presetWeightClassMap[as] : undefined;
    const alignClassName = align === 'inherit' ? undefined : alignClassMap[align];
    const colorClassName = color === 'inherit' ? undefined : colorClassMap[color];
    const transformClassName = transform === 'inherit' ? undefined : transformClassMap[transform];

    const rootClassName = collapseWhitespace(
      composeClasses(
        presetSizeClassName,
        presetWeightClassName,
        sizeClassName,
        weightClassName,
        alignClassName,
        colorClassName,
        transformClassName,
        italic ? italicClasses : undefined,
        truncate ? truncateClasses : undefined,
        noMargin ? noMarginClasses : undefined,
        className
      )
    );

    const Component = as;

    return (
      <Component ref={ref} className={rootClassName} {...rest}>
        {children}
      </Component>
    );
  }
);

Heading.displayName = 'Heading';
