// packages/core/src/icons/LocationIcon/LocationIcon.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: LocationIcon renders a location glyph SVG supporting decorative or labeled usage with optional title and color props

import * as React from 'react';

export interface LocationIconProps extends React.SVGAttributes<SVGSVGElement> {
  decorative?: boolean;
  title?: string;
  titleId?: string;
  color?: string;
}

type LocationIconElement = SVGSVGElement;

export const LocationIcon = React.forwardRef<LocationIconElement, LocationIconProps>(
  (
    {
      decorative = true,
      width = '20px',
      height = '20px',
      title,
      titleId: providedTitleId,
      color = 'currentColor',
      className,
      'aria-labelledby': ariaLabelledby,
      ...rest
    },
    ref
  ) => {
    const generatedTitleId = React.useId();
    const resolvedTitleId = title ? (providedTitleId ?? generatedTitleId) : undefined;

    const computedAriaHidden = decorative ? 'true' : undefined;
    const computedRole = decorative ? undefined : 'img';
    const computedAriaLabelledby =
      !decorative && title && resolvedTitleId ? resolvedTitleId : ariaLabelledby;

    return (
      <svg
        ref={ref}
        {...rest}
        className={className}
        viewBox="0 0 20 20"
        width={width}
        height={height}
        fill={color}
        aria-hidden={computedAriaHidden}
        role={computedRole}
        aria-labelledby={computedAriaLabelledby}
      >
        {!decorative && title ? <title id={resolvedTitleId}>{title}</title> : null}
        <g transform="scale(0.0208333333,0.0208333333) translate(0,960)">
          <path d="M480.21-477.61q30.99 0 52.58-21.81 21.6-21.81 21.6-52.79 0-30.99-21.81-52.58-21.81-21.6-52.79-21.6-30.99 0-52.58 21.81-21.6 21.81-21.6 52.79 0 30.99 21.81 52.58 21.81 21.6 52.79 21.6ZM480-87.87q-160.8-133.5-240.47-246.54-79.66-113.05-79.66-215.55 0-137.28 91.45-229.72 91.45-92.45 228.18-92.45 136.73 0 228.68 92.45 91.95 92.44 91.95 229.72 0 102.5-79.15 215.1T480-87.87Z" />
        </g>
      </svg>
    );
  }
);

LocationIcon.displayName = 'LocationIcon';
