// packages/core/src/icons/LocationIcon/LocationIcon.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Storybook stories for LocationIcon showcasing decorative default and non-decorative role=img usage with color/className controls.

import type { Meta, StoryObj } from '@storybook/react';
import { LocationIcon, LocationIconProps } from './LocationIcon';

const meta: Meta<LocationIconProps> = {
  title: 'Icons/LocationIcon',
  component: LocationIcon,
  args: {
    decorative: true,
    color: 'currentColor'
  },
  argTypes: {
    decorative: { control: 'boolean' },
    title: { control: 'text' },
    titleId: { control: 'text' },
    color: { control: 'color' },
    className: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<LocationIconProps>;

export const Default: Story = {};

export const NonDecorative: Story = {
  args: {
    decorative: false,
    title: 'Dismiss notification',
    titleId: 'close-icon-title'
  }
};
