// packages/core/src/components/client/FormElement/FormElement.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook story for FormElement documenting the shell wrapper with default label, info, and hint copy explaining Slot versus non-Slot behavior.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import Readme from './README.md?raw';
import { FormElement } from './FormElement';

const meta = {
  title: 'Client components/FormElement',
  component: FormElement,
  tags: ['autodocs'],
  parameters: {
    docs: {
      description: {
        component:
          'Shell-only wrapper. In non-Slot mode (asChild=false), the value slot renders a neutral wrapper and the child is not auto-wired with id/aria; use asChild=true to have FormElement pass id/aria/disabled into your control via Radix Slot.'
      },
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
} satisfies Meta<typeof FormElement>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {
    label: 'Form shell',
    info: 'This component provides label, info, focus ring, and messaging. Your control renders as children.',
    hint: 'Use asChild=true to have FormElement pass id/aria/disabled into your control.',
    asChild: false,
    children: (
      <p>
        Place your focusable control here. In Slot mode (asChild=true), FormElement wires id/aria/disabled
        into your child; styling the control remains the consumer’s responsibility.
      </p>
    )
  }
};
