// packages/core/src/components/client/ExpandableContent/ExpandableContent.test.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Tests ExpandableContent control wiring, uncontrolled and controlled toggle behavior, aria linkage, state-specific classes, transition cleanup, and DOM ordering.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ExpandableContent, type ExpandableContentProps } from './ExpandableContent';

const defaultText = 'Curabitur vitae nisl vitae nibh elementum tincidunt.';

const renderExpandableContent = (
  props?: Partial<ExpandableContentProps> & { children?: React.ReactNode }
) => {
  render(
    <ExpandableContent {...props}>{props?.children ?? defaultText.repeat(3)}</ExpandableContent>
  );

  const getControl = () => screen.getByRole('button', { name: 'Toggle expanded content' });

  const getContent = () => {
    const control = getControl();
    const controlsId = control.getAttribute('aria-controls');
    if (!controlsId) {
      throw new Error('IconButton aria-controls attribute was not set.');
    }
    const element = document.getElementById(controlsId);
    if (!element) {
      throw new Error('Expandable content region was not found.');
    }
    return element;
  };

  return { getControl, getContent };
};

describe('ExpandableContent', () => {
  it('renders content slot', () => {
    renderExpandableContent();
    expect(screen.getByText(defaultText, { exact: false })).toBeInTheDocument();
  });

  it('renders control button', () => {
    renderExpandableContent();
    expect(screen.getByRole('button', { name: 'Toggle expanded content' })).toBeInTheDocument();
  });

  describe('uncontrolled toggle', () => {
    it('sets aria-expanded to true after click', async () => {
      const { getControl } = renderExpandableContent();
      const control = getControl();
      const user = userEvent.setup();
      await user.click(control);
      expect(control).toHaveAttribute('aria-expanded', 'true');
    });

    it('updates content data-state to open after click', async () => {
      const { getControl, getContent } = renderExpandableContent();
      const control = getControl();
      const user = userEvent.setup();
      await user.click(control);
      const content = getContent();
      expect(content.getAttribute('data-state')).toBe('open');
    });
  });

  describe('controlled mode', () => {
    it('calls onExpandedChange with next state', async () => {
      const handleExpandedChange = jest.fn();
      const { getControl } = renderExpandableContent({
        expanded: false,
        onExpandedChange: handleExpandedChange
      });
      const control = getControl();
      const user = userEvent.setup();
      await user.click(control);
      expect(handleExpandedChange).toHaveBeenCalledWith(true);
    });

    it('does not change aria-expanded without external state update', async () => {
      const { getControl } = renderExpandableContent({
        expanded: false,
        onExpandedChange: () => {}
      });
      const control = getControl();
      const user = userEvent.setup();
      await user.click(control);
      expect(control).toHaveAttribute('aria-expanded', 'false');
    });
  });

  it('links aria-controls to the content region id', () => {
    const { getControl, getContent } = renderExpandableContent();
    const control = getControl();
    const content = getContent();
    expect(control.getAttribute('aria-controls')).toBe(content.id);
  });

  describe('class assertions', () => {
    it('applies closed-state clamping classes when collapsed', () => {
      const { getContent } = renderExpandableContent();
      const content = getContent();
      expect(content).toHaveClass('data-[state=closed]:mh-18.75');
    });

    it('applies line clamp class when collapsed', () => {
      const { getContent } = renderExpandableContent();
      const content = getContent();
      expect(content).toHaveClass('data-[state=closed]:line-clamp-3');
    });

    it('applies rotate-0 class to control in closed state', () => {
      const { getControl } = renderExpandableContent();
      const control = getControl();
      const wrapper = control.parentElement;
      if (!wrapper) {
        throw new Error('Control wrapper not found.');
      }
      expect(wrapper).toHaveClass('peer-data-[state=closed]:[&>button]:rotate-0');
    });

    it('omits closed-state classes when expanded', () => {
      const { getContent } = renderExpandableContent({ defaultExpanded: true });
      const content = getContent();
      expect(content).not.toHaveClass('data-[state=closed]:mh-75');
    });

    it('omits line clamp class when expanded', () => {
      const { getContent } = renderExpandableContent({ defaultExpanded: true });
      const content = getContent();
      expect(content).not.toHaveClass('data-[state=closed]:line-clamp-3');
    });

    it('applies rotate-180 class to control when expanded', () => {
      const { getControl } = renderExpandableContent({ defaultExpanded: true });
      const control = getControl();
      const wrapper = control.parentElement;
      if (!wrapper) {
        throw new Error('Control wrapper not found.');
      }
      expect(wrapper).toHaveClass('peer-data-[state=open]:[&>button]:rotate-180');
    });
  });

  it('clears inline maxHeight after expand transitionend', async () => {
    const { getControl, getContent } = renderExpandableContent();
    const control = getControl();
    const user = userEvent.setup();
    await user.click(control);
    const content = getContent();

    const result = (() => {
      const before = content.style.maxHeight !== '';
      act(() => {
        content.dispatchEvent(new Event('transitionend'));
      });
      const after = content.style.maxHeight === '';
      return [before, after];
    })();

    expect(result).toEqual([true, true]);
  });

  it('applies inline overrides and animates maxHeight on collapse', async () => {
    const { getControl, getContent } = renderExpandableContent({ defaultExpanded: true });
    const control = getControl();
    const content = getContent();
    const user = userEvent.setup();

    const collapseChecks = await (async () => {
      const initialExpanded = control.getAttribute('aria-expanded');
      await user.click(control);
      const inlineValues = {
        clamp: content.style.webkitLineClamp,
        display: content.style.display,
        maxHeight: content.style.maxHeight
      } as const;
      act(() => {
        content.dispatchEvent(new Event('transitionend'));
      });
      const finalExpanded = control.getAttribute('aria-expanded');
      return { initialExpanded, inlineValues, finalExpanded };
    })();

    const result = [
      collapseChecks.initialExpanded,
      collapseChecks.inlineValues.clamp,
      collapseChecks.inlineValues.display,
      typeof collapseChecks.inlineValues.maxHeight === 'string',
      collapseChecks.finalExpanded
    ];

    expect(result).toEqual(['true', 'unset', 'block', true, 'false']);
  });

  it('renders content before control in the DOM', () => {
    const { getContent } = renderExpandableContent();
    const content = getContent();
    const root = content.parentElement;
    if (!root) {
      throw new Error('ExpandableContent root wrapper not found.');
    }
    expect(root.firstElementChild === content).toBe(true);
  });
});
