// packages/core/src/components/server/MediaCard/MediaCard.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Stories for MediaCard illustrating base layout, media/label metadata, control overlay, and focusable versus link variants.

import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { MediaCard, MediaCardProps } from './MediaCard';
import { MediaControl } from '../../client/MediaControl';
import { EventIcon } from '../../../icons';

const meta: Meta<MediaCardProps> = {
  title: 'Server components/MediaCard',
  component: MediaCard,
  args: {
    subtitle: 'Episode 5 · 48 min',
    title: 'The Design Systems Podcast',
    labels: [
      {
        label: 'Design',
        icon: <EventIcon />
      },
      {
        label: 'Research',
        icon: <EventIcon />
      }
    ]
  }
};

export default meta;

type Story = StoryObj<MediaCardProps>;

export const Default: Story = {
  args: {
    subtitle: 'Episode 5 · 48 min',
    title: 'The Design Systems Podcast',
    labels: [
      {
        label: 'Design',
        icon: <EventIcon />
      },
      {
        label: 'Research',
        icon: <EventIcon />
      }
    ],
    imgSrc: 'https://picsum.photos/seed/doxyz-media/400/400',
    imgAlt: 'Podcast artwork',
    control: <MediaControl ariaLabelPlay="Play media" ariaLabelPause="Pause media" />
  }
};

export const NoImage: Story = {
  args: {
    subtitle: 'Episode 5 · 48 min',
    title: 'The Design Systems Podcast',
    labels: [
      {
        label: 'Design',
        icon: <EventIcon />
      },
      {
        label: 'Research',
        icon: <EventIcon />
      }
    ],
    control: <MediaControl ariaLabelPlay="Play media" ariaLabelPause="Pause media" />
  }
};
