'use client';

// packages/core/src/components/Stepper/Stepper.tsx
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../utilities';

type NavProps = Omit<React.ComponentPropsWithoutRef<'nav'>, 'role' | 'children'>;

export interface StepperProps extends NavProps {
  steps: number;
  activeStep: number;
  onStepChange?: (index: number) => void;
}

const containerClasses = `flex items-center gap-4 select-none transition-colors`;
const stepClasses = `flex flex-col items-center relative`;
const indicatorClasses = `
  size-8 rounded-full flex items-center justify-center font-bold border p-2 transition-colors
  focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2
  focus-visible:ring-color-focus-ring focus-visible:ring-offset-color-background-default
  data-[step-status=active]:bg-transparent data-[step-status=active]:text-color-content-brand
  data-[step-status=active]:border-color-content-brand
  data-[step-status=completed]:bg-color-content-brand data-[step-status=completed]:text-color-background-default
  data-[step-status=completed]:border-color-content-brand
  data-[step-status=upcoming]:bg-transparent data-[step-status=upcoming]:text-color-content-weak
  data-[step-status=upcoming]:border-color-background-default
`;
const labelClasses = `mt-1 text-sm text-center text-color-content-default`;
const railClasses = `
  flex-1 h-px transition-colors bg-color-background-default
  data-[rail-status=default]:bg-color-background-default
  data-[rail-status=full]:bg-color-content-brand
  data-[rail-status=partial]:bg-color-content-brand/50
`;

export const Stepper = React.forwardRef<React.ElementRef<'nav'>, StepperProps>(
  ({ steps, activeStep, onStepChange, className, ...rest }, ref) => {
    const isInteractive = typeof onStepChange === 'function';

    const containerRole = isInteractive ? 'tablist' : 'list';

    const containerClassName = collapseWhitespace(composeClasses(containerClasses, className));
    const stepClassName = collapseWhitespace(composeClasses(stepClasses));
    const indicatorClassName = collapseWhitespace(composeClasses(indicatorClasses));
    const labelClassName = collapseWhitespace(composeClasses(labelClasses));
    const railClassName = collapseWhitespace(composeClasses(railClasses));

    const handleStepClick = React.useCallback(
      (index: number) => {
        if (onStepChange) {
          onStepChange(index);
        }
      },
      [onStepChange]
    );

    const stepsArray = React.useMemo(() => Array.from({ length: steps }, (_, index) => index), [steps]);

    return (
      <nav
        {...rest}
        ref={ref}
        className={containerClassName}
        role={containerRole}
        aria-orientation={isInteractive ? 'horizontal' : undefined}
        data-slot="container"
      >
        {stepsArray.map(index => {
          const stepStatus =
            index < activeStep ? 'completed' : index === activeStep ? 'active' : 'upcoming';
          const railStatus =
            index === 0
              ? undefined
              : index < activeStep
              ? 'full'
              : index === activeStep
              ? 'partial'
              : 'default';

          const rail =
            railStatus !== undefined ? (
              <div
                key={`rail-${index}`}
                className={railClassName}
                data-slot="rail"
                data-rail-status={railStatus}
                aria-hidden="true"
              />
            ) : null;

          if (isInteractive) {
            return (
              <React.Fragment key={`step-${index}`}>
                {rail}
                <button
                  type="button"
                  role="tab"
                  onClick={() => handleStepClick(index)}
                  aria-current={index === activeStep ? ('step' as const) : undefined}
                  aria-selected={index === activeStep}
                  tabIndex={index === activeStep ? 0 : -1}
                  className={stepClassName}
                  data-slot="step"
                  data-step-status={stepStatus}
                >
                  <span
                    className={indicatorClassName}
                    data-slot="indicator"
                    data-step-status={stepStatus}
                    aria-hidden="true"
                  >
                    {index + 1}
                  </span>
                  <span className={labelClassName} data-slot="label">
                    {`Step ${index + 1}`}
                  </span>
                </button>
              </React.Fragment>
            );
          }

          return (
            <React.Fragment key={`step-${index}`}>
              {rail}
              <div className={stepClassName} role="listitem" data-slot="step" data-step-status={stepStatus}>
                <span
                  className={indicatorClassName}
                  data-slot="indicator"
                  data-step-status={stepStatus}
                  aria-hidden="true"
                >
                  {index + 1}
                </span>
                <span className={labelClassName} data-slot="label">
                  {`Step ${index + 1}`}
                </span>
              </div>
            </React.Fragment>
          );
        })}
      </nav>
    );
  }
);

Stepper.displayName = 'Stepper';
