import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Dialog, type DialogProps } from './Dialog';

const TRIGGER_LABEL = 'Launch dialog';
const DialogContent = () => (
  <div>
    <h2>Dialog heading</h2>
    <p>This is the dialog body content.</p>
  </div>
);

const renderDialog = (props?: Partial<DialogProps>) => {
  render(
    <Dialog {...props} trigger={<button type="button">{TRIGGER_LABEL}</button>}>
      <DialogContent />
    </Dialog>
  );
};

const openDialog = async (props?: Partial<DialogProps>) => {
  renderDialog(props);
  const trigger = screen.getByRole('button', { name: TRIGGER_LABEL });
  const user = userEvent.setup();
  await user.click(trigger);
  const dialog = await screen.findByRole('dialog');
  return { dialog, user };
};

describe('Dialog', () => {
  it('opens on trigger click and closes via close control', async () => {
    const { dialog, user } = await openDialog();
    const closeButton = screen.getByRole('button', { name: 'Close dialog' });
    await user.click(closeButton);
    await waitFor(() => {
      if (screen.queryByRole('dialog')) {
        throw new Error('Dialog remained open');
      }
    });
    const result = [dialog.getAttribute('role'), screen.queryByRole('dialog') === null];
    expect(result).toEqual(['dialog', true]);
  });

  it('renders provided closeIcon node', async () => {
    await openDialog({ closeIcon: <span data-testid="custom-close" /> });
    const node = screen.getByTestId('custom-close');
    const result = Boolean(node);
    expect(result).toBe(true);
  });

  it.each([
    ['sm', 'w-600'],
    ['md', 'max-w-1300'],
    ['lg', 'max-w-1600']
  ] as const)('applies %s size classes', async (size, expectedClass) => {
    const { dialog } = await openDialog({ size });
    const hasClass = dialog.classList.contains(expectedClass);
    expect(hasClass).toBe(true);
  });

  it('renders navigation controls when enabled', async () => {
    await openDialog({ hasNavigation: true });
    const previous = screen.getByRole('button', { name: 'Previous' });
    const next = screen.getByRole('button', { name: 'Next' });
    const result = [Boolean(previous), Boolean(next)];
    expect(result).toEqual([true, true]);
  });

  it('renders provided navigation icon nodes when supplied', async () => {
    await openDialog({
      hasNavigation: true,
      controlLeftIcon: <span data-testid="custom-left" />,
      controlRightIcon: <span data-testid="custom-right" />
    });
    const result = [
      Boolean(screen.getByTestId('custom-left')),
      Boolean(screen.getByTestId('custom-right'))
    ];
    expect(result).toEqual([true, true]);
  });

  it('hides navigation controls when disabled', async () => {
    await openDialog({ hasNavigation: false });
    const previous = screen.queryByRole('button', { name: 'Previous' });
    const next = screen.queryByRole('button', { name: 'Next' });
    const result = [previous === null, next === null];
    expect(result).toEqual([true, true]);
  });

  it('invokes navigation callbacks once per click', async () => {
    const handleLeft = jest.fn();
    const handleRight = jest.fn();
    const { user } = await openDialog({
      hasNavigation: true,
      onControlLeftClick: handleLeft,
      onControlRightClick: handleRight
    });
    await user.click(screen.getByRole('button', { name: 'Previous' }));
    await user.click(screen.getByRole('button', { name: 'Next' }));
    const result = [handleLeft.mock.calls.length, handleRight.mock.calls.length];
    expect(result).toEqual([1, 1]);
  });

  it('applies overlay classes from the style map', async () => {
    await openDialog();
    const overlay = document.querySelector('[data-radix-dialog-overlay]');
    const result = [Boolean(overlay), overlay?.classList.contains('bg-modal-dark/50') ?? false];
    expect(result).toEqual([true, true]);
  });
});
