// packages/core/src/components/server/NavigationContainer/NavigationContainer.test.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Tests NavigationContainer rendering behavior and ensures styleMap tokens merge with custom className.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import { NavigationContainer } from './NavigationContainer';

describe('NavigationContainer', () => {
  it('renders a div and exposes children', () => {
    render(
      <NavigationContainer data-testid="navigation-container">
        <span>Child</span>
      </NavigationContainer>
    );

    const element = screen.getByTestId('navigation-container');

    expect({
      tag: element.tagName,
      text: element.textContent?.trim()
    }).toEqual({ tag: 'DIV', text: 'Child' });
  });

  it('merges caller className while preserving styleMap tokens', () => {
    render(
      <NavigationContainer data-testid="navigation-container" className="custom-class">
        <span>Child</span>
      </NavigationContainer>
    );

    const element = screen.getByTestId('navigation-container');
    const flags = {
      px16: element.className.includes('px-4'),
      lgPx112: element.className.includes('lg:px-28'),
      py24: element.className.includes('py-6'),
      lgPy56: element.className.includes('lg:py-14'),
      background: element.className.includes('bg-background-none'),
      custom: element.className.includes('custom-class')
    };

    expect(flags).toEqual({
      px16: true,
      lgPx112: true,
      py24: true,
      lgPy56: true,
      background: true,
      custom: true
    });
  });
});
