// packages/core/src/components/server/NavigationContainer/NavigationContainer.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Tests NavigationContainer rendering behavior and ensures styleMap tokens merge with custom className.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import { NavigationContainer } from './NavigationContainer';

describe('NavigationContainer', () => {
  it('renders a div and exposes children', () => {
    render(
      <NavigationContainer data-testid="navigation-container">
        <span>Child</span>
      </NavigationContainer>
    );

    const element = screen.getByTestId('navigation-container');

    expect({
      tag: element.tagName,
      text: element.textContent?.trim()
    }).toEqual({ tag: 'DIV', text: 'Child' });
  });

  it('merges styleMap tokens with custom className', () => {
    render(
      <NavigationContainer data-testid="navigation-container" className="custom-nav">
        Content
      </NavigationContainer>
    );

    const className = screen.getByTestId('navigation-container').className;
    const tokens = ['px-16', 'lg:px112', 'py-24', 'lg:py-56', 'bg-background-none'];

    expect({
      hasTokens: tokens.every((token) => className.includes(token)),
      hasCustom: className.includes('custom-nav')
    }).toEqual({ hasTokens: true, hasCustom: true });
  });
});
