// packages/core/src/components/server/NavigationContainer/NavigationContainer.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: NavigationContainer wraps children in a div that applies navigation padding/background tokens and forwards HTML div props.

import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../../utilities';

export interface NavigationContainerProps extends React.HTMLAttributes<HTMLDivElement> {
  className?: string;
}

const baseClasses = `px-4 lg:px-28 py-6 lg:py-14 bg-background-none`;

export const NavigationContainer = (props: NavigationContainerProps) => {
  const { className, children, ...rest } = props;

  const rootClassName = collapseWhitespace(composeClasses(baseClasses, className));

  return (
    <div {...rest} className={rootClassName} data-slot="container">
      {children}
    </div>
  );
};

NavigationContainer.displayName = 'NavigationContainer';
