// packages/core/src/components/client/Checkbox/Checkbox.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Stories for Checkbox using a custom render to surface onCheckedChange actions while exposing controls for label, hint, name, value, disabled, and required states.

import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { Checkbox, CheckboxProps } from './Checkbox';

const meta: Meta<CheckboxProps> = {
  title: 'Client components/Checkbox',
  component: Checkbox,
  argTypes: {
    onCheckedChange: { action: 'checked change' }
  },
  args: {
    label: 'Receive updates',
    disabled: false,
    required: false
  }
};

export default meta;

type Story = StoryObj<CheckboxProps>;

const renderCheckbox = (args: CheckboxProps): React.ReactElement => {
  const { onCheckedChange, ...rest } = args;

  return (
    <Checkbox
      {...rest}
      onCheckedChange={value => {
        onCheckedChange?.(value);
      }}
    />
  );
};

export const Default: Story = {
  args: {
    hint: undefined,
    name: undefined,
    value: undefined
  },
  render: args => renderCheckbox(args)
};