// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { Checkbox, CheckboxProps } from '@doxyz-ui/core/client-components';

const meta: Meta<CheckboxProps> = {
  title: 'Client components/Checkbox',
  component: Checkbox,
  argTypes: {
    onCheckedChange: { action: 'checked change' }
  },
  args: {
    label: 'Receive updates',
    disabled: false,
    required: false
  }
};

export default meta;

type Story = StoryObj<CheckboxProps>;

const renderCheckbox = (args: CheckboxProps): React.ReactElement => {
  const { onCheckedChange, ...rest } = args;

  return (
    <Checkbox
      {...rest}
      onCheckedChange={value => {
        onCheckedChange?.(value);
      }}
    />
  );
};

export const Default: Story = {
  args: {
    hint: undefined,
    name: undefined,
    value: undefined
  },
  render: args => renderCheckbox(args)
};