'use client';

// packages/core/src/components/client/Input/Input.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Input wraps FormElement to render a labeled field with optional icons, merges aria wiring, and composes slot-based input row.

import * as React from 'react';
import { composeClasses } from '../../../utilities/composeClasses/composeClasses';
import { collapseWhitespace } from '../../../utilities/collapseWhitespace/collapseWhitespace';
import { FormElement, type FormElementProps } from '../FormElement';

const inputRowClasses = `
  inline-flex items-center gap-2 py-(--spacing-1_5) px-(--spacing-2_5)
`;

const startIconClasses = `
  inline-flex items-center gap-2 shrink-0 [&>svg]:size-4 py-(--spacing-1_5) inline-flex text-color-content-default
`;

const inputClasses = `
  grow bg-transparent outline-none text-color-content-default placeholder-color-content-weak border-none py-(--spacing-1_5) focus:placeholder:opacity-0
`;

const endIconClasses = `
  shrink-0 [&>svg]:size-4 py-(--spacing-1_5) inline-flex text-color-content-default
`;

const invalidStateClasses = `
  data-[invalid=true]:[&_[data-slot=input]]:border-comp-form-color-border-utility-danger
`;

type NativeInputProps = React.InputHTMLAttributes<HTMLInputElement>;
type WrapperProps = Omit<FormElementProps, 'children' | 'asChild' | 'className' | 'id'> &
  Pick<NativeInputProps, 'required' | 'readOnly'>;
type WrapperOnlyProps = Omit<WrapperProps, keyof NativeInputProps>;
type ForwardedInputProps = NativeInputProps & {
  ref?: React.Ref<HTMLInputElement>;
};

type InputFieldProps = Omit<React.HTMLAttributes<HTMLDivElement>, 'children'> & {
  disabled?: boolean;
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  startIconClassName: string;
  inputClassName: string;
  endIconClassName: string;
  inputProps: ForwardedInputProps;
};

const InputField = React.forwardRef<HTMLDivElement, InputFieldProps>(
  (
    {
      startIcon,
      endIcon,
      startIconClassName,
      inputClassName,
      endIconClassName,
      inputProps,
      disabled,
      className,
      ...rest
    },
    ref
  ) => {
    const {
      id,
      ['aria-label']: ariaLabel,
      ['aria-describedby']: ariaDescribedBy,
      ['aria-invalid']: ariaInvalid,
      ...slotContainerProps
    } = rest;

    const wrapperClassName = collapseWhitespace(composeClasses(inputRowClasses, className));

    const { ref: inputRef, ...restInputProps } = inputProps;

    const {
      ['aria-label']: inputAriaLabel,
      ['aria-describedby']: inputAriaDescribedBy,
      ['aria-invalid']: inputAriaInvalid,
      ...otherInputProps
    } = restInputProps;

    const describedBy =
      [ariaDescribedBy, inputAriaDescribedBy]
        .filter((value): value is string => Boolean(value))
        .join(' ') || undefined;

    const resolvedInputProps: NativeInputProps = {
      ...otherInputProps,
      id,
      disabled,
      'aria-label': ariaLabel ?? inputAriaLabel,
      'aria-describedby': describedBy,
      'aria-invalid': ariaInvalid ?? inputAriaInvalid
    };

    return (
      <div
        {...slotContainerProps}
        ref={ref}
        className={wrapperClassName}
        data-slot="input"
        data-disabled={disabled ? 'true' : undefined}
        data-invalid={ariaInvalid ? 'true' : undefined}
      >
        {startIcon ? (
          <span className={startIconClassName} data-slot="startIcon" aria-hidden="true">
            {startIcon}
          </span>
        ) : null}
        <input {...resolvedInputProps} ref={inputRef} className={inputClassName} />
        {endIcon ? (
          <span className={endIconClassName} data-slot="endIcon" aria-hidden="true">
            {endIcon}
          </span>
        ) : null}
      </div>
    );
  }
);

InputField.displayName = 'InputField';

export interface InputProps extends WrapperOnlyProps, Omit<NativeInputProps, 'children' | 'id'> {
  startIcon?: React.ReactNode;
  endIcon?: React.ReactNode;
  className?: string;
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(function Input(props, ref) {
  const { startIcon, endIcon, className, ...restProps } = props;

  const {
    label,
    ariaLabel,
    hint,
    error,
    info,
    required,
    readOnly,
    disabled: disabledProp,
    ...nativeInputRest
  } = restProps;

  const disabled = disabledProp ?? false;

  const formElementProps: WrapperProps = {
    label,
    ariaLabel,
    hint,
    error,
    info,
    required,
    readOnly,
    disabled
  };

  const nativeInputProps: NativeInputProps = {
    ...nativeInputRest,
    required,
    readOnly,
    disabled
  };

  const inputRowClassName = collapseWhitespace(
    composeClasses(inputRowClasses, invalidStateClasses, className)
  );
  const startIconClassName = collapseWhitespace(composeClasses(startIconClasses));
  const inputClassName = collapseWhitespace(composeClasses(inputClasses));
  const endIconClassName = collapseWhitespace(composeClasses(endIconClasses));

  const inputPropsWithRef: ForwardedInputProps = {
    ...nativeInputProps,
    ref
  };

  return (
    <FormElement {...formElementProps} asChild>
      <InputField
        startIcon={startIcon}
        endIcon={endIcon}
        startIconClassName={startIconClassName}
        inputClassName={inputClassName}
        endIconClassName={endIconClassName}
        inputProps={inputPropsWithRef}
        className={inputRowClassName}
        disabled={disabled}
        data-disabled={disabled ? 'true' : undefined}
      />
    </FormElement>
  );
});

Input.displayName = 'Input';
