// packages/core/src/components/server/TextLink/TextLink.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Checks TextLink link rendering, variant styling, start and end icon wrappers, disabled aria-disabled handling, focus ring tokens, and default variant behavior.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import type { TextLinkProps } from './TextLink';
import { TextLink } from './TextLink';

describe('TextLink', () => {
  const renderLink = (props?: Partial<TextLinkProps>) =>
    render(<TextLink href="#example" label="Visit example" variant="brand" {...props} />);

  describe('default parameter initializers', () => {
    it('uses default variant when not provided', () => {
      render(<TextLink href="#example" label="Visit example" />);
      const link = screen.getByRole('link', { name: 'Visit example' });
      expect(link).toHaveClass('text-color-content-brand');
    });

    it('disabled defaults to false (no aria-disabled)', () => {
      render(<TextLink href="#example" label="Visit example" />);
      const link = screen.getByRole('link', { name: 'Visit example' });
      expect(link).not.toHaveAttribute('aria-disabled');
    });
  });

  it('renders link with visible label', () => {
    renderLink();
    expect(screen.getByRole('link', { name: 'Visit example' })).toBeInTheDocument();
  });

  describe('variants', () => {
    const variantCases: ReadonlyArray<[TextLinkProps['variant'], string]> = [
      ['brand', 'text-color-content-brand'],
      ['strong', 'text-color-content-default'],
      ['subtle', 'text-color-content-weak'],
      ['inverted', 'text-comp-button-primary-color-content-default']
    ];

    it.each(variantCases)('applies %s variant classes', (variant, classToken) => {
      renderLink({ variant });
      const link = screen.getByRole('link', { name: 'Visit example' });
      expect(link).toHaveClass(classToken);
    });
  });

  it('renders start icon with aria-hidden', () => {
    renderLink({ startIcon: <span data-testid="start-icon">*</span> });
    expect(screen.getByTestId('start-icon').parentElement).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders end icon with aria-hidden', () => {
    renderLink({ endIcon: <span data-testid="end-icon">*</span> });
    expect(screen.getByTestId('end-icon').parentElement).toHaveAttribute('aria-hidden', 'true');
  });

  describe('slot rendering (absence cases)', () => {
    it('does not render start icon wrapper when startIcon is not provided', () => {
      renderLink();
      const link = screen.getByRole('link', { name: 'Visit example' });
      expect(link.querySelector('span[aria-hidden="true"]')).toBeNull();
    });

    it('renders label within a span when no icons are provided', () => {
      renderLink();
      const link = screen.getByRole('link', { name: 'Visit example' });
      const labelSpan = link.querySelector('span');
      expect(labelSpan?.textContent).toBe('Visit example');
    });

    it('does not render end icon wrapper when endIcon is not provided', () => {
      renderLink();
      const link = screen.getByRole('link', { name: 'Visit example' });
      expect(link.querySelector('span[aria-hidden="true"]')).toBeNull();
    });
  });

  describe('label & icons (both present)', () => {
    it('renders label span when both icons are provided', () => {
      render(
        <TextLink
          href="#example"
          label="Visit example"
          startIcon={<span data-testid="start-icon">*</span>}
          endIcon={<span data-testid="end-icon">*</span>}
        />
      );
      const link = screen.getByRole('link', { name: 'Visit example' });
      const spans = Array.from(link.querySelectorAll('span'));
      const labelSpan = spans.find(span => span.textContent === 'Visit example');
      expect(labelSpan).toBeTruthy();
    });

    it('renders start icon wrapper with aria-hidden when both icons are provided', () => {
      render(
        <TextLink
          href="#example"
          label="Visit example"
          startIcon={<span data-testid="start-icon">*</span>}
          endIcon={<span data-testid="end-icon">*</span>}
        />
      );
      expect(screen.getByTestId('start-icon').parentElement).toHaveAttribute('aria-hidden', 'true');
    });

    it('renders end icon wrapper with aria-hidden when both icons are provided', () => {
      render(
        <TextLink
          href="#example"
          label="Visit example"
          startIcon={<span data-testid="start-icon">*</span>}
          endIcon={<span data-testid="end-icon">*</span>}
        />
      );
      expect(screen.getByTestId('end-icon').parentElement).toHaveAttribute('aria-hidden', 'true');
    });
  });

  it('marks link as disabled via aria-disabled', () => {
    renderLink({ disabled: true });
    expect(screen.getByRole('link', { name: 'Visit example' })).toHaveAttribute(
      'aria-disabled',
      'true'
    );
  });

  it('includes focus ring token class', () => {
    renderLink();
    expect(screen.getByRole('link', { name: 'Visit example' })).toHaveClass(
      'focus-visible:ring-comp-border-focus-ring'
    );
  });
});
