// packages/core/src/components/server/Chip/Chip.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Stories for Chip demonstrating default label, optional icon slot, long label truncation, and aria-label override.

import type { Meta, StoryObj } from '@storybook/react';
import { Markdown } from '@storybook/addon-docs/blocks';
import * as React from 'react';
import { EventIcon } from '../../../icons';
import { Chip, type ChipProps } from './Chip';
import Readme from './README.md?raw';

const meta: Meta<ChipProps> = {
  title: 'Server components/Chip',
  component: Chip,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  },
  args: {
    label: 'General Admission',
    icon: undefined,
    ariaLabel: undefined
  }
};

export default meta;

type Story = StoryObj<ChipProps>;

export const Default: Story = {
  args: {}
};

export const WithIcon: Story = {
  args: {
    icon: <EventIcon />
  }
};

export const LongLabel: Story = {
  args: {
    label: 'General Admission • Upper Mezzanine North Entrance Section 342'
  }
};

export const WithAriaLabel: Story = {
  args: {
    label: 'GA',
    ariaLabel: 'General Admission'
  }
};
