// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import { CheckboxGroup, CheckboxGroupProps } from './CheckboxGroup';

const baseChoices = [
  { label: 'Email notifications' },
  { label: 'SMS alerts' },
  { label: 'Push notifications' }
];

const meta: Meta<CheckboxGroupProps> = {
  title: 'Client components/CheckboxGroup',
  component: CheckboxGroup,
  argTypes: {
    onCheckedChange: { action: 'checked change' },
    choices: { control: false }
  },
  args: {
    label: 'Notification preferences',
    choices: baseChoices
  }
};

export default meta;

type Story = StoryObj<CheckboxGroupProps>;

export const Default: Story = {};

export const WithHint: Story = {
  args: {
    hint: 'Select all options that apply to you.'
  }
};

export const WithInfo: Story = {
  args: {
    info: 'You can change these preferences at any time from your profile settings.'
  }
};

export const WithError: Story = {
  args: {
    error: 'Please choose at least one notification method.'
  }
};

export const NoLabelViaAria: Story = {
  args: {
    label: undefined,
    ariaLabel: 'Notification preferences (aria label)'
  }
};

export const ManyChoices: Story = {
  args: {
    choices: [
      { label: 'Email notifications' },
      { label: 'SMS alerts' },
      { label: 'Push notifications' },
      { label: 'Daily summary' },
      { label: 'Weekly digest' },
      { label: 'Product updates' },
      { label: 'Security alerts' }
    ]
  }
};