// packages/core/src/components/server/ScrollerRow/ScrollerRow.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Story rendering ScrollerRow with MediaCard children to demonstrate flex row layout usage.

import type { Meta, StoryObj } from '@storybook/react';
import { Markdown } from '@storybook/addon-docs/blocks';
import * as React from 'react';
import Readme from './README.md?raw';
import { ScrollerRow } from './ScrollerRow';
import { MediaCard } from '../MediaCard/MediaCard';
import { MediaControl } from '../../client/MediaControl';
import { EventIcon } from '../../../icons';

const meta: Meta<typeof ScrollerRow> = {
  title: 'Server components/ScrollerRow',
  component: ScrollerRow,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>,
      description: {
        component:
          'Layout row for Scroller compositions; applies flex gap-2 justify-between items-center.'
      }
    }
  }
};

export default meta;

type Story = StoryObj<typeof ScrollerRow>;

export const Default: Story = {
  render: () => (
    <ScrollerRow>
      <MediaCard
        subtitle="Episode 5 · 48 min"
        title="The Design Systems Podcast"
        labels={[
          { label: 'Design', icon: <EventIcon /> },
          { label: 'Research', icon: <EventIcon /> }
        ]}
        control={<MediaControl ariaLabelPlay="Play media" ariaLabelPause="Pause media" />}
      />
      <MediaCard
        subtitle="Season 2 · 35 min"
        title="Systems Thinking"
        labels={[
          { label: 'Design', icon: <EventIcon /> },
          { label: 'Research', icon: <EventIcon /> }
        ]}
        control={<MediaControl ariaLabelPlay="Play media" ariaLabelPause="Pause media" />}
      />
      <MediaCard
        subtitle="Trailer · 12 min"
        title="Design Debrief"
        labels={[
          { label: 'Design', icon: <EventIcon /> },
          { label: 'Research', icon: <EventIcon /> }
        ]}
        control={<MediaControl ariaLabelPlay="Play media" ariaLabelPause="Pause media" />}
      />
      <MediaCard
        subtitle="Bonus · 22 min"
        title="Accessibility Notes"
        labels={[
          { label: 'Design', icon: <EventIcon /> },
          { label: 'Research', icon: <EventIcon /> }
        ]}
        control={<MediaControl ariaLabelPlay="Play media" ariaLabelPause="Pause media" />}
      />
    </ScrollerRow>
  )
};
