// packages/core/src/components/server/ScrollerRow/ScrollerRow.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Tests ScrollerRow child rendering, className merging, attribute forwarding, and absence of roles.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import { ScrollerRow } from './ScrollerRow';

describe('ScrollerRow', () => {
  it('renders provided children', () => {
    render(<ScrollerRow>Row child</ScrollerRow>);
    expect(screen.getByText('Row child')).toBeInTheDocument();
  });

  it('merges base classes with a consumer className', () => {
    render(<ScrollerRow className="custom-class">Row</ScrollerRow>);
    const row = screen.getByText('Row');
    const tokens = row.className.split(' ').filter(Boolean);
    expect(tokens).toEqual(expect.arrayContaining(['flex', 'custom-class']));
  });

  it('forwards arbitrary data attributes', () => {
    render(<ScrollerRow data-test="example">Row attr</ScrollerRow>);
    const row = screen.getByText('Row attr');
    expect(row).toHaveAttribute('data-test', 'example');
  });

  it('does not set a role attribute', () => {
    render(<ScrollerRow>Row role</ScrollerRow>);
    const row = screen.getByText('Row role');
    expect(row).not.toHaveAttribute('role');
  });
});
