// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import { Tag, TagProps } from '@doxyz-ui/core/server-components';

const meta: Meta<TagProps> = {
  title: 'Server components/Tag',
  component: Tag,
  args: {
    label: 'Branch',
    variant: 'parent',
    isInteractive: false,
    isActive: false
  },
  argTypes: {
    variant: { control: { type: 'radio' }, options: ['parent', 'child'] },
    isInteractive: { control: 'boolean' },
    isActive: { control: 'boolean' },
    label: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<TagProps>;

export const Default: Story = {
  args: {}
};

export const InteractiveParent: Story = {
  args: {
    isInteractive: true
  }
};

export const InteractiveChild: Story = {
  args: {
    isInteractive: true,
    variant: 'child'
  }
};

export const ActiveParentInteractive: Story = {
  args: {
    isInteractive: true,
    isActive: true
  }
};

export const ActiveChildInteractive: Story = {
  args: {
    isInteractive: true,
    variant: 'child',
    isActive: true
  }
};