// packages/core/src/components/server/Tag/Tag.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories for Tag covering interactive parent/child variants, active state, non-interactive use, and cursor behavior.

import type { Meta, StoryObj } from '@storybook/react-vite';
import { Markdown } from '@storybook/addon-docs/blocks';
import { Tag, TagProps } from './Tag';
import Readme from './README.md?raw';

const meta: Meta<TagProps> = {
  title: 'Server components/Tag',
  component: Tag,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  },
  args: {
    label: 'Branch',
    variant: 'parent',
    isInteractive: false,
    isActive: false
  },
  argTypes: {
    variant: { control: { type: 'radio' }, options: ['parent', 'child'] },
    isInteractive: { control: 'boolean' },
    isActive: { control: 'boolean' },
    label: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<TagProps>;

export const Default: Story = {
  args: {}
};

export const InteractiveParent: Story = {
  args: {
    isInteractive: true
  }
};

export const InteractiveChild: Story = {
  args: {
    isInteractive: true,
    variant: 'child'
  }
};

export const ActiveParentInteractive: Story = {
  args: {
    isInteractive: true,
    isActive: true
  }
};

export const ActiveChildInteractive: Story = {
  args: {
    isInteractive: true,
    variant: 'child',
    isActive: true
  }
};
