// packages/core/src/icons/InfoIcon/InfoIcon.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Verifies InfoIcon decorative defaults, labeled role=img support, color prop passthrough, className merge, and generated title ids.

import { render, screen } from '@testing-library/react';
import { InfoIcon } from './InfoIcon';

describe('InfoIcon', () => {
  it('defaults to decorative and sets aria-hidden="true"', () => {
    render(<InfoIcon data-testid="icon" />);
    expect(screen.getByTestId('icon')).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders non-decorative icons with title as role="img" and aria-labelledby', () => {
    render(<InfoIcon decorative={false} title="Info" titleId="info-icon" />);
    const svg = screen.getByRole('img', { name: 'Info' });
    expect(svg).toHaveAttribute('aria-labelledby', 'info-icon');
  });

  it('applies the color prop to the fill attribute', () => {
    render(<InfoIcon data-testid="icon" color="#123456" />);
    expect(screen.getByTestId('icon')).toHaveAttribute('fill', '#123456');
  });

  it('merges className onto the svg element', () => {
    render(<InfoIcon data-testid="icon" className="custom-class" />);
    expect(screen.getByTestId('icon')).toHaveClass('custom-class');
  });

  it('generates a title id when non-decorative with title and no titleId', () => {
    render(<InfoIcon decorative={false} title="Info" />);
    const img = screen.getByRole('img', { name: 'Info' });
    expect(img).toHaveAttribute('aria-labelledby');
  });
});
