// packages/core/src/components/server/InteractiveListItem/InteractiveListItem.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories for InteractiveListItem covering removable versus static modes, href rendering, supporting/highlight text, and icon overrides.

import type { Meta, StoryObj } from '@storybook/react';
import { Markdown } from '@storybook/addon-docs/blocks';
import { InteractiveListItem, InteractiveListItemProps } from './InteractiveListItem';
import Readme from './README.md?raw';

const meta: Meta<InteractiveListItemProps> = {
  title: 'Server components/InteractiveListItem',
  component: InteractiveListItem,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  },
  args: {
    title: 'Account settings',
    supportingText: 'Manage how your account appears to others.',
    highlightText: 'Last updated 2 days ago',
    imgSrc: 'https://placehold.co/80x80',
    imgAlt: 'Account avatar placeholder',
    isRemovable: false,
    borderBottom: true
  }
};

export default meta;

type Story = StoryObj<InteractiveListItemProps>;

export const Default: Story = {};

export const Removable: Story = {
  args: {
    title: 'Remove account from list',
    isRemovable: true
  }
};

export const AsLink: Story = {
  args: {
    title: 'Manage account security',
    highlightText: 'Requires authentication',
    href: '#'
  }
};
