// packages/core/src/icons/EventIcon/EventIcon.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Verifies EventIcon decorative defaults, labeled role=img support, color prop passthrough, className merge, and generated title ids.

import { render, screen } from '@testing-library/react';
import { EventIcon } from './EventIcon';

describe('EventIcon', () => {
  it('defaults to decorative and sets aria-hidden="true"', () => {
    render(<EventIcon data-testid="icon" />);
    expect(screen.getByTestId('icon')).toHaveAttribute('aria-hidden', 'true');
  });

  it('renders non-decorative icons with title as role="img" and aria-labelledby', () => {
    render(<EventIcon decorative={false} title="Dismiss" titleId="close-icon" />);
    const svg = screen.getByRole('img', { name: 'Dismiss' });
    expect(svg).toHaveAttribute('aria-labelledby', 'close-icon');
  });

  it('applies the color prop to the fill attribute', () => {
    render(<EventIcon data-testid="icon" color="#123456" />);
    expect(screen.getByTestId('icon')).toHaveAttribute('fill', '#123456');
  });

  it('merges className onto the svg element', () => {
    render(<EventIcon data-testid="icon" className="custom-class" />);
    expect(screen.getByTestId('icon')).toHaveClass('custom-class');
  });

  it('generates a title id when non-decorative with title and no titleId', () => {
    render(<EventIcon decorative={false} title="Dismiss" />);
    const img = screen.getByRole('img', { name: 'Dismiss' });
    expect(img).toHaveAttribute('aria-labelledby');
  });
});
