// packages/core/src/components/server/Map/Map.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Map wraps consumer map content in a region section with optional overlay and disabled control rail tiles.

import * as React from 'react';
import { AddIcon, NearMeIcon, RemoveIcon } from '../../../icons';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type NativeSectionProps = Omit<React.HTMLAttributes<HTMLElement>, 'aria-label'>;

export interface MapProps extends NativeSectionProps {
  ariaLabel: string;
  showControls?: boolean;
  showOverlay?: boolean;
  isNested?: boolean;
}

const baseClasses = `
  relative block w-120 lg:w-full h-60 lg:h-170 overflow-hidden rounded-xl
  [_map-layer]:absolute [_map-layer]:inset-0
  data-[is-nested=true]:w-89.5 data-[is-nested=true]:h-100
`;

const surfaceClasses = `
  absolute inset-0
`;

const overlayClasses = `
  pointer-events-none absolute inset-x-0 bottom-0 w-full h-[82px] bg-linear-to-b from-opacity-overlay/0 to-opacity-overlay
`;

const railClasses = `
  absolute top-3 right-3 flex flex-col gap-2 border-none
  bg-color-background-subtle/10 text-color-content-default
`;

const segmentClasses = `
  flex flex-col gap-[2px] [&>button]:first:rounded-b-none [&>button]:last:rounded-t-none
`;

const tileClasses = `
  size-10 rounded-md bg-color-background-subtle text-color-content-default backdrop-blur-sm transition-colors border-none
`;

const iconClasses = `
  pointer-events-none [&>svg]:size-20 [&>*]:aria-hidden
`;

export const Map = React.forwardRef<HTMLElement, MapProps>(
  (
    {
      ariaLabel,
      showControls = true,
      showOverlay = true,
      isNested = false,
      className,
      children,
      ...rest
    },
    ref
  ) => {
    const baseClassName = collapseWhitespace(composeClasses(baseClasses, className));
    const surfaceClassName = collapseWhitespace(composeClasses(surfaceClasses));
    const overlayClassName = collapseWhitespace(composeClasses(overlayClasses));
    const railClassName = collapseWhitespace(composeClasses(railClasses));
    const segmentClassName = collapseWhitespace(composeClasses(segmentClasses));
    const tileClassName = collapseWhitespace(composeClasses(tileClasses));
    const iconClassName = collapseWhitespace(composeClasses(iconClasses));

    return (
      <section
        {...rest}
        ref={ref}
        role="region"
        aria-label={ariaLabel}
        data-is-nested={isNested ? 'true' : undefined}
        className={baseClassName}
        data-part="base"
      >
        <div className={surfaceClassName} data-part="surface">
          {children}
        </div>

        {showOverlay ? <div className={overlayClassName} data-part="overlay" /> : null}

        {showControls ? (
          <div className={railClassName} data-part="rail">
            <div className={segmentClassName} data-part="segment">
              <button
                type="button"
                className={tileClassName}
                data-part="tile"
                data-action="zoomIn"
                aria-label="Zoom in"
                disabled
              >
                <AddIcon className={iconClassName} data-part="icon" />
              </button>
              <button
                type="button"
                className={tileClassName}
                data-part="tile"
                data-action="zoomOut"
                aria-label="Zoom out"
                disabled
              >
                <RemoveIcon className={iconClassName} data-part="icon" />
              </button>
            </div>

            <button
              type="button"
              className={tileClassName}
              data-part="tile"
              data-action="nearMe"
              aria-label="Near me"
              disabled
            >
              <NearMeIcon className={iconClassName} data-part="icon" />
            </button>
          </div>
        ) : null}
      </section>
    );
  }
);

Map.displayName = 'Map';
