// packages/core/src/components/server/Map/Map.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook stories for Map showing default, nested, and control/overlay toggles with placeholder surface content.

import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { Map } from './Map';

const MapPlaceholder = () => (
  <div className="flex h-full w-full items-center justify-center rounded-lg bg-color-background-subtle/40 text-color-content-subtle">
    Consumer map surface
  </div>
);

const meta = {
  title: 'Server components/Map',
  component: Map,
  args: {
    ariaLabel: 'Map',
    children: <MapPlaceholder />
  }
} satisfies Meta<typeof Map>;

export default meta;

type Story = StoryObj<typeof Map>;

export const Default: Story = {};

export const Nested: Story = {
  args: {
    isNested: true
  }
};

export const ControlsOff: Story = {
  args: {
    showControls: false
  }
};

export const OverlayOff: Story = {
  args: {
    showOverlay: false
  }
};

