'use client';

// packages/core/src/components/client/ToggleGroup/ToggleGroup.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: ToggleGroup wraps Radix toggle group with icon-only items, orientation control, trimmed aria labels, and styled on/disabled states.

import * as React from 'react';
import { ToggleGroup as RadixToggleGroup } from 'radix-ui';
import { collapseWhitespace, composeClasses } from '../../../utilities';

type ToggleGroupRootProps = React.ComponentPropsWithoutRef<typeof RadixToggleGroup.Root>;

type ToggleGroupItem = {
  value: string;
  icon: React.ReactNode;
  ariaLabel?: string;
  disabled?: boolean;
};

export interface ToggleGroupProps
  extends Omit<ToggleGroupRootProps, 'asChild' | 'children' | 'aria-label'> {
  ariaLabel: string;
  items: ReadonlyArray<ToggleGroupItem>;
}

const baseClasses = `inline-flex rounded`;
const itemClasses = `
  flex
  h-35
  w-35
  items-center
  justify-center
  border-none
  focus:shadow-none
  bg-comp-button-color-background-knockout
  active:bg-comp-button-color-background-knockout-active
  active:text-comp-button-color-content-default-active
  text-comp-button-color-content-default
  first:rounded-l-sm
  last:rounded-r-sm
  hover:bg-comp-button-color-background-knockout-hover
  hover:text-comp-button-color-content-default-hover
  focus:z-10
  focus:shadow-[0_0_0_2px]
  focus-visible-brand
  data-[state=on]:bg-comp-button-primary-color-background-default
  data-[state=on]:text-comp-button-primary-color-content-default
  data-[state=on]:hover:bg-comp-button-primary-color-background-hover
  data-[state=on]:hover:text-comp-button-primary-color-content-hover
  data-[state=on]:active:bg-comp-button-primary-color-background-active
  disabled:opacity-50
  disabled:pointer-events-none
`;

export const ToggleGroup = React.forwardRef<
  React.ComponentRef<typeof RadixToggleGroup.Root>,
  ToggleGroupProps
>(({ ariaLabel, items, className, orientation = 'horizontal', ...restProps }, ref) => {
  const rootClassName = collapseWhitespace(composeClasses(baseClasses, className));
  const itemClassName = collapseWhitespace(composeClasses(itemClasses));

  return (
    <RadixToggleGroup.Root
      ref={ref}
      className={rootClassName}
      orientation={orientation}
      aria-label={ariaLabel}
      {...(restProps as ToggleGroupRootProps)}
    >
      {items.map(item => {
        const normalizedItemAriaLabel = item.ariaLabel?.trim();
        const itemAriaLabel =
          normalizedItemAriaLabel && normalizedItemAriaLabel.length > 0
            ? normalizedItemAriaLabel
            : item.value;

        return (
          <RadixToggleGroup.Item
            key={item.value}
            value={item.value}
            aria-label={itemAriaLabel}
            disabled={item.disabled}
            className={itemClassName}
          >
            <span aria-hidden="true">{item.icon}</span>
          </RadixToggleGroup.Item>
        );
      })}
    </RadixToggleGroup.Root>
  );
});

ToggleGroup.displayName = 'ToggleGroup';
