// packages/core/src/components/client/ToggleGroup/ToggleGroup.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Storybook story for ToggleGroup displaying the single-select text alignment example with onValueChange action and Radix icons.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react-vite';
import * as React from 'react';
import { fn } from 'storybook/test';
import { TextAlignLeftIcon, TextAlignCenterIcon, TextAlignRightIcon } from '@radix-ui/react-icons';
import Readme from './README.md?raw';
import { ToggleGroup, ToggleGroupProps } from './ToggleGroup';

const textAlignmentItems: ToggleGroupProps['items'] = [
  { value: 'left', icon: <TextAlignLeftIcon /> },
  { value: 'center', icon: <TextAlignCenterIcon /> },
  { value: 'right', icon: <TextAlignRightIcon /> }
];

const meta: Meta<ToggleGroupProps> = {
  title: 'Client components/ToggleGroup',
  component: ToggleGroup,
  args: {
    ariaLabel: 'Text alignment',
    type: 'single',
    defaultValue: 'center',
    onValueChange: fn(),
    items: textAlignmentItems
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<ToggleGroupProps>;

export const Default: Story = {};
