// packages/core/src/components/Tabs/Tabs.stories.tsx
// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { LayersIcon, ReaderIcon, GearIcon } from '@radix-ui/react-icons';
import { Tabs, TabsProps } from './Tabs';

const sectionTabs: TabsProps['tabsList'] = [
  {
    value: 'overview',
    label: 'Overview',
    icon: <LayersIcon />,
    content: (
      <div>
        <p>Overview content with key metrics and introductory details.</p>
      </div>
    )
  },
  {
    value: 'details',
    label: 'Details',
    icon: <ReaderIcon />,
    content: (
      <div>
        <p>Detailed analysis, supporting charts, and extended descriptions.</p>
      </div>
    )
  },
  {
    value: 'settings',
    label: 'Settings',
    disabled: true,
    icon: <GearIcon />,
    content: (
      <div>
        <p>Settings are available after completing initial setup.</p>
      </div>
    )
  }
];

const buttonTabs: TabsProps['tabsList'] = sectionTabs.map(({ icon, ...rest }) => ({ ...rest, icon: undefined }));

const meta: Meta<TabsProps> = {
  title: 'Components/Tabs',
  component: Tabs,
  args: {
    type: 'section',
    tabsList: sectionTabs,
    defaultValue: 'overview',
    ariaLabel: 'Project views',
    disabled: false
  },
  argTypes: {
    type: { control: { type: 'radio' }, options: ['section', 'button'] },
    disabled: { control: 'boolean' },
    activationMode: { control: { type: 'radio' }, options: ['automatic', 'manual'] },
    loop: { control: 'boolean' },
    value: { control: 'text' },
    defaultValue: { control: 'text' },
    tabsList: { control: false },
    onValueChange: { action: 'value-change' },
    ariaLabel: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<TabsProps>;

export const Default: Story = {
  args: {}
};

export const ButtonType: Story = {
  args: {
    type: 'button',
    tabsList: buttonTabs
  }
};

export const ManualActivation: Story = {
  args: {
    activationMode: 'manual'
  }
};

export const Looping: Story = {
  args: {
    loop: true
  }
};

const PersistentCounter: React.FC = () => {
  const [count, setCount] = React.useState(0);
  return (
    <div>
      <p>Count is {count}.</p>
      <button type="button" onClick={() => setCount(previous => previous + 1)}>
        Increment
      </button>
    </div>
  );
};

export const ForceMount: Story = {
  args: {
    tabsList: [
      {
        value: 'notes',
        label: 'Notes',
        icon: <LayersIcon />,
        content: (
          <div>
            <p>Notes panel remains mounted while hidden.</p>
          </div>
        ),
        forceMount: true
      },
      {
        value: 'counter',
        label: 'Counter',
        icon: <ReaderIcon />,
        content: <PersistentCounter />,
        forceMount: true
      },
      {
        value: 'summary',
        label: 'Summary',
        icon: <GearIcon />,
        content: (
          <div>
            <p>Summary highlights current configuration snapshots.</p>
          </div>
        )
      }
    ]
  }
};
