import '@testing-library/jest-dom';
// packages/core/src/components/Tabs/Tabs.test.tsx
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { RenderResult } from '@testing-library/react';
import { Tabs, TabsProps } from './Tabs';

const baseTabsList: TabsProps['tabsList'] = [
  {
    value: 'overview',
    label: 'Overview',
    content: <div>Overview content</div>,
    icon: <span data-testid="overview-icon">🔥</span>
  },
  {
    value: 'details',
    label: 'Details',
    content: <div>Details content</div>,
    icon: <span data-testid="details-icon">📄</span>
  },
  {
    value: 'settings',
    label: 'Settings',
    disabled: true,
    content: <div>Settings content</div>
  }
];

const renderTabs = (overrideProps?: Partial<TabsProps>): RenderResult =>
  render(
    <Tabs
      tabsList={baseTabsList}
      ariaLabel="Project tabs"
      defaultValue="overview"
      {...overrideProps}
    />
  );

describe('Tabs', () => {
  it('renders the tablist using the provided aria-label', () => {
    const view: RenderResult = renderTabs();
    const tablist = screen.getByRole('tablist', { name: 'Project tabs' });
    expect(tablist).toBeInTheDocument();
    view.unmount();
  });

  it('activates a non-disabled trigger when clicked', async () => {
    const user = userEvent.setup();
    const view: RenderResult = renderTabs();
    await user.click(screen.getByRole('tab', { name: 'Details' }));
    const detailsTrigger = screen.getByRole('tab', { name: 'Details' });
    expect(detailsTrigger.getAttribute('aria-selected')).toBe('true');
    view.unmount();
  });

  it('requires Enter/Space to activate when activationMode is manual', async () => {
    const user = userEvent.setup();
    const view: RenderResult = renderTabs({ activationMode: 'manual' });
    const firstTrigger = screen.getByRole('tab', { name: 'Overview' });
    const secondTrigger = screen.getByRole('tab', { name: 'Details' });
    firstTrigger.focus();
    await user.keyboard('{ArrowRight}');
    const stateAfterArrow = secondTrigger.getAttribute('aria-selected');
    await user.keyboard('{Enter}');
    const stateAfterEnter = secondTrigger.getAttribute('aria-selected');
    expect([stateAfterArrow, stateAfterEnter]).toEqual(['false', 'true']);
    view.unmount();
  });

  it('wraps focus to the first trigger when loop is enabled', async () => {
    const user = userEvent.setup();
    const view: RenderResult = renderTabs({ loop: true });
    const triggers = screen.getAllByRole('tab');
    const lastTrigger = triggers[triggers.length - 1];
    lastTrigger.focus();
    await user.keyboard('{ArrowRight}');
    expect(document.activeElement === triggers[0]).toBe(true);
    view.unmount();
  });

  it('prevents disabled triggers from becoming selected', async () => {
    const user = userEvent.setup();
    const view: RenderResult = renderTabs();
    const disabledTrigger = screen.getByRole('tab', { name: 'Settings' });
    await user.click(disabledTrigger);
    expect(disabledTrigger.getAttribute('aria-selected')).toBe('false');
    view.unmount();
  });

  it('blocks interactions when globally disabled and avoids firing onValueChange', async () => {
    const user = userEvent.setup();
    const handleValueChange = jest.fn();
    const view: RenderResult = renderTabs({
      disabled: true,
      onValueChange: handleValueChange,
      value: 'overview'
    });
    await user.click(screen.getByRole('tab', { name: 'Details' }));
    expect(handleValueChange).not.toHaveBeenCalled();
    view.unmount();
  });

  it('renders the trigger icon in section mode as decorative', () => {
    const view: RenderResult = renderTabs();
    const icon = screen
      .getByRole('tab', { name: 'Overview' })
      .querySelector('[data-slot="triggerIcon"]');
    expect(icon?.getAttribute('aria-hidden')).toBe('true');
    view.unmount();
  });

  it('omits trigger icons in button mode and renders a Button child', () => {
    const view: RenderResult = renderTabs({
      type: 'button',
      tabsList: baseTabsList.map(({ ...rest }) => rest)
    });
    const trigger = screen.getByRole('tab', { name: 'Overview' });
    const noIconAndIsButton =
      trigger.tagName === 'BUTTON' && trigger.querySelector('[data-slot="triggerIcon"]') === null;
    expect(noIconAndIsButton).toBe(true);
    view.unmount();
  });
});
