// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import { RadioButtonGroup, type RadioButtonGroupProps } from './RadioButtonGroup';

const baseChoices: RadioButtonGroupProps['choices'] = [
  { value: 'email', label: 'Email updates' },
  { value: 'sms', label: 'SMS alerts', hint: 'Standard messaging rates may apply.' },
  { value: 'push', label: 'Push notifications' }
];

const meta: Meta<RadioButtonGroupProps> = {
  title: 'Components/RadioButtonGroup',
  component: RadioButtonGroup,
  argTypes: {
    onValueChange: { action: 'value change' },
    choices: { control: false },
    value: { control: 'text' },
    defaultValue: { control: 'text' },
    name: { control: 'text' },
    label: { control: 'text' },
    ariaLabel: { control: 'text' },
    hint: { control: 'text' },
    info: { control: 'text' },
    error: { control: 'text' }
  },
  args: {
    label: 'Notification preferences',
    choices: baseChoices
  }
};

export default meta;

type Story = StoryObj<RadioButtonGroupProps>;

export const Default: Story = {
  args: {
    hint: 'Choose the option that works best for you.'
  }
};

export const WithInfo: Story = {
  args: {
    info: 'You can adjust these preferences later in account settings.'
  }
};

export const WithError: Story = {
  args: {
    error: 'Please select a notification method before continuing.'
  }
};

export const PerChoiceDisabled: Story = {
  args: {
    choices: [
      { value: 'email', label: 'Email updates' },
      { value: 'sms', label: 'SMS alerts', disabled: true },
      { value: 'push', label: 'Push notifications' }
    ]
  }
};

export const ManyChoices: Story = {
  args: {
    choices: [
      { value: 'daily', label: 'Daily digest' },
      { value: 'weekly', label: 'Weekly summary' },
      { value: 'monthly', label: 'Monthly recap' },
      { value: 'product', label: 'Product announcements' },
      { value: 'alerts', label: 'Critical alerts', hint: 'Only high-priority updates.' }
    ]
  }
};
