// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { Button, ButtonProps } from './Button';

const meta: Meta<ButtonProps> = {
  title: 'Components/Button',
  component: Button,
  args: {
    children: 'Button',
    disabled: false,
    loading: false,
    fullWidth: false,
    type: 'button'
  }
};

export default meta;

type Story = StoryObj<ButtonProps>;

export const Primary: Story = {
  args: {
    variant: 'primary'
  }
};

export const Secondary: Story = {
  args: {
    variant: 'secondary'
  }
};

export const Bare: Story = {
  args: {
    variant: 'bare'
  }
};

export const Knockout: Story = {
  args: {
    variant: 'knockout'
  }
};

export const WithIcons: Story = {
  args: {
    variant: 'primary',
    startIcon: <span aria-hidden="true">🌟</span>,
    endIcon: <span aria-hidden="true">➡️</span>
  }
};
