// packages/core/src/icons/NotesIcon/NotesIcon.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Storybook stories for NotesIcon showcasing decorative default and non-decorative role=img usage with color/className controls.

import type { Meta, StoryObj } from '@storybook/react-vite';
import { NotesIcon, NotesIconProps } from './NotesIcon';

const meta: Meta<NotesIconProps> = {
  title: 'Icons/NotesIcon',
  component: NotesIcon,
  args: {
    decorative: true,
    color: 'currentColor'
  },
  argTypes: {
    decorative: { control: 'boolean' },
    title: { control: 'text' },
    titleId: { control: 'text' },
    color: { control: 'color' },
    className: { control: 'text' }
  }
};

export default meta;

type Story = StoryObj<NotesIconProps>;

export const Default: Story = {};

export const NonDecorative: Story = {
  args: {
    decorative: false,
    title: 'Dismiss notification',
    titleId: 'close-icon-title'
  }
};
