// packages/core/src/icons/VolumeOffIcon/VolumeOffIcon.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Storybook stories for VolumeOffIcon showcasing decorative default and non-decorative role=img usage with color/className controls.

import type { Meta, StoryObj } from '@storybook/react-vite';
import { VolumeOffIcon, VolumeOffIconProps } from './VolumeOffIcon';

const meta: Meta<VolumeOffIconProps> = {
  title: 'Icons/VolumeOffIcon',
  component: VolumeOffIcon,
  args: {
    decorative: true,
    color: 'currentColor'
  }
};

export default meta;

type Story = StoryObj<VolumeOffIconProps>;

export const Default: Story = {};

export const NonDecorative: Story = {
  args: {
    decorative: false,
    title: 'Dismiss notification',
    titleId: 'close-icon-title'
  }
};
