// packages/core/src/components/client/Accordion/Accordion.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Verifies Accordion renders title trigger, manages content states, supports emphasis and optional slots, rotates icons, keeps focus tokens, and honors controlled open props.

import '@testing-library/jest-dom';
import * as React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import type { RenderResult } from '@testing-library/react';
import { Accordion, AccordionProps } from './Accordion';

type Emphasis = NonNullable<AccordionProps['emphasis']>;

const renderAccordion = (overrideProps?: Partial<AccordionProps>): RenderResult =>
  render(
    <Accordion title="Sample Title" {...overrideProps}>
      <p>Body copy</p>
    </Accordion>
  );

describe('Accordion', () => {
  it('renders the trigger button using the provided title', () => {
    const view: RenderResult = renderAccordion();
    expect(screen.getByRole('button', { name: 'Sample Title' })).toBeInTheDocument();
    view.unmount();
  });

  it('keeps the content region mounted but closed by default', () => {
    const view: RenderResult = renderAccordion();
    const content = view.container.querySelector('[data-slot="content"]') as HTMLElement;
    expect(content.getAttribute('data-state')).toBe('closed');
    view.unmount();
  });

  describe('emphasis state', () => {
    const cases: ReadonlyArray<[Emphasis, boolean]> = [
      ['strong', true],
      ['weak', false]
    ] as const;

    it.each(cases)('applies emphasisStrong when emphasis=%s', (emphasis, expected) => {
      const view: RenderResult = renderAccordion({ emphasis });
      const titleSlot = view.container.querySelector('[data-slot="title"]') as HTMLElement;
      expect(titleSlot.className.includes('font-bold')).toBe(expected);
      view.unmount();
    });
  });

  it('omits the image slot when not provided', () => {
    const view: RenderResult = renderAccordion();
    expect(screen.queryByTestId('thumb')).toBeNull();
    view.unmount();
  });

  it('renders the image slot when an img element is provided', () => {
    const view: RenderResult = renderAccordion({
      image: <img src="thumb.png" alt="" data-testid="thumb" />
    });
    expect(screen.getByTestId('thumb')).toBeInTheDocument();
    view.unmount();
  });

  it('renders the intro before the body content when provided', () => {
    const view: RenderResult = renderAccordion({ intro: 'Introductory copy' });
    fireEvent.click(screen.getByRole('button', { name: 'Sample Title' }));
    const intro = view.container.querySelector('[data-slot="intro"]') as HTMLElement;
    expect(intro.textContent).toBe('Introductory copy');
    view.unmount();
  });

  it('applies the closed rotation state to the icon by default', () => {
    const view: RenderResult = renderAccordion();
    const icon = view.container.querySelector('[data-slot="icon"] svg') as HTMLElement;
    expect(icon.classList.contains('group-data-[state=closed]:rotate-0')).toBe(true);
    view.unmount();
  });

  it('applies the open rotation state after toggling', () => {
    const view: RenderResult = renderAccordion();
    fireEvent.click(screen.getByRole('button', { name: 'Sample Title' }));
    const icon = view.container.querySelector('[data-slot="icon"] svg') as HTMLElement;
    expect(icon.classList.contains('group-data-[state=open]:rotate-180')).toBe(true);
    view.unmount();
  });

  it('keeps the focus ring tokens on the base element', () => {
    const view: RenderResult = renderAccordion();
    const root = view.container.querySelector('[data-slot="container"]') as HTMLElement;
    expect(root.className).toContain('ring-comp-border-focus-ring');
    view.unmount();
  });

  it('avoids applying focus ring tokens on the trigger slot', () => {
    const view: RenderResult = renderAccordion();
    const trigger = view.container.querySelector('[data-slot="trigger"]') as HTMLElement;
    expect(trigger.className.includes('focus-visible:ring')).toBe(false);
    view.unmount();
  });

  it('opens when a controlled value is provided (covers value ??)', () => {
    const view: RenderResult = renderAccordion({ value: 'controlled' });
    const content = view.container.querySelector('[data-slot="content"]') as HTMLElement;
    expect(content.getAttribute('data-state')).toBe('open');
    view.unmount();
  });

  it('opens when a defaultValue is provided (covers ?? defaultValue)', () => {
    const view: RenderResult = renderAccordion({ defaultValue: 'uncontrolled' });
    const content = view.container.querySelector('[data-slot="content"]') as HTMLElement;
    expect(content.getAttribute('data-state')).toBe('open');
    view.unmount();
  });
});
