// packages/core/src/components/client/Accordion/Accordion.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Storybook stories for Accordion demonstrating default, image, and intro examples plus strong/weak emphasis; image control disabled.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import Readme from './README.md?raw';
import { Accordion, AccordionProps } from './Accordion';

const meta: Meta<AccordionProps> = {
  title: 'Client components/Accordion',
  component: Accordion,
  args: {
    title: 'What is DoXYZ?',
    children: (
      <p>
        Accordion content lives here. Provide supporting details or onboarding information that
        users may need to expand.
      </p>
    ),
    emphasis: 'strong'
  },
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<AccordionProps>;

export const Default: Story = {};

export const WithImage: Story = {
  args: {
    image: <img src="https://placehold.co/600x400/png" alt="placeholder image" />
  }
};

export const WithIntro: Story = {
  args: {
    intro: 'This optional introduction sits above the main body content.'
  }
};

export const EmphasisStrong: Story = {
  args: {
    emphasis: 'strong'
  }
};

export const EmphasisWeak: Story = {
  args: {
    emphasis: 'weak'
  }
};
