// packages/core/src/components/client/Stepper/Stepper.test.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Tests Stepper interactive tablist roles, step and rail statuses, focus ring tokens, aria labeling, onStepChange interactions, static list mode, and completed icon rendering.

import '@testing-library/jest-dom';
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Stepper } from './Stepper';

describe('Stepper', () => {
  it('renders interactive navigation as a tablist', () => {
    render(<Stepper steps={3} activeStep={1} activeLabel="Shipping" onStepChange={jest.fn()} />);
    expect(screen.getByRole('tablist')).toBeInTheDocument();
  });

  it('marks the active tab with aria-current="step"', () => {
    render(<Stepper steps={3} activeStep={1} activeLabel="Shipping" onStepChange={jest.fn()} />);
    const tabs = screen.getAllByRole('tab');
    expect(tabs[0].getAttribute('aria-current')).toBe('step');
  });

  test.each([
    { activeStep: 1, expected: ['active', 'upcoming', 'upcoming'] },
    { activeStep: 2, expected: ['completed', 'active', 'upcoming'] },
    { activeStep: 3, expected: ['completed', 'completed', 'active'] }
  ])('computes step statuses for activeStep=$activeStep', ({ activeStep, expected }) => {
    render(
      <Stepper steps={3} activeStep={activeStep} activeLabel="Shipping" onStepChange={jest.fn()} />
    );
    const statuses = screen
      .getAllByRole('tab')
      .map(tab => tab.getAttribute('data-step-status') ?? '');
    expect(statuses).toEqual(expected);
  });

  test.each([
    { steps: 1, activeStep: 1, expected: [] },
    { steps: 4, activeStep: 1, expected: ['default', 'default', 'default'] },
    { steps: 4, activeStep: 3, expected: ['full', 'partial', 'default'] }
  ])('computes rail statuses for activeStep=$activeStep', ({ steps, activeStep, expected }) => {
    const { container } = render(
      <Stepper
        steps={steps}
        activeStep={activeStep}
        activeLabel="Shipping"
        onStepChange={jest.fn()}
      />
    );
    const rails = Array.from(container.querySelectorAll<HTMLElement>('[data-slot="rail"]')).map(
      node => node.getAttribute('data-rail-status') ?? ''
    );
    expect(rails).toEqual(expected);
  });

  it('retains the focus-visible ring on interactive buttons', () => {
    render(<Stepper steps={3} activeStep={1} activeLabel="Shipping" onStepChange={jest.fn()} />);
    const [firstTab] = screen.getAllByRole('tab');
    firstTab.focus();
    const className = firstTab.className;
    expect(className.includes('focus-visible-brand')).toBe(true);
  });

  it('names the active tab via aria-labelledby', () => {
    render(<Stepper steps={3} activeStep={2} activeLabel="Review" onStepChange={jest.fn()} />);
    const tabs = screen.getAllByRole('tab');
    const active = tabs.find(t => t.getAttribute('aria-current') === 'step')!;
    const labelledBy = active.getAttribute('aria-labelledby') ?? '';
    expect(/stepper-label-1$/.test(labelledBy)).toBe(true);
  });

  it('names non-active tabs via aria-label', () => {
    render(<Stepper steps={3} activeStep={2} activeLabel="Review" onStepChange={jest.fn()} />);
    const tabs = screen.getAllByRole('tab');
    const aNonActive = tabs.find(t => t.getAttribute('aria-current') !== 'step')!;
    expect(aNonActive.getAttribute('aria-label')).toBeTruthy();
  });

  it('invokes onStepChange when clicking an upcoming tab', async () => {
    const user = userEvent.setup();
    const handleStepChange = jest.fn();
    render(
      <Stepper steps={4} activeStep={1} activeLabel="Shipping" onStepChange={handleStepChange} />
    );
    const tabs = screen.getAllByRole('tab');
    await user.click(tabs[2]);
    expect(handleStepChange).toHaveBeenCalledWith(2);
  });

  it('invokes onStepChange when pressing Enter', async () => {
    const user = userEvent.setup();
    const handleStepChange = jest.fn();
    render(
      <Stepper steps={4} activeStep={1} activeLabel="Shipping" onStepChange={handleStepChange} />
    );
    const tabs = screen.getAllByRole('tab');
    tabs[1].focus();
    await user.keyboard('{Enter}');
    expect(handleStepChange.mock.calls).toEqual([[1]]);
  });

  it('renders static mode with list semantics', () => {
    render(<Stepper steps={3} activeStep={2} activeLabel="Review" />);
    const list = screen.getByRole('list');
    const valid =
      list.getAttribute('aria-orientation') === null &&
      screen.getAllByRole('listitem').length === 3;
    expect(valid).toBe(true);
  });

  it('sets aria-orientation only when interactive', () => {
    const { rerender, container } = render(
      <Stepper steps={3} activeStep={1} activeLabel="Shipping" onStepChange={jest.fn()} />
    );
    const interactiveOrientation = container.querySelector('nav')?.getAttribute('aria-orientation');
    rerender(<Stepper steps={3} activeStep={1} activeLabel="Shipping" />);
    const staticOrientation = container.querySelector('nav')?.getAttribute('aria-orientation');
    expect([interactiveOrientation, staticOrientation]).toEqual(['horizontal', null]);
  });

  it('renders check icons for completed steps', () => {
    render(<Stepper steps={3} activeStep={3} activeLabel="Shipping" onStepChange={jest.fn()} />);
    const tabs = screen.getAllByRole('tab');
    const completedTabs = tabs.slice(0, 2);
    const decorativeChecks = completedTabs.every(tab =>
      tab.querySelector('svg[aria-hidden="true"]')
    );
    expect(decorativeChecks).toBe(true);
  });
});
