// packages/core/src/components/Stepper/Stepper.stories.tsx
// This file was generated by an AI agent. Do not edit directly.
import type { Meta, StoryObj } from '@storybook/react';
import { fn } from 'storybook/test';
import { Stepper, StepperProps } from '@doxyz-ui/core/client-components';

const meta: Meta<StepperProps> = {
  title: 'Client components/Stepper',
  component: Stepper
};

export default meta;

type Story = StoryObj<StepperProps>;

export const Default: Story = {
  args: {
    steps: 4,
    activeStep: 3,
    activeLabel: 'Shipping details',
    onStepChange: fn()
  }
};

export const Static: Story = {
  args: {
    steps: 4,
    activeStep: 3,
    activeLabel: 'Shipping details'
  }
};

export const ActiveFirst: Story = {
  args: {
    steps: 4,
    activeStep: 1,
    activeLabel: 'Shipping details',
    onStepChange: fn()
  }
};

export const ActiveLast: Story = {
  args: {
    steps: 4,
    activeStep: 4,
    activeLabel: 'Shipping details',
    onStepChange: fn()
  }
};

export const LongLabels: Story = {
  args: {
    steps: 4,
    activeStep: 2,
    activeLabel: 'Review your shipping address and delivery preferences',
    onStepChange: fn()
  }
};