// packages/core/src/icons/ArtistIcon/ArtistIcon.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: ArtistIcon renders a customizable artist-themed SVG supporting decorative or labeled usage with optional title and color props

import * as React from 'react';

export interface ArtistIconProps extends React.SVGAttributes<SVGSVGElement> {
  decorative?: boolean;
  title?: string;
  titleId?: string;
  color?: string;
}

type ArtistIconElement = SVGSVGElement;

export const ArtistIcon = React.forwardRef<ArtistIconElement, ArtistIconProps>(
  (
    {
      decorative = true,
      width = '20px',
      height = '20px',
      title,
      titleId: providedTitleId,
      color = 'currentColor',
      className,
      'aria-labelledby': ariaLabelledby,
      ...rest
    },
    ref
  ) => {
    const generatedTitleId = React.useId();
    const resolvedTitleId = title ? (providedTitleId ?? generatedTitleId) : undefined;

    const computedAriaHidden = decorative ? 'true' : undefined;
    const computedRole = decorative ? undefined : 'img';
    const computedAriaLabelledby =
      !decorative && title && resolvedTitleId ? resolvedTitleId : ariaLabelledby;

    return (
      <svg
        ref={ref}
        {...rest}
        className={className}
        viewBox="0 0 20 20"
        width={width}
        height={height}
        fill={color}
        aria-hidden={computedAriaHidden}
        role={computedRole}
        aria-labelledby={computedAriaLabelledby}
      >
        {!decorative && title ? <title id={resolvedTitleId}>{title}</title> : null}
        <g transform="scale(0.0208333333,0.0208333333) translate(0,960)">
          <path d="M720-563.48h127.41v79.41h-72v204.44q0 41.75-28.97 70.79-28.97 29.04-70.68 29.04-41.71 0-70.73-28.97Q576-237.74 576-279.46q0-41.71 28.88-70.73 28.88-29.03 70.71-29.03 12.25 0 23.31 3.76 11.06 3.76 21.1 8.05v-196.07ZM133-179.8v-100.61q0-28.16 13.58-51.57 13.57-23.41 37.72-37.37 55.48-32.24 117.59-49.48 62.1-17.24 127.24-17.24 35.78 0 70.82 5.82 35.03 5.82 69.85 17.92-16.87 13.76-30.52 30.75-13.66 16.98-23.28 37.99-20.72-5.48-42.93-7.48t-43.94-2q-53.27 0-104.68 13.41-51.41 13.4-97.45 41.16-4.95 2.84-7.98 7.94-3.02 5.1-3.02 11.34v16.42h290q1.04 23.34 8.52 43.71 7.48 20.37 20.15 39.29H133Zm296.13-304.27q-63.59 0-107.86-44.27Q277-572.61 277-636.2q0-63.58 44.27-107.74 44.27-44.15 107.86-44.15 63.59 0 107.74 44.15 44.15 44.16 44.15 107.74 0 63.59-44.15 107.86-44.15 44.27-107.74 44.27Zm.2-83q28.6 0 48.65-20.36 20.04-20.37 20.04-48.97 0-28.6-20.3-48.64-20.3-20.05-48.8-20.05-28.61 0-48.76 20.3Q360-664.49 360-635.98q0 28.6 20.37 48.76 20.36 20.15 48.96 20.15Zm-.2-69.13Zm0 373.4Z" />
        </g>
      </svg>
    );
  }
);

ArtistIcon.displayName = 'ArtistIcon';
