// packages/core/src/components/client/FloatingBar/FloatingBar.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Stories for FloatingBar showcasing default layout, interactive scroll controls, and disabled scroll buttons.

import { Markdown } from '@storybook/addon-docs/blocks';
import type { Meta, StoryObj } from '@storybook/react';
import { fn } from 'storybook/test';
import { Button } from '../Button';
import Readme from './README.md?raw';
import { FloatingBar } from './FloatingBar';

const meta: Meta<typeof FloatingBar> = {
  title: 'Client components/FloatingBar',
  component: FloatingBar,
  tags: ['autodocs'],
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    }
  }
};

export default meta;

type Story = StoryObj<typeof FloatingBar>;

const defaultActions = (
  <div className="inline-flex gap-2">
    <Button>Apply</Button>
    <Button variant="secondary">Dismiss</Button>
  </div>
);

export const Default: Story = {
  args: {
    content: 'Review recent changes before publishing.',
    actions: defaultActions
  }
};

export const ScrollableInteractive: Story = {
  args: {
    isScrollable: true,
    content: (
      <div className="flex gap-4 whitespace-nowrap">
        <span>Step 1: Draft</span>
        <span>Step 2: Review</span>
        <span>Step 3: Approve</span>
        <span>Step 4: Publish</span>
      </div>
    ),
    actions: defaultActions,
    onLeftScroll: fn(),
    onRightScroll: fn()
  }
};

export const ScrollableDisabled: Story = {
  args: {
    isScrollable: true,
    content: (
      <div className="flex gap-4 whitespace-nowrap">
        <span>Filter: Region</span>
        <span>Filter: Segment</span>
        <span>Filter: Status</span>
      </div>
    ),
    actions: (
      <div className="inline-flex gap-2">
        <Button disabled>Clear</Button>
        <Button>Save</Button>
      </div>
    )
  }
};
