'use client';

// packages/core/src/components/client/FloatingBar/FloatingBar.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Floating utility bar with optional scroll buttons, content/actions slots, and accessible labeling via aria props.

import * as React from 'react';
import { ArrowBackIcon, ArrowForwardIcon } from '../../../icons';
import { IconButton } from '../IconButton';
import { composeClasses } from '../../../utilities/composeClasses/composeClasses';
import { collapseWhitespace } from '../../../utilities/collapseWhitespace/collapseWhitespace';

const baseClasses = `flex items-center justify-between gap-2 px-16 py-24 bg-color-background-default outline-none`;
const startButtonWrapperClasses = `_startButton shrink-0`;
const endButtonWrapperClasses = `_endButton shrink-0`;
const railClasses = `_rail flex items-center gap-2 min-w-0 flex-1`;
const contentClasses = `_content min-w-0 flex-1 justify-start truncate text-color-content-default`;
const actionsClasses = `_actions inline-flex gap-2 shrink-0 justify-end`;

type FloatingBarScrollEvent = MouseEvent | KeyboardEvent;

export interface FloatingBarProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'content'> {
  ariaLabel?: string;
  labelledBy?: string;
  isScrollable?: boolean;
  onLeftScroll?: (event?: FloatingBarScrollEvent) => void;
  onRightScroll?: (event?: FloatingBarScrollEvent) => void;
  content?: React.ReactNode;
  actions?: React.ReactNode;
}

export const FloatingBar = React.forwardRef<HTMLDivElement, FloatingBarProps>(
  (
    {
      ariaLabel,
      labelledBy,
      isScrollable = false,
      onLeftScroll,
      onRightScroll,
      content,
      actions,
      className,
      role: roleProp,
      ...rest
    },
    ref
  ) => {
    const trimmedAriaLabel = ariaLabel?.trim() ?? '';
    const trimmedLabelledBy = labelledBy?.trim() ?? '';

    const role = roleProp ?? (trimmedAriaLabel || trimmedLabelledBy ? 'region' : undefined);

    const baseClassName = collapseWhitespace(composeClasses(baseClasses, className));
    const railClassName = collapseWhitespace(composeClasses(railClasses));
    const contentClassName = collapseWhitespace(composeClasses(contentClasses));
    const actionsClassName = collapseWhitespace(composeClasses(actionsClasses));
    const startButtonClassName = collapseWhitespace(composeClasses(startButtonWrapperClasses));
    const endButtonClassName = collapseWhitespace(composeClasses(endButtonWrapperClasses));

    const handleLeftScroll = React.useCallback(
      (event: React.MouseEvent<HTMLButtonElement>) => {
        onLeftScroll?.(event.nativeEvent);
      },
      [onLeftScroll]
    );

    const handleRightScroll = React.useCallback(
      (event: React.MouseEvent<HTMLButtonElement>) => {
        onRightScroll?.(event.nativeEvent);
      },
      [onRightScroll]
    );

    const leftScrollDisabled = !onLeftScroll;
    const rightScrollDisabled = !onRightScroll;

    return (
      <div
        ref={ref}
        className={baseClassName}
        role={role}
        aria-label={trimmedAriaLabel.length > 0 ? trimmedAriaLabel : undefined}
        aria-labelledby={trimmedLabelledBy.length > 0 ? trimmedLabelledBy : undefined}
        data-slot="container"
        {...rest}
      >
        {isScrollable ? (
          <span className={startButtonClassName} data-slot="_startButton">
            <IconButton
              icon={<ArrowBackIcon />}
              ariaLabel="Scroll left"
              variant="bare"
              disabled={leftScrollDisabled}
              onClick={onLeftScroll ? handleLeftScroll : undefined}
            />
          </span>
        ) : null}
        <div className={railClassName} data-slot="_rail">
          <div className={contentClassName} data-slot="_content">
            {content}
          </div>
          <div className={actionsClassName} data-slot="_actions">
            {actions}
          </div>
        </div>
        {isScrollable ? (
          <span className={endButtonClassName} data-slot="_endButton">
            <IconButton
              icon={<ArrowForwardIcon />}
              ariaLabel="Scroll right"
              variant="bare"
              disabled={rightScrollDisabled}
              onClick={onRightScroll ? handleRightScroll : undefined}
            />
          </span>
        ) : null}
      </div>
    );
  }
);

FloatingBar.displayName = 'FloatingBar';
