import '@testing-library/jest-dom';
// packages/core/src/components/Combobox/Combobox.test.tsx
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { Combobox, type ComboboxProps } from './Combobox';

beforeAll(() => {
  Object.defineProperty(window.HTMLElement.prototype, 'hasPointerCapture', {
    value: () => false,
    configurable: true
  });
  Object.defineProperty(window.HTMLElement.prototype, 'setPointerCapture', {
    value: () => {},
    configurable: true
  });
  Object.defineProperty(window.HTMLElement.prototype, 'releasePointerCapture', {
    value: () => {},
    configurable: true
  });
  Object.defineProperty(window.HTMLElement.prototype, 'scrollIntoView', {
    value: () => {},
    configurable: true
  });
});

const baseItems: NonNullable<ComboboxProps['items']> = [
  { id: 'artists', option: 'Artists' },
  { id: 'venues', option: 'Venues' },
  { id: 'events', option: 'Events' }
];

describe('Combobox', () => {
  it('renders placeholder text when no selection is present', () => {
    render(
      <Combobox
        placeholder="Select categories"
        items={baseItems}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByPlaceholderText('Select categories')).toBeInTheDocument();
  });

  it('renders chip dismiss button with accessible label', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        FormElementProps={{ label: 'Categories' }}
        showEndIcon
      />
    );
    expect(screen.getByRole('button', { name: 'Remove Artists' })).toBeInTheDocument();
  });

  it('does not render clear-all button when no selections exist', () => {
    render(<Combobox items={baseItems} showEndIcon FormElementProps={{ label: 'Categories' }} />);
    expect(screen.queryByRole('button', { name: 'Clear all selections' })).toBeNull();
  });

  it('renders clear-all button when selections exist', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        showEndIcon
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByRole('button', { name: 'Clear all selections' })).toBeInTheDocument();
  });

  it('calls onSelectionChange when selecting an item', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn();
    render(
      <Combobox
        items={baseItems}
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    await user.click(screen.getByRole('combobox'));
    const option = await screen.findByRole('option', { name: 'Venues' });
    await user.click(option);
    expect(handleSelectionChange).toHaveBeenCalledWith(['venues']);
  });

  it('keeps the popover open after selecting an item', async () => {
    const user = userEvent.setup();
    render(<Combobox items={baseItems} FormElementProps={{ label: 'Categories' }} />);

    await user.click(screen.getByRole('combobox'));
    const option = await screen.findByRole('option', { name: 'Venues' });
    await user.click(option);
    expect(screen.getByRole('listbox')).toBeInTheDocument();
  });

  it('clears selections via the clear-all button', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists', 'venues']}
        showEndIcon
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    await user.click(screen.getByRole('button', { name: 'Clear all selections' }));
    expect(handleSelectionChange).toHaveBeenCalledWith([]);
  });

  it('moves highlight with the ArrowDown key', async () => {
    const user = userEvent.setup();
    render(<Combobox items={baseItems} FormElementProps={{ label: 'Categories' }} />);

    await user.click(screen.getByRole('combobox'));
    await user.keyboard('{ArrowDown}');
    expect(screen.getByRole('combobox').getAttribute('aria-activedescendant')).toContain(
      'option-artists'
    );
  });

  it('selects the highlighted item with Enter', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn();
    render(
      <Combobox
        items={baseItems}
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    await user.click(screen.getByRole('combobox'));
    await user.keyboard('{ArrowDown}{Enter}');
    expect(handleSelectionChange).toHaveBeenCalledWith(['artists']);
  });

  it('does not open when disabled', async () => {
    const user = userEvent.setup();
    render(
      <Combobox
        items={baseItems}
        disabled
        FormElementProps={{ label: 'Categories' }}
      />
    );

    await user.click(screen.getByRole('combobox'));
    expect(screen.getByRole('combobox')).toHaveAttribute('aria-expanded', 'false');
  });

  it('renders empty state text when no items are provided', () => {
    render(
      <Combobox
        items={[]}
        defaultOpen
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByText('No options available')).toBeInTheDocument();
  });

  it('omits the placeholder when selections exist', () => {
    render(
      <Combobox
        placeholder="Select categories"
        items={baseItems}
        defaultSelectedIds={['artists']}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByRole('combobox')).not.toHaveAttribute('placeholder');
  });
});

