it('controlled mode: calls onSelectionChange but UI stays in sync with prop (no internal mutation)', async () => {
  const user = userEvent.setup();
  const handleSelectionChange = jest.fn<void, [string[]]>();
  render(
    <Combobox
      items={baseItems}
      selectedIds={['artists']}
      defaultOpen
      onSelectionChange={handleSelectionChange}
      FormElementProps={{ label: 'Categories' }}
    />
  );

  const artists = await screen.findByRole('option', { name: 'Artists' });
  const venues = await screen.findByRole('option', { name: 'Venues' });

  // Sanity: controlled selection marks Artists selected, Venues not selected
  expect(artists).toHaveAttribute('aria-selected', 'true');
  expect(venues).toHaveAttribute('aria-selected', 'false');

  // Click Venues — should request a change but NOT update UI (since prop is controlled)
  await user.click(venues);

  expect(handleSelectionChange).toHaveBeenCalledWith(['artists', 'venues']);
  // Still controlled by prop; UI remains as originally rendered
  expect(artists).toHaveAttribute('aria-selected', 'true');
  expect(venues).toHaveAttribute('aria-selected', 'false');
});
import '@testing-library/jest-dom';
// packages/core/src/components/Combobox/Combobox.test.tsx
// This file was generated by an AI agent. Do not edit directly.
import { render, screen, fireEvent } from '@testing-library/react';
import userEvent from '@testing-library/user-event';

import { Combobox, resolveClearedSelection } from './Combobox';

beforeAll(() => {
  Object.defineProperty(window.HTMLElement.prototype, 'hasPointerCapture', {
    value: () => false,
    configurable: true
  });
  Object.defineProperty(window.HTMLElement.prototype, 'setPointerCapture', {
    value: () => {},
    configurable: true
  });
  Object.defineProperty(window.HTMLElement.prototype, 'releasePointerCapture', {
    value: () => {},
    configurable: true
  });
  Object.defineProperty(window.HTMLElement.prototype, 'scrollIntoView', {
    value: () => {},
    configurable: true
  });
});

const baseItems = [
  { id: 'artists', option: 'Artists' },
  { id: 'venues', option: 'Venues' },
  { id: 'events', option: 'Events' }
];

describe('Combobox', () => {
  it('renders decorative end icon when showEndIcon is true and no selection exists', () => {
    const { container } = render(
      <Combobox items={baseItems} showEndIcon FormElementProps={{ label: 'Categories' }} />
    );
    const clearAll = screen.queryByRole('button', { name: 'Clear all selections' });
    const hasEndIcon = Boolean(container.querySelector('[data-slot="endIcon"]'));
    expect(clearAll === null && hasEndIcon).toBe(true);
  });

  it('renders the provided startIcon in the startIcon slot', () => {
    const { container } = render(
      <Combobox
        items={baseItems}
        startIcon={<span data-testid="start-icon">S</span>}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    const slot = container.querySelector('[data-slot="startIcon"]');
    expect(slot).toBeTruthy();
    expect(screen.getByTestId('start-icon')).toBeInTheDocument();
  });

  it('omits end icon when selections exist even if showEndIcon is true', () => {
    const { container } = render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        showEndIcon
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(container.querySelector('[data-slot="endIcon"]')).toBeNull();
  });

  it('renders the provided endIcon when showEndIcon is true and no selection exists', () => {
    render(
      <Combobox
        items={baseItems}
        showEndIcon
        endIcon={<span data-testid="custom-end">X</span>}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    const slot = screen.getByTestId('custom-end').closest('[data-slot="endIcon"]');
    expect(slot).toBeTruthy();
  });

  it('renders clear-all button with tabindex -1 when selections exist', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        showEndIcon
        FormElementProps={{ label: 'Categories' }}
      />
    );
    const clearAll = screen.getByRole('button', { name: 'Clear all selections' });
    expect(clearAll).toHaveAttribute('tabindex', '-1');
  });

  it('renders chip dismiss button with tabindex -1', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    const dismiss = screen.getByRole('button', { name: 'Remove Artists' });
    expect(dismiss).toHaveAttribute('tabindex', '-1');
  });

  it('is name-exposed by the FormElement label', () => {
    render(<Combobox items={baseItems} FormElementProps={{ label: 'Categories' }} />);
    expect(screen.getByRole('combobox', { name: 'Categories' })).toBeInTheDocument();
  });

  it('renders placeholder text when no selection is present', () => {
    render(
      <Combobox
        placeholder="Select categories"
        items={baseItems}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByPlaceholderText('Select categories')).toBeInTheDocument();
  });

  it('renders chip dismiss button with accessible label', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        FormElementProps={{ label: 'Categories' }}
        showEndIcon
      />
    );
    expect(screen.getByRole('button', { name: 'Remove Artists' })).toBeInTheDocument();
  });

  it('does not render clear-all button when no selections exist', () => {
    render(<Combobox items={baseItems} showEndIcon FormElementProps={{ label: 'Categories' }} />);
    expect(screen.queryByRole('button', { name: 'Clear all selections' })).toBeNull();
  });

  it('renders clear-all button when selections exist', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        showEndIcon
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByRole('button', { name: 'Clear all selections' })).toBeInTheDocument();
  });

  it('clears selections via the clear-all button', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists', 'venues']}
        showEndIcon
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const input = screen.getByRole('combobox');
    const clearAllButton = screen.getByRole('button', { name: 'Clear all selections' });

    await user.click(clearAllButton);
    expect(handleSelectionChange).toHaveBeenCalledWith([]);
    expect(document.activeElement).toBe(input);
  });

  it('prevents default on clear-all mouse down', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        showEndIcon
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const clearAllButton = screen.getByRole('button', { name: 'Clear all selections' });
    const result = fireEvent.mouseDown(clearAllButton);
    expect(result).toBe(false);
  });

  it('does not open when disabled', () => {
    render(<Combobox items={baseItems} disabled FormElementProps={{ label: 'Categories' }} />);

    const input = screen.getByRole('combobox');
    expect(input).toBeDisabled();
    if (input instanceof HTMLInputElement) {
      input.disabled = false;
      fireEvent.click(input);
    }
    expect(input).toHaveAttribute('aria-expanded', 'false');
  });

  it('renders empty state text when no items are provided', () => {
    render(<Combobox items={[]} defaultOpen FormElementProps={{ label: 'Categories' }} />);
    expect(screen.getByText('No options available')).toBeInTheDocument();
  });

  it('renders empty state when items prop is omitted (undefined)', () => {
    render(<Combobox defaultOpen FormElementProps={{ label: 'Categories' }} />);
    expect(screen.getByText('No options available')).toBeInTheDocument();
  });

  it('omits the placeholder when selections exist', () => {
    render(
      <Combobox
        placeholder="Select categories"
        items={baseItems}
        defaultSelectedIds={['artists']}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    expect(screen.getByRole('combobox')).not.toHaveAttribute('placeholder');
  });

  it('keeps focus on the input during option mouse down (prevents blur)', async () => {
    const user = userEvent.setup();
    render(<Combobox items={baseItems} FormElementProps={{ label: 'Categories' }} />);

    const input = screen.getByRole('combobox');
    await user.click(input);
    const option = await screen.findByRole('option', { name: 'Artists' });

    fireEvent.mouseDown(option);
    expect(document.activeElement).toBe(input);
  });

  it('calls onSelectionChange when clicking an option (selects Artists)', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn<void, [string[]]>();
    render(
      <Combobox
        items={baseItems}
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    await user.click(screen.getByRole('combobox'));
    const option = await screen.findByRole('option', { name: 'Artists' });
    await user.click(option);
    expect(handleSelectionChange).toHaveBeenCalledWith(['artists']);
  });

  it('closes the popover when clicking outside', async () => {
    const user = userEvent.setup();
    render(
      <div>
        <Combobox items={baseItems} FormElementProps={{ label: 'Categories' }} />
        <button type="button">Outside</button>
      </div>
    );

    const input = screen.getByRole('combobox');
    await user.click(input);
    expect(screen.getByRole('option', { name: 'Artists' })).toBeInTheDocument();

    const outsideButton = screen.getByText('Outside');
    await user.click(outsideButton);

    expect(input).toHaveAttribute('aria-expanded', 'false');
    expect(screen.queryByRole('option', { name: 'Artists' })).toBeNull();
  });

  it('does not attempt to open when already open (click input is a no-op)', async () => {
    const user = userEvent.setup();
    render(<Combobox items={baseItems} defaultOpen FormElementProps={{ label: 'Categories' }} />);
    const input = screen.getByRole('combobox');

    expect(input).toHaveAttribute('aria-expanded', 'true');

    await user.click(input);

    expect(input).toHaveAttribute('aria-expanded', 'true');
  });

  it('prevents default on chip dismiss mouse down', () => {
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const dismiss = screen.getByRole('button', { name: 'Remove Artists' });
    const result = fireEvent.mouseDown(dismiss);
    expect(result).toBe(false);
  });

  it('removes a chip and returns focus to the input on dismiss click', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn<void, [string[]]>();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const input = screen.getByRole('combobox');
    const dismiss = screen.getByRole('button', { name: 'Remove Artists' });

    await user.click(dismiss);

    expect(handleSelectionChange).toHaveBeenCalledWith([]);
    expect(document.activeElement).toBe(input);
  });

  it('ignores chip dismiss when the combobox is disabled', async () => {
    const handleSelectionChange = jest.fn<void, [string[]]>();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        disabled
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const dismiss = screen.getByRole('button', { name: 'Remove Artists' });
    expect(dismiss).toBeDisabled();
    const user = userEvent.setup({ pointerEventsCheck: 0 });
    await user.click(dismiss);

    expect(handleSelectionChange).not.toHaveBeenCalled();
    expect(screen.getByRole('button', { name: 'Remove Artists' })).toBeInTheDocument();
  });

  it('ignores clear-all when disabled', async () => {
    const handleSelectionChange = jest.fn<void, [string[]]>();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists', 'venues']}
        showEndIcon
        disabled
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const clearAll = screen.getByRole('button', { name: 'Clear all selections' });
    expect(clearAll).toBeDisabled();
    const user = userEvent.setup({ pointerEventsCheck: 0 });
    await user.click(clearAll);

    expect(handleSelectionChange).not.toHaveBeenCalled();
    expect(screen.getByRole('button', { name: 'Clear all selections' })).toBeInTheDocument();
  });

  it('deselects an already-selected option when clicked', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn<void, [string[]]>();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists']}
        defaultOpen
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    const option = await screen.findByRole('option', { name: 'Artists' });
    await user.click(option);
    expect(handleSelectionChange).toHaveBeenCalledWith([]);
  });

  it('deselects only the clicked id when multiple are selected', async () => {
    const user = userEvent.setup();
    const handleSelectionChange = jest.fn<void, [string[]]>();
    render(
      <Combobox
        items={baseItems}
        defaultSelectedIds={['artists', 'venues']}
        defaultOpen
        onSelectionChange={handleSelectionChange}
        FormElementProps={{ label: 'Categories' }}
      />
    );
    const option = await screen.findByRole('option', { name: 'Artists' });
    await user.click(option);
    expect(handleSelectionChange).toHaveBeenCalledWith(['venues']);
  });

  it('respects an explicit menuItemBorderBottom override', async () => {
    render(
      <Combobox
        items={baseItems}
        menuItemBorderBottom={false}
        defaultOpen
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const option = await screen.findByRole('option', { name: 'Artists' });
    expect(option).toHaveAttribute('data-border-bottom', 'false');
  });

  it('defaults complex menu items to no bottom border', async () => {
    render(
      <Combobox
        items={baseItems}
        menuItemType="complex"
        defaultOpen
        FormElementProps={{ label: 'Categories' }}
      />
    );

    const options = await screen.findAllByRole('option');
    for (const option of options) {
      expect(option).toHaveAttribute('data-border-bottom', 'false');
    }
  });

  describe('helper functions', () => {
    it('resolveClearedSelection requires enabled state and selection', () => {
      expect(resolveClearedSelection(false, true)).toBe(true);
      expect(resolveClearedSelection(true, true)).toBe(false);
      expect(resolveClearedSelection(false, false)).toBe(false);
    });
  });
});
