// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Combobox, type ComboboxProps } from './Combobox';
import {
  ArtistIcon,
  CloseIcon,
  EventIcon,
  MapIcon,
  SearchIcon,
  StadiumIcon
} from '../../icons';

const simpleItems = [
  { id: 'artists', option: 'Artists' },
  { id: 'venues', option: 'Venues' },
  { id: 'events', option: 'Events' },
  { id: 'guides', option: 'Guides' },
  { id: 'news', option: 'News' }
];

const complexItems = [
  {
    id: 'stadiums',
    option: 'Stadiums',
    supportingText: 'Large venues with 40k+ capacity',
    mediaIcon: <StadiumIcon aria-hidden="true" />
  },
  {
    id: 'festivals',
    option: 'Festivals',
    supportingText: 'Multi-day outdoor experiences',
    mediaIcon: <EventIcon aria-hidden="true" />
  },
  {
    id: 'museums',
    option: 'Museums',
    supportingText: 'Indoor cultural exhibits',
    mediaIcon: <MapIcon aria-hidden="true" />
  }
];

const meta: Meta<ComboboxProps> = {
  title: 'Components/Combobox',
  component: Combobox,
  args: {
    FormElementProps: {
      label: 'Categories',
      hint: 'Select any categories to filter your results.'
    },
    items: simpleItems,
    showEndIcon: true,
    defaultSelectedIds: ['artists', 'venues']
  }
};

export default meta;

type Story = StoryObj<ComboboxProps>;

export const Default: Story = {};

export const WithStartIcon: Story = {
  args: {
    startIcon: <SearchIcon aria-hidden="true" />,
    placeholder: 'Search collections…',
    defaultSelectedIds: ['artists']
  }
};

export const ComplexItems: Story = {
  args: {
    menuItemType: 'complex',
    menuItemBorderBottom: false,
    items: complexItems,
    FormElementProps: {
      label: 'Experiences',
      info: 'Complex rows include supporting text and media.',
      hint: 'Select one or more experience types.'
    },
    defaultSelectedIds: ['festivals']
  }
};

export const CustomEndIcon: Story = {
  args: {
    endIcon: <CloseIcon aria-hidden="true" />,
    items: simpleItems,
    defaultSelectedIds: ['events', 'guides'],
    FormElementProps: {
      label: 'Content Types',
      hint: 'Remove selections with the custom close icon.'
    }
  }
};

export const Disabled: Story = {
  args: {
    disabled: true,
    defaultSelectedIds: ['venues', 'events']
  }
};

export const Controlled: Story = {
  render: props => {
    const [value, setValue] = React.useState<string[]>(['news']);
    const { defaultSelectedIds, FormElementProps, ...rest } = props;

    return (
      <Combobox
        {...rest}
        selectedIds={value}
        onSelectionChange={setValue}
        items={simpleItems}
        FormElementProps={{
          label: 'Controlled selection',
          hint: 'State for chips is managed by the story.'
        }}
        showEndIcon
      />
    );
  }
};
