// packages/core/src/components/client/Button/Button.stories.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Stories for Button spanning primary/secondary/bare/knockout variants and an icon slot example, keeping common args for label, disabled, loading, and type.

import type { Meta, StoryObj } from '@storybook/react';
import * as React from 'react';
import { InfoCircledIcon } from '@radix-ui/react-icons';
import { Button, ButtonProps } from './Button';

const meta: Meta<ButtonProps> = {
  title: 'Client components/Button',
  component: Button,
  args: {
    children: 'Button',
    disabled: false,
    loading: false,
    type: 'button'
  }
};

export default meta;

type Story = StoryObj<ButtonProps>;

export const Primary: Story = {
  args: {
    variant: 'primary'
  }
};

export const Secondary: Story = {
  args: {
    variant: 'secondary'
  }
};

export const Bare: Story = {
  args: {
    variant: 'bare'
  }
};

export const Knockout: Story = {
  args: {
    variant: 'knockout'
  }
};

export const WithIcons: Story = {
  args: {
    variant: 'primary',
    startIcon: <InfoCircledIcon />,
    endIcon: <InfoCircledIcon />
  }
};