import '@testing-library/jest-dom';
// This file was generated by an AI agent. Do not edit directly.
import * as React from 'react';
import { render, screen, waitFor, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { DatePicker } from './DatePicker';

// --- Test-local suppression of Radix Dialog dev warnings ---
// We only filter the two specific accessibility messages emitted by @radix-ui/react-dialog in dev.
// All other console.error/warn traffic is passed through unchanged.
const RADIX_DIALOG_DEV_WARN_PATTERNS = [
  /`DialogContent` requires a `DialogTitle`/, // missing title
  /Missing `Description` or `aria-describedby=\{undefined\}`/ // missing description
];

let __errorSpy: jest.SpyInstance | undefined;
let __warnSpy: jest.SpyInstance | undefined;

beforeAll(() => {
  const passThroughError = console.error.bind(console);
  const passThroughWarn = console.warn.bind(console);

  __errorSpy = jest.spyOn(console, 'error').mockImplementation((...args: unknown[]) => {
    const msg = args.map(a => String(a)).join(' ');
    if (RADIX_DIALOG_DEV_WARN_PATTERNS.some(re => re.test(msg))) return;
    passThroughError(...(args as []));
  });

  __warnSpy = jest.spyOn(console, 'warn').mockImplementation((...args: unknown[]) => {
    const msg = args.map(a => String(a)).join(' ');
    if (RADIX_DIALOG_DEV_WARN_PATTERNS.some(re => re.test(msg))) return;
    passThroughWarn(...(args as []));
  });
});

afterAll(() => {
  __errorSpy?.mockRestore();
  __warnSpy?.mockRestore();
});
// --- end suppression block ---

jest.mock('rsuite', () => {
  return {
    DateRangePicker: React.forwardRef<
      HTMLDivElement,
      {
        onChange?: (value: [unknown, unknown] | null, event?: unknown) => void;
        showOneCalendar?: boolean;
        open?: boolean;
        onClose?: (e?: unknown) => void;
        onOpen?: (e?: unknown) => void;
        container?: () => HTMLElement;
        value?: [unknown, unknown];
        editable?: boolean;
        ranges?: unknown[];
      }
    >((props, ref) => {
      const { onChange, showOneCalendar, open, container, value, editable, ranges } = props;

      container?.();

      React.useEffect(() => {
        const el = container?.();
        if (!el) return;

        const ensurePanel = () => {
          let panel = el.querySelector('.rs-picker-daterange-panel');
          if (open) {
            if (!panel) {
              panel = document.createElement('div');
              panel.className = 'rs-picker-daterange-panel';
              el.insertBefore(panel, el.firstChild);
            }
          } else if (panel) {
            el.removeChild(panel);
          }
        };

        ensurePanel();

        return () => {
          const panel = el.querySelector('.rs-picker-daterange-panel');
          if (panel) el.removeChild(panel);
        };
      }, [container, open]);

      const toTs = (d: unknown) => (d instanceof Date ? String(d.getTime()) : '');
      const v0 = Array.isArray(value) ? toTs(value[0]) : '';
      const v1 = Array.isArray(value) ? toTs(value[1]) : '';

      return (
        <div
          ref={ref}
          role="button"
          tabIndex={0}
          data-testid="date-range-picker"
          data-prop-show-one={showOneCalendar ? 'true' : 'false'}
          data-prop-open={open ? 'true' : 'false'}
          data-prop-value-start={v0}
          data-prop-value-end={v1}
          data-prop-editable={editable ? 'true' : 'false'}
          data-prop-ranges-length={String((ranges ?? []).length)}
          onClick={() => {
            const payload: [unknown, unknown] = [new Date(0), new Date(0)];
            onChange?.(payload);
          }}
          onDoubleClick={(e: React.MouseEvent<HTMLDivElement>) => {
            const payload: [unknown, unknown] = [new Date(0), new Date(0)];
            onChange?.(payload, e.nativeEvent);
          }}
          onKeyDown={(e: React.KeyboardEvent<HTMLDivElement>) => {
            if (e.key === 'Escape') {
              props.onClose?.(e);
            }
            if (e.key === 'Enter' || e.key === 'ArrowDown') {
              props.onOpen?.(e);
            }
            if (e.key === 'Backspace') {
              onChange?.(null);
            }
          }}
        >
          DateRangePicker
        </div>
      );
    })
  };
});

const setupMatchMedia = (initialMatches: boolean) => {
  let matches = initialMatches;
  const listeners = new Set<(event: { matches: boolean }) => void>();

  const mediaQueryList = {
    get matches() {
      return matches;
    },
    media: '(min-width: 1024px)',
    addEventListener: (_event: string, callback: (event: { matches: boolean }) => void) => {
      listeners.add(callback);
    },
    removeEventListener: (_event: string, callback: (event: { matches: boolean }) => void) => {
      listeners.delete(callback);
    }
  } as unknown as MediaQueryList;

  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    value: jest.fn().mockImplementation(() => mediaQueryList)
  });

  const dispatch = (next: boolean) => {
    matches = next;
    listeners.forEach(callback => callback({ matches: next }));
  };

  return { dispatch };
};

describe('DatePicker', () => {
  it('renders wrapper with base token classes', () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const container = screen.getByTestId('date-range-picker').parentElement;
    expect(container?.className).toContain('dxyz-date-picker');
  });

  it('applies fullWidth layout class when enabled', () => {
    setupMatchMedia(false);
    render(<DatePicker fullWidth />);
    const container = screen.getByTestId('date-range-picker').parentElement;
    expect(container?.className).toContain('w-full');
  });

  it('defaults to showOneCalendar=true below lg breakpoint', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
    await waitFor(() => {
      expect(container).toHaveAttribute('data-show-one-calendar', 'true');
    });
  });

  it('defaults to showOneCalendar=false at or above lg breakpoint', async () => {
    setupMatchMedia(true);
    render(<DatePicker />);
    const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
    await waitFor(() => {
      expect(container).not.toHaveAttribute('data-show-one-calendar');
    });
  });

  it('honors explicit showOneCalendar=true', async () => {
    setupMatchMedia(true);
    render(<DatePicker showOneCalendar />);
    const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
    await waitFor(() => {
      expect(container).toHaveAttribute('data-show-one-calendar', 'true');
    });
  });

  it('honors explicit showOneCalendar=false', async () => {
    setupMatchMedia(false);
    render(<DatePicker showOneCalendar={false} />);
    const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
    await waitFor(() => {
      expect(container).not.toHaveAttribute('data-show-one-calendar');
    });
  });

  it('forwards onChange to rsuite DateRangePicker', async () => {
    setupMatchMedia(false);
    const handleChange = jest.fn();
    const user = userEvent.setup();
    render(<DatePicker onChange={handleChange} />);
    await user.click(screen.getByRole('button', { name: 'DateRangePicker' }));
    expect(handleChange).toHaveBeenCalledTimes(1);
  });

  it('merges custom className on the wrapper', () => {
    setupMatchMedia(false);
    render(<DatePicker className="u-test" />);
    const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
    expect(container.className).toContain('u-test');
  });

  it('passes effective showOneCalendar to rsuite (responsive default)', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-show-one', 'true');
    });
  });

  it('passes explicit showOneCalendar=false to rsuite', async () => {
    setupMatchMedia(false);
    render(<DatePicker showOneCalendar={false} />);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-show-one', 'false');
    });
  });

  it('opens the RSuite picker when clicking the visible Input', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);

    const input = screen.getByTestId('date-picker-input');
    await userEvent.click(input);

    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'true');
    });
  });

  it('defaults safely when window.matchMedia is unavailable (no-support path)', async () => {
    const originalMatchMedia = window.matchMedia;

    (window as unknown as { matchMedia: typeof window.matchMedia | null }).matchMedia = null;

    try {
      render(<DatePicker />);

      const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
      await waitFor(() => {
        expect(container).toHaveAttribute('data-show-one-calendar', 'true');
      });
    } finally {
      (window as unknown as { matchMedia: typeof window.matchMedia }).matchMedia =
        originalMatchMedia;
    }
  });

  it('responds to breakpoint change events (toggles one/two calendar after mount)', async () => {
    const { dispatch } = setupMatchMedia(false);
    render(<DatePicker />);

    act(() => {
      dispatch(true);
    });

    const container = screen.getByTestId('date-range-picker').parentElement as HTMLElement;
    await waitFor(() => {
      expect(container).not.toHaveAttribute('data-show-one-calendar');
    });
  });

  it('closes in uncontrolled mode when RSuite fires onClose (Escape)', async () => {
    setupMatchMedia(false);
    render(<DatePicker defaultOpen />);
    const inner = screen.getByTestId('date-range-picker');

    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'true');
    });

    inner.focus();
    await userEvent.keyboard('{Escape}');

    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'false');
    });
  });

  it('calls user onClose in controlled mode even if open stays true', async () => {
    setupMatchMedia(false);
    const onClose = jest.fn();
    render(<DatePicker open onClose={onClose} />);

    const inner = screen.getByTestId('date-range-picker');
    inner.focus();
    await userEvent.keyboard('{Escape}');

    await waitFor(() => {
      expect(onClose).toHaveBeenCalledTimes(1);
    });
  });

  it('forwards wrapper element to a callback ref on mount', () => {
    setupMatchMedia(false);
    let received: HTMLDivElement | null = null;
    render(
      <DatePicker
        ref={element => {
          received = element;
        }}
      />
    );
    expect(received).toBeInstanceOf(HTMLDivElement);
  });

  it('calls callback ref with null on unmount', () => {
    setupMatchMedia(false);
    let last: HTMLDivElement | null = null;
    const { unmount } = render(
      <DatePicker
        ref={element => {
          last = element;
        }}
      />
    );
    unmount();
    expect(last).toBeNull();
  });

  it('sets object ref.current to wrapper element on mount', () => {
    setupMatchMedia(false);
    const objRef = React.createRef<HTMLDivElement>();
    render(<DatePicker ref={objRef} />);
    expect(objRef.current).toBeInstanceOf(HTMLDivElement);
  });

  it('clears object ref.current on unmount', () => {
    setupMatchMedia(false);
    const objRef = React.createRef<HTMLDivElement>();
    const { unmount } = render(<DatePicker ref={objRef} />);
    unmount();
    expect(objRef.current).toBeNull();
  });

  it('does not open when disabled (early return path)', async () => {
    setupMatchMedia(false);
    render(<DatePicker disabled />);

    const inner = screen.getByTestId('date-range-picker');
    inner.focus();
    await userEvent.keyboard('{Enter}');

    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'false');
    });
  });

  it('prevents default on Enter key in the visible Input', () => {
    setupMatchMedia(false);
    render(<DatePicker />);

    const input = screen.getByTestId('date-picker-input');
    const ev = new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true });
    input.dispatchEvent(ev);

    expect(ev.defaultPrevented).toBe(true);
  });

  it('opens the RSuite picker on ArrowDown key in the visible Input', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);

    const input = screen.getByTestId('date-picker-input');
    const ev = new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true });
    input.dispatchEvent(ev);

    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'true');
    });
  });

  it('initializes effective value from defaultValue (internal)', () => {
    setupMatchMedia(false);
    const d0 = new Date(2020, 0, 1);
    const d1 = new Date(2020, 0, 2);
    render(<DatePicker defaultValue={[d0, d1]} />);
    const inner = screen.getByTestId('date-range-picker');
    expect(inner).toHaveAttribute('data-prop-value-start', String(d0.getTime()));
  });

  it('updates internal value on onChange in uncontrolled mode', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const inner = screen.getByTestId('date-range-picker');
    await userEvent.click(inner);
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-value-start', '0');
    });
  });

  it('does not change effective value in controlled mode on onChange (calls user handler)', async () => {
    setupMatchMedia(false);
    const d0 = new Date(2021, 0, 1);
    const d1 = new Date(2021, 0, 2);
    const onChange = jest.fn();
    render(<DatePicker value={[d0, d1]} onChange={onChange} />);
    const inner = screen.getByTestId('date-range-picker');

    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-value-start', String(d0.getTime()));
    });

    await userEvent.click(inner);

    await waitFor(() => {
      expect(onChange).toHaveBeenCalledTimes(1);
    });
  });

  it('forwards null to onChange when the picker clears value', async () => {
    setupMatchMedia(false);
    const spy = jest.fn();
    render(<DatePicker onChange={spy} />);
    const inner = screen.getByTestId('date-range-picker');
    inner.focus();
    await userEvent.keyboard('{Backspace}');
    await waitFor(() => {
      expect(spy).toHaveBeenCalledWith(null, undefined);
    });
  });

  it('calls user onOpen when clicking the visible Input', async () => {
    setupMatchMedia(false);
    const onOpen = jest.fn();
    render(<DatePicker onOpen={onOpen} />);

    const input = screen.getByTestId('date-picker-input');
    await userEvent.click(input);

    await waitFor(() => {
      expect(onOpen).toHaveBeenCalledTimes(1);
    });
  });

  it('calls user onOpen when RSuite triggers onOpen (Enter)', async () => {
    setupMatchMedia(false);
    const onOpen = jest.fn();
    render(<DatePicker onOpen={onOpen} />);

    const inner = screen.getByTestId('date-range-picker');
    inner.focus();
    await userEvent.keyboard('{Enter}');

    await waitFor(() => {
      expect(onOpen).toHaveBeenCalledTimes(1);
    });
  });

  it('does not open when controlled open=false and clicking the visible Input', async () => {
    setupMatchMedia(false);
    render(<DatePicker open={false} />);
    const input = screen.getByTestId('date-picker-input');
    await userEvent.click(input);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'false');
    });
  });

  it('applies disabled attribute to the visible Input when disabled', () => {
    setupMatchMedia(false);
    render(<DatePicker disabled />);
    const input = screen.getByTestId('date-picker-input');
    expect(input).toBeDisabled();
  });

  it('sets aria-expanded="true" on the visible Input when opened', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const input = screen.getByTestId('date-picker-input');
    await userEvent.click(input);
    await waitFor(() => {
      expect(input).toHaveAttribute('aria-expanded', 'true');
    });
  });

  it('sets aria-expanded="false" on the visible Input after closing', async () => {
    setupMatchMedia(false);
    render(<DatePicker defaultOpen />);
    const input = screen.getByTestId('date-picker-input');
    const inner = screen.getByTestId('date-range-picker');
    inner.focus();
    await userEvent.keyboard('{Escape}');
    await waitFor(() => {
      expect(input).toHaveAttribute('aria-expanded', 'false');
    });
  });

  it('prevents default on ArrowDown key in the visible Input', () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const input = screen.getByTestId('date-picker-input');
    const ev = new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true });
    input.dispatchEvent(ev);
    expect(ev.defaultPrevented).toBe(true);
  });

  it('honors defaultOpen on initial render (uncontrolled)', async () => {
    setupMatchMedia(false);
    render(<DatePicker defaultOpen />);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'true');
    });
  });

  it('forwards (value, undefined) to onChange when RSuite provides only value', async () => {
    setupMatchMedia(false);
    const spy = jest.fn();
    render(<DatePicker onChange={spy} />);
    const inner = screen.getByTestId('date-range-picker');
    await userEvent.click(inner);
    await waitFor(() => {
      expect(spy).toHaveBeenCalledWith([new Date(0), new Date(0)], undefined);
    });
  });

  it('does not open on unrelated keydown (Tab) in the visible Input', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const input = screen.getByTestId('date-picker-input');
    const ev = new KeyboardEvent('keydown', { key: 'Tab', bubbles: true, cancelable: true });
    input.dispatchEvent(ev);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'false');
    });
  });

  it('passes editable=false to RSuite DateRangePicker', () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const inner = screen.getByTestId('date-range-picker');
    expect(inner).toHaveAttribute('data-prop-editable', 'false');
  });

  it('forwards (value, event) to onChange when RSuite provides both (dblclick path)', async () => {
    setupMatchMedia(false);
    const spy = jest.fn();
    render(<DatePicker onChange={spy} />);
    const inner = screen.getByTestId('date-range-picker');
    await userEvent.dblClick(inner);
    await waitFor(() => {
      expect(spy).toHaveBeenCalledWith([new Date(0), new Date(0)], expect.any(Event));
    });
  });

  it('treats controlled undefined value as empty effective value', () => {
    setupMatchMedia(false);
    render(<DatePicker value={undefined as unknown as [Date, Date]} />);
    const inner = screen.getByTestId('date-range-picker');
    expect(inner).toHaveAttribute('data-prop-value-start', '');
  });

  it('handles both Enter and ArrowDown on the visible Input (prevent + open)', async () => {
    setupMatchMedia(false);
    render(<DatePicker />);
    const input = screen.getByTestId('date-picker-input');

    const ev = new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true });
    input.dispatchEvent(ev);
    expect(ev.defaultPrevented).toBe(true);

    const ev2 = new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true });
    input.dispatchEvent(ev2);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'true');
    });
  });

  it('uses default placeholder when InputProps provided without placeholder', () => {
    setupMatchMedia(false);
    render(<DatePicker InputProps={{ 'aria-label': 'probe-1' }} />);
    const input = screen.getByTestId('date-picker-input');
    expect(input).toHaveAttribute('placeholder', 'Select a date range');
  });

  it('spreads InputProps onto the visible Input', () => {
    setupMatchMedia(false);
    render(<DatePicker InputProps={{ 'aria-label': 'ok' }} />);
    const input = screen.getByTestId('date-picker-input');
    expect(input).toHaveAttribute('aria-label', 'ok');
  });

  it('renders custom top ranges on mobile when open', async () => {
    setupMatchMedia(false);
    render(<DatePicker defaultOpen />);
    await waitFor(() => {
      expect(screen.getByText('Today')).toBeInTheDocument();
    });
    const inner = screen.getByTestId('date-range-picker');
    expect(inner).toHaveAttribute('data-prop-ranges-length', '0');
  });

  it('clicking a custom range applies value and closes on mobile', async () => {
    setupMatchMedia(false);
    const onChange = jest.fn();
    render(<DatePicker defaultOpen onChange={onChange} />);
    await waitFor(() => {
      expect(screen.getByText('Today')).toBeInTheDocument();
    });
    await userEvent.click(screen.getByText('Today'));
    expect(onChange).toHaveBeenCalledTimes(1);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-open', 'false');
    });
  });

  it('does not render custom toolbar on desktop; passes ranges to RSuite', async () => {
    setupMatchMedia(true);
    render(<DatePicker defaultOpen />);
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-ranges-length', '3');
    });
    expect(screen.queryByTestId('daterange-predefined-top')).toBeNull();
    expect(screen.queryByText('Today')).toBeNull();
  });

  it('switches toolbars when toggling breakpoint while open', async () => {
    const { dispatch } = setupMatchMedia(false);
    render(<DatePicker defaultOpen />);
    await waitFor(() => {
      expect(screen.getByText('Today')).toBeInTheDocument();
    });
    act(() => {
      dispatch(true);
    });
    const inner = screen.getByTestId('date-range-picker');
    await waitFor(() => {
      expect(inner).toHaveAttribute('data-prop-ranges-length', '3');
      expect(screen.queryByText('Today')).toBeNull();
    });
  });
});
