// packages/core/src/components/server/Visibility/Visibility.stories.tsx
// Generated by AI (Eventz agents). Do not edit directly.
// Summary: Stories demonstrating Visibility baseline render plus breakpoint-bound examples using from/to props.

import type { Meta, StoryObj } from '@storybook/react-vite';
import { Markdown } from '@storybook/addon-docs/blocks';
import * as React from 'react';
import { Visibility, type VisibilityProps } from './Visibility';
import Readme from './README.md?raw';

const demoContainerStyle: React.CSSProperties = {
  display: 'grid',
  gap: '1rem'
};

const demoBlockStyle: React.CSSProperties = {
  border: '1px dashed #94a3b8',
  borderRadius: '0.75rem',
  padding: '1rem'
};

const demoLabelStyle: React.CSSProperties = {
  fontWeight: 600,
  marginBottom: '0.25rem'
};

const demoDescriptionStyle: React.CSSProperties = {
  fontSize: '0.875rem',
  color: '#475569'
};

const meta: Meta<VisibilityProps> = {
  title: 'Server components/Visibility',
  component: Visibility,
  tags: ['autodocs'],
  args: {
    children: 'Responsive content block',
    className: ''
  },
  parameters: {
    docs: {
      page: () => <Markdown>{Readme}</Markdown>
    },
    controls: {
      include: ['from', 'to', 'className']
    }
  }
};

export default meta;

type Story = StoryObj<VisibilityProps>;

export const Default: Story = {
  args: {}
};

const ExampleBlock = ({ label, description }: { label: string; description: string }) => (
  <div style={demoBlockStyle}>
    <div style={demoLabelStyle}>{label}</div>
    <div style={demoDescriptionStyle}>{description}</div>
  </div>
);

export const Examples: Story = {
  render: () => (
    <div style={demoContainerStyle}>
      <Visibility from="lg">
        <ExampleBlock label='from="lg"' description="Hidden until lg breakpoint." />
      </Visibility>
      <Visibility to="xl">
        <ExampleBlock label='to="xl"' description="Visible until xl breakpoint." />
      </Visibility>
      <Visibility from="md" to="xl">
        <ExampleBlock label='from="md" to="xl"' description="Visible only between md and xl." />
      </Visibility>
      <Visibility from="xl" to="md">
        <ExampleBlock label='from="xl" to="md"' description="Visible outside md..xl." />
      </Visibility>
      <Visibility from="md" to="md">
        <ExampleBlock
          label='from="md" to="md"'
          description="Hidden everywhere (conflicting bounds)."
        />
      </Visibility>
    </div>
  )
};
