// packages/core/src/components/server/Badge/Badge.tsx
// Generated by AI (DoXYZ agents). Do not edit directly.
// Summary: Badge renders gradient variants with optional icon slot and label content.

import * as React from 'react';
import { collapseWhitespace, composeClasses } from '../../../utilities';

export interface BadgeProps extends React.HTMLAttributes<HTMLSpanElement> {
  variant?: 'purple' | 'blue' | 'pink' | 'brand' | 'orange';
  icon?: React.ReactNode;
  label?: string;
}

const baseClasses = `
  inline-flex items-center rounded-sm px-1.5 py-0.5
  text-caption-lg-allcaps-bold
`;

const variantClasses: Record<NonNullable<BadgeProps['variant']>, string> = {
  purple: 'bg-gradient-purple',
  blue: 'bg-gradient-blue',
  pink: 'bg-gradient-pink',
  brand: 'bg-brand-500',
  orange: 'bg-gradient-orange'
};

export const Badge = React.forwardRef<HTMLSpanElement, BadgeProps>(
  ({ variant = 'purple', icon, label, className, ...props }, ref) => {
    const rootClassName = collapseWhitespace(
      composeClasses(baseClasses, variantClasses[variant], className)
    );

    return (
      <div>
        <span ref={ref} className={rootClassName} {...props}>
          <span className="flex items-center gap-1.5">
            {icon && (
              <span className="shrink-0 h-20" aria-hidden="true">
                {icon}
              </span>
            )}
            {label && <span>{label}</span>}
          </span>
        </span>
      </div>
    );
  }
);

Badge.displayName = 'Badge';
